export const data = {
  Laghouat: {
    Aflou: "Aflou - أفلو",
    "Aïn Madhi": "Ain Madhi - عين ماضي",
    "Aïn Sidi Ali": "Ain Sidi Ali - عين سهيه علي",
    Beidha: "Beidha - بيضاء",
    "Bennasser Benchohra": "Benacer Benchohra - بن ناصر بن شهرة",
    Brida: "Brida - بريدة",
    "El Assafia": "El Assafia - العسفية",
    "El Ghicha": "El Ghicha - الغيشة",
    "El Houaita": "El Haouaita - الحويطة",
    "Gueltat Sidi Saad": "Gueltat Sidi Saad - قتلة سيدي سعيد",
    "Hadj Mechri": "Hadj Mechri - الحاج مشري",
    "Hassi Delaa": "Hassi Delaa - حاسي الدلاعة",
    "Hassi R'Mel": "Hassi R'mel - حاسي الرمل",
    Kheneg: "Kheneg - الخنق",
    "Ksar El Hirane": "Ksar El Hirane - قصر الحيران",
    Laghouat: "Laghouat - الأغواط",
    "Oued M'Zi": "Oued M'zi - وادي مزي",
    "Oued Morra": "Oued Morra - وادي مرة",
    Sebgag: "Sebgag - سبقاق",
    "Sidi Bouzid": "Sidi Bouzid - سيدي بوزيد",
    "Sidi Makhlouf": "Sidi Makhlouf - سيدي مخلوف",
    Tadjemout: "Tadjemout - تاجموت",
    Tadjrouna: "Tadjrouna - تاجرونة",
    Taouiala: "Taouiala - تاويالة",
  },
  Chlef: {
    "Abou El Hassan": "Abou El Hassan - أبو الحسين",
    "Aïn Merane": "Ain Merane - عين مران",
    Bénairia: "Benairia - بنايرية",
    "Beni Bouateb": "Beni Bouattab - بني بوعتاب",
    "Beni Haoua": "Beni Haoua - بني حواء",
    "Beni Rached": "Beni Rached - بني راشد",
    Boukadir: "Boukadir - بوقادير",
    Bouzeghaia: "Bouzeghaia - بوزغاية",
    Breira: "Breira - بريرة",
    Chettia: "Chettia - الشطية",
    Chlef: "Chlef - الشلف",
    Dahra: "Dahra - الظهر",
    "El Hadjadj": "El Hadjadj - الحجاج",
    "El Karimia": "El Karimia - الكريمية",
    "El Marsa": "El Marsa - المرسى",
    Harchoun: "Harchoun - حرشون",
    Harenfa: "Herenfa - الهرنفة",
    "Labiod Medjadja": "Labiod Medjadja - الأبيض مجاجة",
    Moussadek: "Moussadek - مصدق",
    "Oued Fodda": "Oued Fodda - وادي الفضة",
    "Oued Goussine": "Oued Goussine - وادي قوسين",
    "Oued Sly": "Oued Sly - وادي سلي",
    "Ouled Abbes": "Ouled Abbes - أولاد عباس",
    "Ouled Ben Abdelkader": "Ouled Ben Abdelkader - أولاد بن عبد القادر",
    "Ouled Fares": "Ouled Fares - أولاد فارس",
    "Oum Drou": "Oum Drou - أم الدروع",
    Sendjas: "Sendjas - السنجاس",
    "Sidi Abderrahmane": "Sidi Abderrahmane - سيدي عبد الرحمن",
    "Sidi Akkacha": "Sidi Akkacha - سيدي عكاشة",
    Sobha: "Sobha - صبحة",
    Tadjena: "Tadjena - تاجنة",
    Talassa: "Talassa - تلعصة",
    Taougrite: "Taougrite - تاقريت",
    Ténès: "Tenes - تنس",
    Zeboudja: "Zeboudja - الزبوجة",
  },
  Béjaïa: {
    Adekar: "Adekar - أدكار",
    "Ait Djellil": "Beni Dejllil - بني جليل",
    "Aït Ksila": "Beni Ksila - بني كسيلة",
    "Aït Maouche": "Beni maouche - بني معوش",
    "Aït Mellikeche": "Beni-mallikeche - بني مليكش",
    "Aït R'zine": "Ait R'zine - أيت رزين",
    "Aït Smail": "Ait-smail - أيت إسماعيل",
    Akbou: "Akbou - أقبو",
    Akfadou: "Akfadou - أكفادو",
    Amalou: "Amalou - أمالو",
    Amizour: "Amizour - أميزور",
    Aokas: "Aokas - أوقاس",
    Barbacha: "Barbacha - برباشة",
    Béjaïa: "Bejaia - بجاية",
    Boudjellil: "Boudjellil - بو جليل",
    Bouhamza: "Bouhamza - بوحمزة",
    Boukhelifa: "Boukhelifa - بوخليفة",
    Chellata: "Chellata - شلاطة",
    Chemini: "Chemini - شميني",
    Darguina: "Darghina - درقينة",
    "Draâ El Kaïd": "Dra El Caid - ذراع القايد",
    "El Kseur": "El Kseur - القصر",
    "Fenaïa Ilmaten": "Fenaia Il Maten - فلاين الماثن",
    Ferraoun: "Feraoun - فرعون",
    "Ighil Ali": "Ighil-ali - إغيل علي",
    Ighram: "Ighram - إغرم",
    Kendira: "Kendira - كنديرة",
    Kherrata: "Kherrata - خراطة",
    Leflaye: "Leflaye - لفلاي",
    "M'cisna": "M'cisna - مسيسنة",
    Melbou: "Melbou - مالبو",
    "Oued Ghir": "Oued Ghir - وادي غير",
    Ouzellaguen: "Ouzellaguene - أوزلاقن",
    Seddouk: "Seddouk - صدوق",
    Semaoun: "Smaoun - سمعون",
    "Sidi Aïch": "Sidi-aich - سيدي عيش",
    "Sidi Ayad": "Sidi Ayad - سيدي عياد",
    "Souk El Ténine": "Souk El Tenine - سوق لإثنين",
    "Souk Oufella": "Souk Oufella - السوق أوفلا",
    "Tala Hamza": "Tala Hamza - تالة حمزة",
    Tamokra: "Tamokra - تامقرة",
    Tamridjet: "Tamridjet - تامريجت",
    "Taourirt Ighil": "Taourit Ighil - تاوريرت إغيل",
    Taskriout: "Taskriout - تاسكريوت",
    Tazmalt: "Tazmalt - تزمالت",
    Tibane: "Tibane - طيبان",
    Tichy: "Tichy - تيشي",
    Tifra: "Tifra - تيفرة",
    Timezrit: "Timezrit - تيمزريت",
    Tinabdher: "Tinebdar - تينبدار",
    "Tizi N'Berber": "Tizi-n'berber - تيزي نبربر",
    Toudja: "Toudja - توجة",
  },
  Bouira: {
    Aghbalou: "Aghbalou - أغبالو",
    "Ahl El Ksar": "Ahl El Ksar - أهل القصر",
    "Aïn Bessem": "Ain-bessem - عين بسام",
    "Aïn El Hadjar": "Ain El Hadjar - عين الحجر",
    "Aïn El Turc": "Ain Turk - عين الترك",
    "Aïn Laloui": "Ain Laloui - عين العلوي",
    "Aït Laziz": "Ait Laaziz - أيت لعزيز",
    Aomar: "Aomar - أعمر",
    "Ath Mansour": "Ath Mansour Taourirt - تاوريرت",
    Bechloul: "Bechloul - بشلول",
    "Bir Ghbalou": "Bir Ghbalou - بئر غبالو",
    "Bordj Okhriss": "Bordj Okhriss - برج أوخريص",
    Bouderbala: "Bouderbala - بودربالة",
    Bouira: "Bouira - البويرة",
    Boukram: "Boukram - بوكرم",
    Chorfa: "Chorfa - الشرفاء",
    Dechmia: "Dechmia - الدشمية",
    Dirrah: "Dirah - ديرة",
    Djebahia: "Djebahia - جباحية",
    "El Adjiba": "El Adjiba - العجيبة",
    "El Asnam": "El Asnam - الأسنام",
    "El Hachimia": "El Hachimia - الهاشمية",
    "El Hakimia": "El-hakimia - الحاكمية",
    "El Khabouzia": "El Khabouzia - الخبوزية",
    "El Mokrani": "El-mokrani - المقراني",
    Guerrouma: "Guerrouma - قرومة",
    "Hadjera Zerga": "Hadjera Zerga - الحجرة الزرقاء",
    Haizer: "Haizer - الحيزر",
    Hanif: "Hanif - حنيف",
    Kadiria: "Kadiria - القادرية",
    Lakhdaria: "Lakhdaria - الأخضرية",
    "M'Chedallah": "Mchedallah - مشد الله",
    Maala: "Maala - معلة",
    Maamora: "Maamora - المعمورة",
    Mezdour: "Mezdour - مزدور",
    "Oued El Berdi": "Oued El Berdi - وادي البردي",
    "Ouled Rached": "Ouled Rached - أولاد راشد",
    Raouraoua: "Raouraoua - روراوة",
    Ridane: "Ridane - ريدان",
    Saharidj: "Saharidj - الصهايج",
    "Souk El Khemis": "Souk El Khemis - سوق الخميس",
    "Sour El Ghouzlane": "Sour El Ghozlane - سور الغزلان",
    Taghzout: "Taghzout - تاغزوت",
    Taguedit: "Taguedite - تاقديت",
    Zbarbar: "Zbarbar - زبربر",
  },
  Tlemcen: {
    "Aïn Fetah": "Ain Fettah - عين فتاح",
    "Aïn Fezza": "Ain Fezza - عين فزة",
    "Aïn Ghoraba": "Ain Ghoraba - عين الغرابة",
    "Aïn Kebira": "Ain Kebira - العين الكبيرة",
    "Aïn Nehala": "Ain Nehala - عين نحالة",
    "Aïn Tallout": "Ain Tallout - عين تالوت",
    "Aïn Youcef": "Ain Youcef - عين يوسف",
    Amieur: "Amieur - عمير",
    Azails: "Azails - العزايل",
    "Bab El Assa": "Bab El Assa - باب العسة",
    "Beni Bahdel": "Beni Bahdel - بني بهدل",
    "Beni Boussaid": "Beni Boussaid - بني بوسعيد",
    "Beni Khellad": "Beni Khaled - بني راشد",
    "Beni Mester": "Beni Mester - بني مستر",
    "Beni Ouarsous": "Beni Ouarsous - بني وارسوس",
    "Beni Semiel": "Beni Smiel - بني صميل",
    "Beni Snous": "Beni Snous - بني سنوس",
    Bensekrane: "Bensekrane - إبن سكران",
    Bouhlou: "Bouhlou - بوحلو",
    Chetouane: "Chetouane - شتوان",
    "Dar Yaghmouracene": "Dar Yaghmouracene - دار يغمراسن",
    Djebala: "Djebala - جبالة",
    "El Aricha": "El Aricha - العريشة",
    "El Bouihi": "Bouihi - البويهي",
    "El Fehoul": "El Fehoul - الفحول",
    "El Gor": "El Gor - القور",
    Fellaoucene: "Fellaoucene - فلاوسن",
    Ghazaouet: "Ghazaouet - الغزوات",
    "Hammam Boughrara": "Hammam Boughrara - حمام بوغرارة",
    Hennaya: "Hennaya - الحناية",
    Honaïne: "Honaine - حنين",
    Maghnia: "Maghnia - مغنية",
    Mansourah: "Mansourah - منصورة",
    "Marsa Ben M'Hidi": "Marsa Ben M'hidi - مرسى بن مهيدي",
    "MSirda Fouaga": "Msirda Fouaga - مسيردة الفواقة",
    Nedroma: "Nedroma - ندرومة",
    "Oued Lakhdar": "oued lakhdar - واد لخضر",
    "Ouled Mimoun": "Ouled Mimoun - أولاد ميمون",
    "Ouled Riyah": "Ouled Riyah - أولاد رياح",
    Remchi: "Remchi - الرمشي",
    Sabra: "Sabra - صبرة",
    "Sebaa Chioukh": "Sebbaa Chioukh - السبعة شيوخ",
    Sebdou: "Sebdou - سبدو",
    "Sidi Abdelli": "Sidi Abdelli - سيدي عبد اللي",
    "Sidi Djillali": "Sidi Djilali - سيدي الجيلالي",
    "Sidi Medjahed": "Sidi Medjahed - سيدي مجاهد",
    Souahlia: "Souahlia - السواحلية",
    Souani: "Souani - السواني",
    "Souk Tlata": "Souk Tleta - سوق الثلاثاء",
    "Terny Beni Hdiel": "Terny Beni Hediel - تيرني بني هديل",
    Tienet: "Tianet - تيانت",
    Tlemcen: "Tlemcen - تلمسان",
    Zenata: "Zenata - زناتة",
  },
  Djelfa: {
    "Aïn Chouhada": "Ain Chouhada - عين الشهداء",
    "Aïn El Ibel": "Ain El Ibel - عين الإبل",
    "Aïn Feka": "Ain Fekka - عين فكة",
    "Aïn Maabed": "Ain Maabed - عين معبد",
    "Aïn Oussara": "Ain Oussera - عين وسارة",
    Amourah: "Amourah - عمورة",
    Benhar: "Benhar - بنهار",
    "Beni Yagoub": "Benyagoub - بني يعقوب",
    Birine: "Birine - بيرين",
    "Bouira Lahdab": "Bouira Lahdab - بويرة الأحدب",
    Charef: "Charef - الشارف",
    "Dar Chioukh": "Dar Chioukh - دار الشيوخ",
    Deldoul: "Deldoul - دلدول",
    Djelfa: "Djelfa - الجلفة",
    Douis: "Douis - دويس",
    "El Guedid": "El Guedid - القديد",
    "El Idrissia": "El Idrissia - الادريسية",
    "El Khemis": "El Khemis - الخميس",
    "Faidh El Botma": "Faidh El Botma - فيض البطمة",
    Guernini: "Guernini - قرنيني",
    Guettara: "Guettara - القطارة",
    "Had Sahary": "Had Sahary - حد الصحاري",
    "Hassi Bahbah": "Hassi Bahbah - حاسي بحبح",
    "Hassi El Euch": "Hassi El Euch - حاسي العش",
    "Hassi Fedoul": "Hassi Fedoul - حاسي فدول",
    "M'Liliha": "Mliliha - مليليحة",
    Messaad: "Messaad - مسعد",
    Moudjebara: "Moudjebara - مجبرة",
    "Oum Laadham": "Oum Laadham - أم العظام",
    "Sed Rahal": "Sed Rahal - سد الرحال",
    Selmana: "Selmana - سلمانة",
    "Sidi Baizid": "Sidi Baizid - سيدي بايزيد",
    "Sidi Ladjel": "Sidi Ladjel - سيدي لعجل",
    Tadmit: "Tadmit - تاعظميت",
    Zaafrane: "Zaafrane - زعفران",
    Zaccar: "Zaccar - زكار",
  },

  Tébessa: {
    "Aïn Zerga": "Ain Zerga - عين الزرقاء",
    Bedjene: "Bedjene - بجن",
    Bekkaria: "Bekkaria - بكارية",
    "Bir Dheb": "Bir Dheheb - بئر الذهب",
    "Bir el Ater": "Bir El Ater - بئر العاتر",
    "Bir Mokkadem": "Bir Mokkadem - بئر المقدم",
    Boukhadra: "Boukhadra - بوخضرة",
    "Boulhaf Dir": "Boulhaf Dyr - بولحاف الدين",
    Cheria: "Cheria - الشريعة",
    "El Aouinet": "El Aouinet - العوينات",
    "El Houidjbet": "El Houidjbet - الحويجبات",
    "El Kouif": "El Kouif - الكويف",
    "El Ma Labiodh": "El Malabiod - الماء الابيض",
    "El Meridj": "El Meridj - المريج",
    "El Mezeraa": "El Mezeraa - المزرعة",
    "El Ogla": "El Ogla - العقلة",
    Ferkane: "Ferkane - فركان",
    Guorriguer: "Guorriguer - قوريقر",
    Hammamet: "Hammamet - الحمامات",
    Morsott: "Morssot - مرسط",
    Negrine: "Negrine - نقرين",
    "Ogla Melha": "El Ogla El Malha - العقلة المالحة",
    Ouenza: "Ouenza - الونزة",
    "Oum Ali": "Oum Ali - أم علي",
    "Safsaf El Ouesra": "Saf Saf El Ouesra - صفصاف الوسرة",
    "Stah Guentis": "Stah Guentis - سطح قنطيس",
    Tébessa: "Tebessa - تبسة",
    Tlidjene: "Telidjen - ثليجان",
  },
  Béchar: {
    Abadla: "Abadla - العبادل",
    Béchar: "Bechar - بشار",
    "Béni Abbès": "Beni Abbes - بني عباس",
    "Beni Ikhlef": "Beni Ikhlef - بني يخلف",
    "Beni Ounif": "Beni Ounif - بني ونيف",
    Boukais: "Boukais - بوقايس",
    "El Ouata": "El Ouata - الوطاء",
    "Erg Ferradj": "Erg Ferradj - عرق فراج",
    Igli: "Igli - إيقلي",
    Kenadsa: "Kenadsa - قنادسة",
    Kerzaz: "Kerzaz - كرزاز",
    Ksabi: "Ksabi - قصابي",
    Lahmar: "Lahmar - الأحمر",
    "Mechraa Houari Boumedienne": "Mechraa H.boumediene - مشروع هواري بومدين",
    Meridja: "Meridja - مريجة",
    Mougheul: "Mogheul - موغل",
    "Ouled Khoudir": "Ouled Khoudir - أولاد خضير",
    Tabelbala: "Tabelbala - تبلبالة",
    Taghit: "Taghit - تاغيت",
    Tamtert: "Tamtert - تامترت",
    Timoudi: "Timoudi - تيمودي",
  },
  Blida: {
    "Aïn Romana": "Ain Romana - عين الرمانة",
    "Beni Mered": "Beni Mered - بني مراد",
    "Beni Tamou": "Beni-tamou - بني تامو",
    Benkhelil: "Benkhelil - بن خليل",
    Blida: "Blida - البليدة",
    Bouarfa: "Bouarfa - بوعرفة",
    Boufarik: "Boufarik - بوفاريك",
    Bougara: "Bougara - بوقرة",
    Bouinan: "Bouinan - بوعينان",
    Chebli: "Chebli - الشبلي",
    Chiffa: "Chiffa - الشفة",
    Chréa: "Chrea - الشريعة",
    Djebabra: "Djebabra - جبابرة",
    "El Affroun": "El-affroun - العفرون",
    Guerouaou: "Guerrouaou - قرواو",
    "Hammam Melouane": "Hammam Melouane - حمام ملوان",
    Larbaa: "Larbaa - الأربعاء",
    Meftah: "Meftah - مفتاح",
    Mouzaia: "Mouzaia - موزاية",
    "Oued Alleug": "Oued El Alleug - وادي العلايق",
    "Oued Djer": "Oued Djer - وادي جر",
    "Ouled Slama": "Ouled Slama - اولاد سلامة",
    "Ouled Yaïch": "Ouled Yaich - أولاد يعيش",
    Souhane: "Souhane - سوحان",
    Soumaa: "Souma - الصومعة",
  },
  Jijel: {
    "Bordj Tahar": "Bordj Tahar - برج الطاهر",
    "Boucif Ouled Askeur": "Boussif Ouled Askeur - بوسيف أولاد عسكري",
    "Boudriaa Ben Yadjis": "Boudria Beniyadjis - بوذريعة بني ياجيس",
    "Bouraoui Belhadef": "Bouraoui Belhadef - بوراوي بلهادف",
    Chahna: "Chahna - الشحنة",
    Chekfa: "Chekfa - الشقفة",
    "Djemaa Beni Habibi": "Djemaa Beni Habibi - الجمعة بني حبيبي",
    Djimla: "Djimla - جميلة",
    "El Ancer": "El Ancer - العنصر",
    "El Aouana": "El Aouana - العوانة",
    "El Kennar Nouchfi": "El Kennar Nouchfi - القنار نوشفي",
    "El Milia": "El Milia - الميلية",
    "Emir Abdelkader": "Emir Abdelkader - الامير عبد القادر",
    Eraguene: "Erraguene - أراقن",
    Ghebala: "Ghebala - غبالة",
    Jijel: "Jijel - جيجل",
    Kaous: "Kaous - قاوس",
    "Kheïri Oued Adjoul": "Khiri Oued Adjoul - خير وادي عجول",
    Ouadjana: "Oudjana - وجانة",
    "Ouled Rabah": "Ouled Rabah - أولاد رابح",
    "Ouled Yahia Khedrouche": "Ouled Yahia Khadrouch - أولاد يحيى خدروش",
    "Selma Benziada": "Selma Benziada - سلمى بن زيادة",
    Settara: "Settara - السطارة",
    "Sidi Abdelaziz": "Sidi Abdelaziz - سيدي عبد العزيز",
    "Sidi Maarouf": "Sidi Marouf - سيدي معروف",
    Taher: "Taher - الطاهير",
    Texenna: "Texena - تاكسنة",
    "Ziama Mansouriah": "Ziama Mansouria - زيامة منصورية",
  },
  "Sidi Bel Abbès": {
    "Aïn Adden": "Ain Adden - عين عدان",
    "Aïn El Berd": "Ain El Berd - عين البرد",
    "Aïn Kada": "Ain Kada - عين قادة",
    "Aïn Thrid": "Ain Thrid - عين الثريد",
    "Aïn Tindamine": "Ain Tindamine - عين تندمين",
    Amarnas: "Amarnas - امرناس",
    "Badredine El Mokrani": "Badredine El Mokrani - بدر الدين المقراني",
    Belarbi: "Belarbi - بلعربي",
    "Ben Badis": "Ben Badis - بن باديس",
    "Benachiba Chelia": "Benachiba Chelia - بن عشيبة شلية",
    "Bir El Hammam": "Bir El Hammam - بئر الحمام",
    "Boudjebaa El Bordj": "Boudjebaa El Bordj - بوجبع البرج",
    Boukhanafis: "Boukhanafis - بوخنيفيس",
    "Chettouane Belaila": "Chetouane Belaila - شتوان بليلة",
    Dhaya: "Dhaya - الضاية",
    "El Haçaiba": "El Hacaiba - الحصيبة",
    "Hassi Dahou": "Hassi Dahou - حاسي دحو",
    "Hassi Zehana": "Hassi Zahana - حاسي زهانة",
    Lamtar: "Lamtar - لمطار",
    "M'Cid": "Mcid - مسيد",
    Makedra: "Makedra - مقدرة",
    Marhoum: "Marhoum - مرحوم",
    Merine: "Merine - مرين",
    Mezaourou: "Mezaourou - مزاورو",
    "Mostefa Ben Brahim": "Mostefa Ben Brahim - مصطفى بن ابراهيم",
    "Moulay Slissen": "Moulay Slissen - مولاي سليسن",
    "Oued Sebaa": "Oued Sebaa - وادي السبع",
    "Oued Sefioun": "Oued Sefioun - وادي سفيون",
    "Oued Taourira": "Oued Taourira - وادي تاوريرة",
    "Ras El Ma": "Ras El Ma - راس الماء",
    "Redjem Demouche": "Redjem Demouche - رجم دموش",
    "Sehala Thaoura": "Sehala Thaoura - سحالة ثاورة",
    Sfisef: "Sfissef - الزفيزف",
    "Sidi Ali Benyoub": "Sidi Ali Benyoub - سيدي علي بن يوب",
    "Sidi Ali Boussidi": "Sidi Ali Boussidi - سيدي علي بوسيدي",
    "Sidi Bel Abbes": "Sidi Bel Abbes - سيدي بلعباس",
    "Sidi Brahim": "Sidi Brahim - سيدي ابراهيم",
    "Sidi Chaib": "Sidi Chaib - سيدي شعيب",
    "Sidi Daho des Zairs": "Sidi Dahou Zairs - سيدي دحو الزاير",
    "Sidi Hamadouche": "Sidi Hamadouche - سيدي حمادوش",
    "Sidi Khaled": "Sidi Khaled - سيدي خالد",
    "Sidi Lahcene": "Sidi Lahcene - سيدي لحسن",
    "Sidi Yacoub": "Sidi Yacoub - سيدي يعقوب",
    Tabia: "Tabia - طابية",
    Tafissour: "Tafissour - تافيسور",
    Taoudmout: "Taoudmout - تاودموت",
    Teghalimet: "Teghalimet - تغليمت",
    Telagh: "Telagh - تلاغ",
    Tenira: "Tenira - تنيرة",
    Tessala: "Tessala - تسالة",
    Tilmouni: "Tilmouni - تيلموني",
    Zerouala: "Zerouala - زروالة",
  },
  Tiaret: {
    "Aïn Bouchekif": "Ain Bouchekif - عين بوشقيق",
    "Aïn Deheb": "Ain Deheb - عين الذهب",
    "Aïn Dzarit": "Ain Zarit - عين زاريت",
    "Aïn El Hadid": "Ain El Hadid - عين الحديد",
    "Aïn Kermes": "Ain Kermes - عين كرمس",
    Bougara: "Bougara - بوقرة",
    Chehaima: "Chehaima - شحيمة",
    Dahmouni: "Dahmouni - دحموني",
    "Djebilet Rosfa": "Djebilet Rosfa - جبيلة الرصفاء",
    "Djillali Ben Amar": "Djillali Ben Amar - جيلالي بن عمار",
    Faidja: "Faidja - الفايجة",
    Frenda: "Frenda - فرندة",
    Guertoufa: "Guertoufa - قرطوفة",
    Hamadia: "Hamadia - الحمادية",
    "Ksar Chellala": "Ksar Chellala - قصر الشلالة",
    Madna: "Madna - مادنة",
    Mahdia: "Mahdia - مهدية",
    "Mechraa Safa": "Mechraa Safa - مشرع الصفا",
    Medrissa: "Medrissa - مديرسة",
    Medroussa: "Medroussa - مدروسة",
    Meghila: "Meghila - مغيلة",
    Mellakou: "Mellakou - كلاكو",
    Nadorah: "Nadorah - الناظورة",
    Naima: "Naima - النعيمة",
    "Oued Lilli": "Oued Lilli - وادي ليلي",
    Rahouia: "Rahouia - رحوية",
    Rechaiga: "Rechaiga - الرشايقة",
    Sebaine: "Sebaine - سبعين",
    Sebt: "Sebt - السبت",
    Serghine: "Serghine - سرغين",
    "Si Abdelghani": "Si Abdelghani - سي عبد الغني",
    "Sidi Abderahmane": "Sidi Abderrahmane - سيدي عبد الرحمن",
    "Sidi Ali Mellal": "Sidi Ali Mellal - سيدي علي ملال",
    "Sidi Bakhti": "Sidi Bakhti - سيدي بختي",
    "Sidi Hosni": "Sidi Hosni - سيدي الحسني",
    Sougueur: "Sougueur - السوقر",
    Tagdemt: "Tagdemt - تاقدمت",
    Takhemaret: "Takhemaret - تخمرت",
    Tiaret: "Tiaret - تيارت",
    Tidda: "Tidda - تيدة",
    Tousnina: "Tousnina - توسنينة",
    "Zmalet El Emir Abdelkader":
      "Zmalet El Emir Abdelkade - زاملة الأمير عبد القادر",
  },
  Guelma: {
    "Aïn Ben Beida": "Ain Ben Beida - عين بن بيضاء",
    "Aïn Larbi": "Ain Larbi - عين العربي",
    "Aïn Makhlouf": "Ain Makhlouf - عين مخلوف",
    "Aïn Reggada": "Ain Reggada - عين رقادة",
    "Aïn Sandel": "Ain Sandel - عين صندل",
    Belkheir: "Belkheir - بلخير",
    "Ben Djerrah": "Ben Djarah - بن جراح",
    "Beni Mezline": "Beni Mezline - بني مزلين",
    "Bordj Sabath": "Bordj Sabat - برج صباط",
    "Bouati Mahmoud": "Bouati Mahmoud - بوعاطي محمود",
    Bouchegouf: "Bouchegouf - بوشقوف",
    Bouhachana: "Bou Hachana - بوحشانة",
    Bouhamdane: "Bou Hamdane - بوحمدان",
    "Boumahra Ahmed": "Bouhamra Ahmed - بومهرة أحمد",
    Dahouara: "Dahouara - الداواهرة",
    "Djeballah Khemissi": "Djeballah Khemissi - جبالة الخميسي",
    "El Fedjoudj": "El Fedjoudj - الفجوج",
    "Guellat Bou Sbaa": "Guelaat Bou Sbaa - قلعة بوصبع",
    Guelma: "Guelma - قالمة",
    "Hammam Debagh": "Hamam Debagh - حمام دباغ",
    "Hammam N'Bail": "Hammam N'bail - حمام النبايل",
    Héliopolis: "Heliopolis - هيليوبوليس",
    "Houari Boumédiène": "Ain Hessania - عين الحساينية",
    Khezarra: "Khezara - خزارة",
    "Medjez Amar": "Medjez Amar - مجاز عمار",
    "Medjez Sfa": "Medjez Sfa - مجاز الصفاء",
    Nechmaya: "Nechmaya - نشماية",
    "Oued Cheham": "Oued Cheham - وادي الشحم",
    "Oued Fragha": "Oued Fragha - وادي فراغا",
    "Oued Zenati": "Oued Zenati - وادي الزناتي",
    "Ras El Agba": "Ras El Agba - رأس العقبة",
    Roknia: "Roknia - الركنية",
    "Sellaoua Announa": "Sellaoua Announa - سلاوة عنونة",
    Tamlouka: "Tamlouka - تاملوكة",
  },
  Mostaganem: {
    "Abdelmalek Ramdane": "Benabdelmalek Ramdane - بن عبد المالك رمضان",
    Achaacha: "Achaacha - عشعاشة",
    "Aïn Boudinar": "Ain-boudinar - عين بودينار",
    "Aïn Nouissy": "Ain Nouissy - عين نويسي",
    "Aïn Sidi Cherif": "Ain-sidi Cherif - عين سيدي الشريف",
    "Aïn Tedles": "Ain-tedles - عين تادلس",
    "Blad Touahria": "Touahria - الطواهرية",
    Bouguirat: "Bouguirat - بوقيراط",
    "El Hassaine": "Hassiane - الحسيان",
    Fornaka: "Fornaka - فرناقة",
    Hadjadj: "Hadjadj - حجاج",
    "Hassi Mameche": "Hassi Mameche - حاسي معمش",
    Khadra: "Khadra - خضراء",
    Kheireddine: "Kheir Eddine - خير الدين",
    Mansourah: "Mansourah - منصورة",
    Mazagran: "Mazagran - مزغران",
    Mesra: "Mesra - ماسرة",
    Mostaganem: "Mostaganem - مستغانم",
    Nekmaria: "Nekmaria - نكمارية",
    "Oued El Kheir": "Oued El Kheir - وادي الخير",
    "Ouled Boughalem": "Ouled Boughalem - أولاد بوغالم",
    "Ouled Maallah": "Ouled Maalah - أولاد مع الله",
    Safsaf: "Safsaf - صفصاف",
    Sayada: "Sayada - صيادة",
    "Sidi Ali": "Sidi Ali - سيدي علي",
    "Sidi Belattar": "Sidi Belaattar - سيدي بلعطار",
    "Sidi Lakhdar": "Sidi-lakhdar - سيدي لخضر",
    Sirat: "Sirat - سيرات",
    Souaflia: "Souaflia - السوافلية",
    Sour: "Sour - سور",
    Stidia: "Stidia - ستيدية",
    Tazgait: "Tazgait - تزقايت",
  },
  Skikda: {
    "Aïn Bouziane": "Ain Bouziane - عين بوزيان",
    "Aïn Charchar": "Ain Charchar - عين الشرشار",
    "Aïn Kechra": "Ain Kechera - عين قشرة",
    "Aïn Zouit": "Ain Zouit - عين زويت",
    Azzaba: "Azzaba - عزابة",
    "Bekkouche Lakhdar": "Bekkouche Lakhdar - بكوش الأخضر",
    "Ben Azzouz": "Ben Azzouz - بن عزوز",
    "Beni Bechir": "Beni Bechir - بني بشير",
    "Beni Oulbane": "Beni Oulbane - بني ولبان",
    "Beni Zid": "Beni Zid - بني زيد",
    "Bin El Ouiden": "Bin El Ouiden - بين الويدان",
    Bouchtata: "Bouchetata - بوشطاطة",
    Cheraia: "Cheraia - الشرائع",
    Collo: "Collo - القل",
    "Djendel Saadi Mohamed": "Djendel Saadi Mohamed - جندل سعيدي محمد",
    "El Ghedir": "El Ghedir - الغدير",
    "El Hadaiek": "El Hadaiek - الحدائق",
    "El Harrouch": "El Arrouch - الحروش",
    "El Marsa": "El Marsa - المرسى",
    "Emdjez Edchich": "Emjez Edchich - مجاز الدشيش",
    "Es Sebt": "Es Sebt - السبت",
    Filfila: "Filfila - فلفلة",
    "Hamadi Krouma": "Hamadi Krouma - حمادي كرومة",
    Kanoua: "Kanoua - قنواع",
    Kerkera: "Kerkera - الكركرة",
    "Kheneg Mayoum": "Khenag Mayoum - خنق مايون",
    "Oued Zehour": "Oued Zhour - وادي الزهور",
    "Ouldja Boulballout": "Ouldja Boulbalout - الولجة بولبلوط",
    "Ouled Attia": "Ouled Attia - أولاد عطية",
    "Ouled Hbaba": "Ouled Habbeba - أولاد حبابة",
    "Oum Toub": "Oum Toub - أم الطوب",
    "Ramdane Djamel": "Ramdane Djamel - ومضان جمال",
    "Salah Bouchaour": "Salah Bouchaour - صالح بو الشعور",
    "Sidi Mezghiche": "Sidi Mezghiche - سيدي مزغيش",
    Skikda: "Skikda - سكيكدة",
    Tamalous: "Tamalous - تمالوس",
    Zerdaza: "Zerdezas - زردازة",
    Zitouna: "Zitouna - الزيتونة",
  },
  Batna: {
    "Abdelkader Azil": "Azil Abedelkader - إزيل عبد القادر",
    "Aïn Djasser": "Ain Djasser - عين جاسر",
    "Aïn Touta": "Ain Touta - عين التوتة",
    "Aïn Yagout": "Ain Yagout - عين ياقوت",
    Arris: "Arris - أريس",
    Barika: "Barika - بريكة",
    Batna: "Batna - باتنة",
    "Ben Foudhala El Hakania": "Beni Foudhala El Hakania - بني فوظالة الحكانية",
    Bitam: "Bitam - بيطام",
    Boulhilat: "Boulhilat - بوالحيلات",
    Boumagueur: "Boumagueur - بومقر",
    "Boumia (Batna)": "Boumia - بومية",
    Bouzina: "Bouzina - بوزينة",
    Chemora: "Chemora - شمرة",
    Chir: "Chir - شير",
    Djerma: "Djerma - جرمة",
    Djezar: "Djezzar - الجزار",
    "El Hassi": "El Hassi - الحاسي",
    "El Madher": "El Madher - المعذر",
    Fesdis: "Fesdis - فسديس",
    "Foum Toub": "Foum Toub - فم الطوب",
    Ghassira: "Ghassira - غسيرة",
    Gosbat: "Gosbat - القصبات",
    Guigba: "Guigba - قيقبة",
    Hidoussa: "Hidoussa - حيدوسة",
    Ichmoul: "Ichmoul - أشمول",
    Inoughissen: "Inoughissen - إينوغيسن",
    Kimmel: "Kimmel - كيمل",
    "Ksar Bellezma": "Ksar Bellezma - قصر بلزمة",
    Larbaâ: "Larbaa - لرباع",
    Lazrou: "Lazrou - لازرو",
    Lemsane: "Lemsane - لمسان",
    "M'doukel": "Mdoukal - مدوكال",
    Maafa: "Maafa - معافة",
    Menaa: "Menaa - منعة",
    Merouana: "Merouana - مروانة",
    "N'Gaous": "Ngaous - نقاوس",
    "Oued Chaaba": "Oued Chaaba - وادي الشعبة",
    "Oued El Ma": "Oued El Ma - وادي الماء",
    "Oued Taga": "Oued Taga - وادي الطاقة",
    "Ouled Ammar": "Ouled Ammar - أولاد عمار",
    "Ouled Aouf": "Ouled Aouf - أولاد عوف",
    "Ouled Fadel": "Ouled Fadel - أولاد فاضل",
    "Ouled Sellam": "Ouled Sellem - أولاد سالم",
    "Ouled Si Slimane": "Ouled Si Slimane - أولاد سيدي سليمان",
    "Ouyoun El Assafir": "Ouyoun El Assafir - عيون العصافير",
    Rahbat: "Rahbat - الرحبات",
    "Ras El Aioun": "Ras El Aioun - رأس العيون",
    Sefiane: "Sefiane - سفيان",
    Seggana: "Seggana - سقانة",
    Seriana: "Seriana - سريانة",
    "T'Kout": "Tkout - تكوت",
    Talkhamt: "Talkhamt - تالغمت",
    Taxlent: "Taxlent - تاكسلانة",
    Tazoult: "Tazoult - تازولت",
    "Teniet El Abed": "Teniet El Abed - ثنية العابد",
    Tighanimine: "Tighanimine - تغانمين",
    Tigherghar: "Tigharghar - تغرغار",
    Tilatou: "Tilatou - تيلاطو",
    Timgad: "Timgad - تيمقاد",
    "Zanat El Beida": "Zanet El Beida - زانة البيضاء",
  },
  "M'Sila": {
    "Aïn El Hadjel": "Ain El Hadjel - عين الحجل",
    "Aïn El Melh": "Ain El Melh - عين الملح",
    "Aïn Errich": "Ain Rich - عين الريش",
    "Aïn Fares": "Ain Fares - عين فارس",
    "Aïn Khadra": "Ain Khadra - عين خضراء",
    Belaiba: "Belaiba - بلعايبة",
    "Ben Srour": "Ben Srour - ابن سرور",
    "Beni Ilmane": "Beni Ilmane - بني يلمان",
    Benzouh: "Benzouh - بن زوح",
    Berhoum: "Berhoum - برهوم",
    "Bir Foda": "Bir Foda - بئر الفضة",
    "Bou Saâda": "Bou Saada - بوسعادة",
    "Bouti Sayah": "Bouti Sayeh - بوطي السياح",
    Chellal: "Chellal - شلال",
    Dehahna: "Dehahna - دهاهنة",
    "Djebel Messaad": "Djebel Messaad - جبل مسعد",
    "El Hamel": "El Hamel - الهامل",
    "El Houamed": "El Houamed - الحوامد",
    "Hammam Dhalaa": "Hammam Dalaa - حمام الضلعة",
    "Khettouti Sed El Djir": "Khettouti Sed El Jir - ختوتي سد الجير",
    Khoubana: "Khoubana - خبانة",
    "M'Cif": "Mcif - مصيف",
    "M'Sila": "M'sila - المسيلة",
    "M'Tarfa": "Mtarfa - المطارفة",
    Maadid: "Maadid - المعاضيد",
    Maarif: "Maarif - معاريف",
    Magra: "Magra - مقرة",
    Medjedel: "Medjedel - مجدل",
    "Mohammed Boudiaf": "Mohamed Boudiaf - محمد بوضياف",
    Ouanougha: "Ouanougha - ونوغة",
    "Ouled Addi Guebala": "Ouled Addi Guebala - أولاد عدي قبالة",
    "Ouled Atia": "Menaa Ouled Attia - منعة -أولاد عطية",
    "Ouled Derradj": "Ouled Derradj - أولاد دراج",
    "Ouled Madhi": "Ouled Madhi - أولاد ماضي",
    "Ouled Mansour": "Ouled Mansour - أولاد منصور",
    "Ouled Sidi Brahim": "Ouled Sidi Brahim - أولاد سيدي ابراهيم",
    "Ouled Slimane": "Ouled Slimane - أولاد سليمان",
    Oultem: "Oulteme - ولتام",
    "Sidi Aïssa": "Sidi Aissa - سيدي عيسى",
    "Sidi Ameur": "Sidi Ameur - سيدي عامر",
    "Sidi Hadjeres": "Sidi Hadjeres - سيدي هجرس",
    "Sidi M'Hamed": "Sidi Mhamed - سيدي أحمد",
    Slim: "Slim - سليم",
    Souamaa: "Souamaa - الصوامع",
    Tamsa: "Tamsa - تامسة",
    Tarmount: "Tarmount - تارمونت",
    Zarzour: "Zarzour - زرزور",
  },
  "Tizi Ouzou": {
    "Abi Youcef": "Abi Youcef - أبي يوسف",
    Aghribs: "Aghribs - أغريب",
    "Agouni Gueghrane": "Agouni Gueghrane - أقني قغران",
    "Ain El Hammam": "Ain El Hammam - عين الحمام",
    "Aïn Zaouia": "Ain Zaouia - عين الزاوية",
    "Aït Aggouacha": "Ait Aggouacha - أيت قواشة",
    "Aït Aïssa Mimoun": "Ait Aissa Mimoun - أيت عيسى ميمون",
    "Aït Bouadou": "Ait Bouaddou - أيت بوعدو",
    "Aït Boumahdi": "Ait Boumehdi - أيت بومهدي",
    "Aït Chafâa": "Ait Chafaa - أيت شفعة",
    "Aït Khellili": "Ait Khellili - أيت خليلي",
    "Aït Mahmoud": "Ait-mahmoud - أيت محمود",
    "Aït Oumalou": "Ait Oumalou - أيت أومالو",
    "Aït Toudert": "Ait Toudert - أيت تودرت",
    "Aït Yahia": "Ait-yahia - أيت يحي",
    "Aït Yahia Moussa": "Ait Yahia Moussa - أيت يحيى",
    "Aït Yenni": "Ait Yenni - أيت يني",
    Akbil: "Akbil - اقبيل",
    Akerrou: "Akerrou - أقرو",
    "Assi Youcef": "Assi Youcef - أسي يوسف",
    "Ath Zikki": "Ait Zikki - أيت زيكي",
    Azazga: "Azazga - عزازقة",
    Azeffoun: "Azeffoun - أزفون",
    "Beni Aïssi": "Beni Aissi - بني عيسي",
    "Beni Douala": "Beni-douala - بني دوالة",
    "Beni Zmenzer": "Beni Zmenzer - بني زمنزر",
    Boghni: "Boghni - بوغني",
    Boudjima: "Boudjima - بوجيمة",
    Bounouh: "Bounouh - بونوح",
    Bouzguen: "Bouzeguene - بوزغن",
    "Draâ Ben Khedda": "Draa Ben Khedda - ذراع بن خدة",
    "Draâ El Mizan": "Draa El Mizan - ذراع الميزان",
    Freha: "Freha - فريحة",
    Frikat: "Frikat - فريقات",
    Iboudraren: "Iboudrarene - أبودرارن",
    Idjeur: "Idjeur - إجر",
    Iferhounène: "Iferhounene - ايفرحونن",
    Ifigha: "Ifigha - إيفيغاء",
    Iflissen: "Iflissen - أفليسن",
    Illilten: "Illilten - اليلتين",
    "Illoula Oumalou": "Illoula Oumalou - ايلولة امالو",
    Imsouhel: "Imsouhal - أمسوحال",
    Irdjen: "Irdjen - ارجن",
    "Larbaâ Nath Irathen": "Larba Nath Irathen - الاربعاء نايث ايراثن",
    "M'Kira": "Mkira - مكيرة",
    Mâatkas: "Maatkas - المعاتقة",
    Makouda: "Makouda - ماكودة",
    Mechtras: "Mechtras - مشطراس",
    Mekla: "Mekla - مقلة",
    Mizrana: "Mizrana - مزرانة",
    Ouacif: "Ouacif - واسيف",
    Ouadhia: "Ouadhia - واضية",
    Ouaguenoun: "Ouaguenoune - واقنون",
    "Sidi Namane": "Sidi Naamane - سيدي نعمان",
    Souamaâ: "Souamaa - الصوامع",
    "Souk El Thenine": "Souk El Thenine - سوق الاثنين",
    Tadmaït: "Tadmait - تادمايت",
    Tigzirt: "Tigzirt - تقيزريت",
    Timizart: "Timizart - تيميزارت",
    Tirmitine: "Tirmitine - تيرمتين",
    "Tizi Gheniff": "Tizi Ghenif - تيزي غنيف",
    "Tizi N'Tleta": "Tizi Ntleta - تيزي نثلاثة",
    "Tizi Ouzou": "Tizi ouzou - تيزي وزو",
    "Tizi Rached": "Tizi Rached - تيزي راشد",
    Yakouren: "Yakourene - يعكورن",
    Yatafen: "Yatafene - ياطفان",
    Zekri: "Zekri - زكري",
  },
  "El Tarf": {
    "Aïn El Assel": "Ain El Assel - عين العسل",
    "Aïn Kerma": "Ain Kerma - عين الكرمة",
    Asfour: "Asfour - عصفور",
    "Ben Mehidi": "Ben Mhidi - ابن مهيدي",
    Berrihane: "Berrihane - بريحان",
    Besbes: "Besbes - البسباس",
    Bougous: "Bougous - بوقوس",
    Bouhadjar: "Bouhadjar - بوحجار",
    Bouteldja: "Bouteldja - بوثلجة",
    "Chebaita Mokhtar": "Chebaita Mokhtar - شبايطة مختار",
    Chefia: "Chefia - الشافية",
    Chihani: "Chihani - شهاني",
    Dréan: "Drean - الذرغان",
    Echatt: "Echatt - الشط",
    "El Aioun": "El Aioun - العيون",
    "El Kala": "El Kala - القالة",
    "El Tarf": "El Tarf - الطارف",
    "Hammam Beni Salah": "Hammam Beni Salah - حمام بن صالح",
    "Lac des Oiseaux": "Lac Des Oiseaux - بحيرة الطيور",
    "Oued Zitoun": "Oued Zitoun - وادي الزيتون",
    "Raml Souk": "Raml Souk - رمل السوق",
    Souarekh: "Souarekh - السواريخ",
    Zerizer: "Zerizer - زريزر",
    Zitouna: "Zitouna - الزيتونة",
  },
  "Oum El Bouaghi": {
    "Aïn Babouche": "Ain Babouche - عين بابوش",
    "Aïn Beïda": "Ain Beida - عين البيضاء",
    "Aïn Diss": "Ain Diss - عين الديس",
    "Aïn Fakroun": "Ain Fekroune - عين الفكرون",
    "Aïn Kercha": "Ain Kercha - عين كرشة",
    "Aïn M'lila": "Ain M'lila - عين مليلة",
    "Aïn Zitoun": "Ain Zitoun - عين الزيتون",
    "Behir Chergui": "Behir Chergui - بحير الشرقي",
    Berriche: "Berriche - بريش",
    "Bir Chouhada": "Bir Chouhada - بئر الشهداء",
    Dhalaa: "Dhala - الضلعة",
    "El Amiria": "El Amiria - العامرية",
    "El Belala": "El Belala - البلالة",
    "El Djazia": "El Djazia - الجازية",
    "El Fedjoudj Boughrara Saoudi":
      "El Fedjoudj Boughrara Saoudi - الفجوج بوغرارة سعودي",
    "El Harmilia": "El Harmilia - الحرملية",
    Fkirina: "Fkirina - فكيرينة",
    "Hanchir Toumghani": "Hanchir Toumghani - هنشير تومغاني",
    "Ksar Sbahi": "Ksar Sbahi - قصر الصباحي",
    Meskiana: "Meskiana - مسكيانة",
    "Oued Nini": "Oued Nini - وادي نيني",
    "Ouled Gacem": "Ouled Gacem - أولاد قاسم",
    "Ouled Hamla": "Ouled Hamla - أولاد حملة",
    "Ouled Zouaï": "Ouled Zouai - أولاد زاوي",
    "Oum el Bouaghi": "Oum El Bouaghi - أم البواقي",
    Rahia: "Rahia - الراحية",
    Sigus: "Sigus - سيقوس",
    "Souk Naamane": "Souk Naamane - سوق نعمان",
    Zorg: "Zorg - الزرق",
  },
  Tissemsilt: {
    Ammari: "Ammari - عماري",
    "Beni Chaib": "Beni Chaib - بني شعيب",
    "Beni Lahcene": "Beni Lahcene - بني الحسن",
    "Bordj Bou Naama": "Bordj Bounaama - برج بونعامة",
    "Bordj El Emir Abdelkader":
      "Bordj El Emir Abdelkader - برج الأمير عبد القادر",
    Boucaid: "Bou Caid - بوقايد",
    Khemisti: "Khemisti - خميستي",
    Larbaa: "Larbaa - الأربعاء",
    Lardjem: "Lardjem - الأرجم",
    Layoune: "Layoune - العيون",
    Lazharia: "Lazharia - الأزهرية",
    Maacem: "Maacem - المعاصم",
    Melaab: "Melaab - ملعب",
    "Ouled Bessem": "Ouled Bessem - أولاد بسام",
    "Sidi Abed": "Sidi Abed - سيدي عابد",
    "Sidi Boutouchent": "Sidi Boutouchent - سيدي بوتوشنت",
    "Sidi Lantri": "Sidi Lantri - سيدي العنتري",
    "Sidi Slimane": "Sidi Slimane - سيدي سليمان",
    Tamalaht: "Tamellalet - تاملاحت",
    "Theniet El Had": "Theniet El Had - ثنية الاحد",
    Tissemsilt: "Tissemsilt - تيسمسيلت",
    Youssoufia: "Youssoufia - اليوسفية",
  },
  Ouargla: {
    "Aïn Beida": "Ain Beida - عين البيضاء",
    Benaceur: "Benaceur - بن ناصر",
    "Blidet Amor": "Blidet Amor - بلدية عامر",
    "El Allia": "El Alia - العالية",
    "El Borma": "El Borma - البرمة",
    "El Hadjira": "El-hadjira - الحجيرة",
    "Hassi Ben Abdellah": "Hassi Ben Abdellah - حاسي بن عبد الله",
    "Hassi Messaoud": "Hassi Messaoud - حاسي مسعود",
    "M'Naguer": "M'naguer - المنقر",
    Megarine: "Megarine - المقارين",
    "N'Goussa": "Ngoussa - نقوسة",
    Nezla: "Nezla - النزلة",
    Ouargla: "Ouargla - ورقلة",
    Rouissat: "Rouissat - الرويسات",
    "Sidi Khouiled": "Sidi Khouiled - سيدي خويلد",
    "Sidi Slimane": "Sidi Slimane - سيدي سليمان",
    Taibet: "Taibet - الطيبات",
    Tamacine: "Temacine - تماسين",
    Tebesbest: "Tebesbest - تبسبست",
    Touggourt: "Touggourt - توقرت",
    "Zaouia El Abidia": "Zaouia El Abidia - الزاوية العابدية",
  },
  "El Oued": {
    Bayadha: "Bayadha - البياضة",
    "Beni Guecha": "Ben Guecha - بني قشة",
    Debila: "Debila - الدبيلة",
    Djamaa: "Djamaa - جامعة",
    "Douar El Ma": "Douar El Maa - دوار الماء",
    "El M'Ghair": "El-m'ghair - المغير",
    "El Ogla": "El Ogla - العقلة",
    "El Oued": "El Oued - الوادي",
    Guemar: "Guemar - قمار",
    Hamraia: "Hamraia - الحمراية",
    "Hassani Abdelkrim": "Hassani Abdelkrim - حساني عبد الكريم",
    "Hassi Khalifa": "Hassi Khalifa - حاسي خليفة",
    Kouinine: "Kouinine - كوينين",
    "M'Rara": "M'rara - مرارة",
    Magrane: "Magrane - المقرن",
    "Mih Ouansa": "Mih Ouansa - ميه وانسة",
    Nakhla: "Nakhla - النخلة",
    "Oued El Alenda": "Oued El Alenda - وادي العلندة",
    "Oum Touyour": "Oum Touyour - أم الطيور",
    Ourmas: "Ourmes - ورماس",
    Reguiba: "Reguiba - الرقيبة",
    Robbah: "Robbah - الرباح",
    "Sidi Amrane": "Sidi Amrane - سيدي عمران",
    "Sidi Aoun": "Sidi Aoun - سيدي عون",
    "Sidi Khellil": "Sidi Khelil - سيدي خليل",
    Still: "Still - سطيل",
    Taghzout: "Taghzout - تاغزوت",
    "Taleb Larbi": "Taleb Larbi - طالب العربي",
    Tendla: "Tenedla - تندلة",
    Trifaoui: "Trifaoui - الطريفاوي",
  },
  Tipaza: {
    Aghbal: "Aghbal - أغبال",
    "Ahmar El Aïn": "Ahmer El Ain - أحمر العين",
    "Aïn Tagourait": "Ain Tagourait - عين تاقورايت",
    Attatba: "Attatba - الحطاطبة",
    "Beni Milleuk": "Beni Mileuk - بني ميلك",
    "Bou Ismaïl": "Bou Ismail - بواسماعيل",
    Bouharoun: "Bou Haroun - بوهارون",
    Bourkika: "Bourkika - بورقيقة",
    Chaiba: "Chaiba - الشعيبة",
    Cherchell: "Cherchell - شرشال",
    Damous: "Damous - الداموس",
    Douaouda: "Douaouda - دواودة",
    Fouka: "Fouka - فوكة",
    Gouraya: "Gouraya - قوراية",
    "Hadjeret Ennous": "Hadjret Ennous - حجرة النص",
    Hadjout: "Hadjout - حجوط",
    Khemisti: "Khemisti - خميستي",
    Koléa: "Kolea - القليعة",
    Larhat: "Larhat - الأرهاط",
    Menaceur: "Menaceur - مناصر",
    Merad: "Merad - مراد",
    Messelmoun: "Messelmoun - مسلمون",
    Nador: "Nador - الناظور",
    "Sidi Amar": "Sidi-amar - سيدي عامر",
    "Sidi Ghiles": "Sidi Ghiles - سيدي غيلاس",
    "Sidi Rached": "Sidi Rached - سيدي راشد",
    "Sidi Semiane": "Sidi Semiane - سيدي سميان",
    Tipaza: "Tipaza - تيبازة",
  },
  Adrar: {
    Adrar: "Adrar - أدرار",
    Akabli: "Akabli - اقبلي",
    Aougrout: "Aougrout - أوقروت",
    Aoulef: "Aoulef - أولف",
    "Bordj Badji Mokhtar": "Bordj Badji Mokhtar - برج باجي مختار",
    Bouda: "Bouda - بودة",
    Charouine: "Charouine - شروين",
    Deldoul: "Deldoul - دلدول",
    Fenoughil: "Fenoughil - فنوغيل",
    "In Zghmir": "In Zghmir - انزجمير",
    "Ksar Kaddour": "Ksar Kaddour - قصر قدور",
    Metarfa: "Metarfa - المطارفة",
    "Ouled Ahmed Tammi": "Ouled Ahmed Timmi - أولاد أحمد تيمي",
    "Ouled Aïssa": "Ouled Aissa - أولاد عيسى",
    "Ouled Saïd": "Ouled Said - أولاد سعيد",
    Reggane: "Reggane - رقان",
    Sali: "Sali - سالي",
    Sebaa: "Sebaa - سبع",
    Talmine: "Talmine - طلمين",
    Tamantit: "Tamantit - تمنطيط",
    Tamekten: "Timekten - تيمقطن",
    Tamest: "Tamest - تامست",
    Timiaouine: "Timiaouine - تيمياوين",
    Timimoun: "Timimoun - تيميمون",
    Tinerkouk: "Tinerkouk - تينركوك",
    Tit: "Tit - تيط",
    Tsabit: "Tsabit - تسابيت",
    "Zaouiet Kounta": "Zaouiet Kounta - زاوية كنتة",
  },
  "Illizi (wilaya restreinte)": {
    "Bordj El Haouas": "Bordj El Haouasse - برج الحواس",
    "Bordj Omar Driss": "Bordj Omar Driss - برج عمر إدريس",
    Debdeb: "Debdeb - دبداب",
    Djanet: "Djanet - جانت",
    Illizi: "Illizi - إيليزي",
    "In Amenas": "In Amenas - إن أميناس",
  },
  Biskra: {
    "Aïn Naga": "Ain Naga - عين الناقة",
    "Aïn Zaatout": "Ain Zaatout - عين زعطوط",
    Besbes: "Besbes - بسباس",
    Biskra: "Biskra - بسكرة",
    "Bordj Ben Azzouz": "Bordj Ben Azzouz - برج بن عزوز",
    Bouchagroune: "Bouchagroun - بوشقرون",
    Branis: "Branis - البرانس",
    Chetma: "Chetma - شتمة",
    Djemorah: "Djemorah - جمورة",
    Doucen: "Doucen - الدوسن",
    "Ech Chaïba": "Chaiba - الشعيبة",
    "El Feidh": "El Feidh - الفيض",
    "El Ghrous": "El Ghrous - الغروس",
    "El Hadjeb": "El Hadjab - الحاجب",
    "El Haouch": "El Haouch - الحوش",
    "El Kantara": "El Kantara - القنطرة",
    "El Mizaraa": "Meziraa - المزيرعة",
    "El Outaya": "El Outaya - الوطاية",
    Foughala: "Foughala - فوغالة",
    "Khenguet Sidi Nadji": "Khenguet Sidi Nadji - خنقة سيدي ناجي",
    Lichana: "Lichana - لشانة",
    Lioua: "Lioua - لواء",
    "M'Chouneche": "M'chouneche - مشونش",
    "M'Lili": "Mlili - مليلي",
    Mekhadma: "Mekhadma - مخادمة",
    "Ouled Djellal": "Ouled Djellal - أولاد جلال",
    Oumache: "Oumache - أوماش",
    Ourlal: "Ourlal - أورلال",
    "Ras El Miaad": "Ras El Miad - رأس الميعاد",
    "Sidi Khaled": "Sidi Khaled - سيدي خالد",
    "Sidi Okba": "Sidi Okba - سيدي عقبة",
    Tolga: "Tolga - طولقة",
    "Zeribet El Oued": "Zeribet El Oued - زريبة الوادي",
  },
  "Aïn Defla": {
    "Aïn Benian": "Ain Benian - عين البنيان",
    "Aïn Bouyahia": "Ain Bouyahia - عين بويحيى",
    "Aïn Defla": "Ain Defla - عين الدفلة",
    "Aïn Lechiekh": "Ain Lechiakh - عين الاشياخ",
    "Aïn Soltane": "Ain-soltane - عين السلطان",
    "Aïn Torki": "Ain Torki - عين الترك",
    Arib: "Arib - عريب",
    Bathia: "Bathia - بطحية",
    Belaas: "Belaas - بالعاص",
    "Ben Allal": "Ben Allal - إبن علال",
    "Bir Ould Khelifa": "Bir Ould Khelifa - بئر ولد خليفة",
    Birbouche: "Barbouche - بربوش",
    "Bordj Emir Khaled": "Bordj-emir-khaled - برج الأمير خالد",
    Boumedfaa: "Boumedfaa - بومدفع",
    Bourached: "Bourached - بوراشد",
    Djelida: "Djelida - جليدة",
    "Djemaa Ouled Cheikh": "Djemaa Ouled Cheikh - جمعة أولاد الشيخ",
    Djendel: "Djendel - جندل",
    "El Abadia": "El Abadia - العبادية",
    "El Amra": "El Amra - العامرة",
    "El Attaf": "El Attaf - العطاف",
    "El Hassania": "Hassania - الحسانية",
    "El Maine": "El Maine - الماين",
    "Hammam Righa": "Hammam Righa - حمام ريغة",
    Hoceinia: "Hoceinia - الحسينية",
    "Khemis Miliana": "Khemis Miliana - خميس مليانة",
    Mekhatria: "Mekhatria - المخاطرية",
    Miliana: "Miliana - مليانة",
    "Oued Chorfa": "Oued Chorfa - وادي الشرفاء",
    "Oued Djemaa": "Oued Djemaa - وادي جمعة",
    Rouina: "Rouina - روينة",
    "Sidi Lakhdar": "Sidi Lakhdar - سيدي الأخضر",
    "Tacheta Zougagha": "Tacheta Zegagha - تاشتة زقاغة",
    "Tarik Ibn Ziad": "Tarik-ibn-ziad - طارق بن زياد",
    Tiberkanine: "Tiberkanine - تبركانين",
    Zeddine: "Zeddine - زدين",
  },
  Saïda: {
    "Aïn El Hadjar": "Ain El Hadjar - عين الحجر",
    "Aïn Sekhouna": "Ain Sekhouna - عين السخونة",
    "Aïn Soltane": "Ain Soltane - عين السلطان",
    "Doui Thabet": "Doui Thabet - دوي ثابت",
    "El Hassasna": "El Hassasna - الحساسنة",
    Hounet: "Hounet - حنات",
    Maamora: "Maamora - المعمورة",
    "Moulay Larbi": "Moulay Larbi - مولاي العربي",
    "Ouled Brahim": "Ouled Brahim - أولاد إبراهيم",
    "Ouled Khaled": "Ouled Khaled - أولاد خالد",
    Saïda: "Saida - سعيدة",
    "Sidi Ahmed": "Sidi Ahmed - سيدي احمد",
    "Sidi Amar": "Sidi Amar - سيدي عمار",
    "Sidi Boubekeur": "Sidi Boubekeur - سيدي بوبكر",
    Tircine: "Tircine - تيرسين",
    Youb: "Youb - يوب",
  },
  "Bordj Bou Arreridj": {
    "Aïn Taghrout": "Ain Taghrout - عين تاغروت",
    "Aïn Tesra": "Ain Tesra - عين تسرة",
    Belimour: "Belimour - بليمور",
    "Ben Daoud": "Ben Daoud - بن داود",
    "Bir Kasdali": "Bir Kasdali - بئر قصد علي",
    "Bordj Bou Arreridj": "Bordj Bou Arreridj - برج بوعريرج",
    "Bordj Ghédir": "Bordj Ghdir - برج غدير",
    "Bordj Zemoura": "Bordj Zemora - برج زمورة",
    Colla: "Colla - القلة",
    Djaafra: "Djaafra - الجعافرة",
    "El Ach": "El Ach - العش",
    "El Achir": "El Achir - الياشير",
    "El Anseur": "El Anseur - العنصر",
    "El Hamadia": "El Hamadia - الحمادية",
    "El M'hir": "El Mhir - المهير",
    "El Main": "El Main - الماين",
    Ghilassa: "Ghilassa - غيلاسة",
    Haraza: "Haraza - حرازة",
    Hasnaoua: "Hasnaoua - حسناوة",
    Khelil: "Khelil - خليل",
    Ksour: "Ksour - القصور",
    Mansoura: "Mansoura - المنصورة",
    Medjana: "Medjana - مجانة",
    "Ouled Brahem": "Ouled Brahem - أولاد أبراهيم",
    "Ouled Dahmane": "Ouled Dahmane - أولاد دحمان",
    "Ouled Sidi Brahim": "Ouled Sidi Brahim - أولاد سيدي ابراهيم",
    Rabta: "Rabta - الرابطة",
    "Ras El Oued": "Ras El Oued - رأس الوادي",
    "Sidi Embarek": "Sidi Embarek - سيدي مبارك",
    Taglait: "Taglait - تقلعيت",
    Tassameurt: "Tesmart - تسمرت",
    Tefreg: "Tafreg - تفرق",
    "Teniet En Nasr": "Teniet En Nasr - ثنية النصر",
    Tixter: "Tixter - تيكستير",
  },
  Ghardaïa: {
    Berriane: "Berriane - بريان",
    Bounoura: "Bounoura - بونورة",
    "Dhayet Bendhahoua": "Dhayet Bendhahoua - ضاية بن ضحوة",
    "El Atteuf": "El Atteuf - العطف",
    "El Guerrara": "El Guerrara - القرارة",
    "El Menia": "El Meniaa - المنيعة",
    Ghardaïa: "Ghardaia - غرداية",
    "Hassi Fehal": "Hassi Fehal - حاسي الفحل",
    "Hassi Gara": "Hassi Gara - حاسي القارة",
    Mansoura: "Mansoura - المنصورة",
    Metlili: "Metlili - منليلي",
    Sebseb: "Sebseb - سبسب",
    Zelfana: "Zelfana - رلفانة",
  },
  Alger: {
    "Aïn Benian": "Ain Benian - عين بنيان",
    "Aïn Taya": "Ain Taya - عين طاية",
    "Alger Centre": "Alger Centre - الجزائر",
    "Bab El Oued": "Bab El Oued - باب الوادي",
    "Bab Ezzouar": "Bab Ezzouar - باب الزوار",
    "Baba Hassen": "Baba Hesen - بابا حسن",
    Bachdjerrah: "Bachedjerah - باش جراح",
    Baraki: "Baraki - براقي",
    Belouizdad: "Mohamed Belouzdad - محمد بلوزداد",
    "Ben Aknoun": "Ben Aknoun - ابن عكنون",
    "Beni Messous": "Beni Messous - بني مسوس",
    "Bir Mourad Raïs": "Bir Mourad Rais - بئر مراد رايس",
    Birkhadem: "Birkhadem - بئر خادم",
    Birtouta: "Bir Touta - بئر توتة",
    Bologhine: "Bologhine Ibnou Ziri - بولوغين بن زيري",
    "Bordj El Bahri": "Bordj El Bahri - برج البحري",
    "Bordj El Kiffan": "Bordj El Kiffan - برج الكيفان",
    Bourouba: "Bourouba - بوروبة",
    Bouzareah: "Bouzareah - بوزريعة",
    Casbah: "Casbah - القصبة",
    Cheraga: "Cheraga - الشراقة",
    "Dar El Beïda": "Dar El Beida - الدار البيضاء",
    "Dely Ibrahim": "Dely Ibrahim - دالي ابراهيم",
    "Djasr Kasentina": "Djasr Kasentina - جسر قسنطينة",
    Douera: "Douira - الدويرة",
    Draria: "Draria - الدرارية",
    "El Achour": "El Achour - العاشور",
    "El Biar": "El Biar - الابيار",
    "El Hammamet": "El Hammamet - الحمامات",
    "El Harrach": "El Harrach - الحراش",
    "El Madania": "El Madania - المدنية",
    "El Magharia": "El Magharia - المغارية",
    "El Marsa": "El Merssa - المرسى",
    "El Mouradia": "El Mouradia - المرادية",
    "H'raoua": "Herraoua - هراوة",
    "Hussein Dey": "Hussein Dey - حسين داي",
    Hydra: "Hydra - حيدرة",
    Khraicia: "Kheraisia - الخرايسية",
    Kouba: "Kouba - القبة",
    "Les Eucalyptus": "Les Eucalyptus - الكاليتوس",
    Mahelma: "Maalma - المعالمة",
    Mohammadia: "Mohammadia - المحمدية",
    "Oued Koriche": "Oued Koriche - وادي قريش",
    "Oued Smar": "Oued Smar - وادي السمار",
    "Ouled Chebel": "Ouled Chebel - اولاد شبل",
    "Ouled Fayet": "Ouled Fayet - اولاد فايت",
    Rahmania: "Rahmania - الرحمانية",
    "Raïs Hamidou": "Rais Hamidou - الرايس حميدو",
    Reghaïa: "Reghaia - رغاية",
    Rouïba: "Rouiba - الرويبة",
    Saoula: "Sehaoula - السحاولة",
    "Sidi M'Hamed": "Sidi Mhamed - سيدي امحمد",
    "Sidi Moussa": "Sidi Moussa - سيدي موسى",
    Souidania: "Souidania - سويدانية",
    Staoueli: "Setaouali - سطاوالي",
    "Tessala El Merdja": "Tessala El Merdja - تسالة المرجة",
    Zeralda: "Zeralda - زرالدة",
  },
  Tamanrasset: {
    Abalessa: "Abalessa - آبلسّا",
    "Foggaret Ezzaouia": "Foggaret Azzaouia - فقارة الزوا",
    Idles: "Idles - أدلس",
    "In Amguel": "Ain Amguel - عين امقل",
    "In Ghar": "In Ghar - إنغر",
    "In Guezzam": "In Guezzam - عين قزام",
    "In Salah": "In Salah - عين صالح",
    Tamanrasset: "Tamanrasset - تامنغست",
    Tazrouk: "Tazrouk - تازروك",
    "Tin Zaouatine": "Tin Zouatine - تينزواتين",
  },
  Sétif: {
    "Aïn Abessa": "Ain Abessa - عين عباسة",
    "Aïn Arnat": "Ain Arnat - عين أرنات",
    "Aïn Azel": "Ain Azel - عين أزال",
    "Aïn El Kebira": "Ain El Kebira - العين الكبيرة",
    "Aïn Lahdjar": "Ain Lahdjar - عين الحجر",
    "Aïn Legradj": "Ain Legradj - عين لقراج",
    "Aïn Oulmene": "Ain Oulmane - عين ولمان",
    "Aïn Roua": "Ain Roua - عين الروى",
    "Aïn Sebt": "Ain Sebt - عين السبت",
    "Aït Naoual Mezada": "Ait Naoual Mezada - أيت نوال مزادة",
    "Aït Tizi": "Ait Tizi - ايت تيزي",
    "Aït Wertilan": "Aït Wertilan - ايت ورتيلان",
    Amoucha: "Amoucha - عموشة",
    Babor: "Babor - بابور",
    "Bazer Sakhra": "Bazer Sakra - بازر الصخرة",
    "Beidha Bordj": "Beidha Bordj - بيضاء برج",
    Belaa: "Bellaa - بلعة",
    "Beni Aziz": "Beni-aziz - بني عزيز",
    "Beni Chebana": "Beni Chebana - بني شبانة",
    "Beni Fouda": "Beni Fouda - بني فودة",
    "Beni Hocine": "Beni Oussine - بني وسين",
    "Beni Mouhli": "Beni Mouhli - بني موحلي",
    "Bir El Arch": "Bir El Arch - بئر العرش",
    "Bir Haddada": "Bir Haddada - بئر حدادة",
    Bouandas: "Bouandas - بوعنداس",
    Bougaa: "Bougaa - بوقاعة",
    Bousselam: "Bousselam - بوسلام",
    Boutaleb: "Boutaleb - بوطالب",
    Dehamcha: "Dehamcha - الدهامشة",
    Djemila: "Djemila - جميلة",
    "Draa Kebila": "Draa Kebila - ذراع القبيلة",
    "El Eulma": "El Eulma - العلمة",
    "El Ouldja": "El Ouldja - الولجة",
    "El Ouricia": "El Ouricia - الوريسية",
    Guellal: "Guellal - قلال بوطالب",
    "Guelta Zerka": "Guelta Zerka - القتلة الزرقاء",
    Guenzet: "Guenzet - قنزات",
    Guidjel: "Guidjel - قجال",
    Hamma: "Hamma - الحامة",
    "Hammam Guergour": "Hammam Guergour - حمام قرقور",
    "Hammam Soukhna": "Hamam Soukhna - حمام السخنة",
    Harbil: "Harbil - حربيل",
    "Ksar El Abtal": "Ksar El Abtal - قصر الابطال",
    Maaouia: "Maaouia - معاوية",
    Maoklane: "Maouaklane - ماوكلان",
    Mezloug: "Mezloug - مزلوق",
    "Oued El Barad": "Oued El Barad - وادي البارد",
    "Ouled Addouane": "Ouled Addouane - أولاد عدوان",
    "Ouled Sabor": "Ouled Sabor - أولاد صابر",
    "Ouled Si Ahmed": "Ouled Si Ahmed - أولاد سي أحمد",
    "Ouled Tebben": "Ouled Tebben - أولاد تبان",
    Rasfa: "Rosfa - الرصفة",
    "Salah Bey": "Salah Bey - صالح باي",
    "Serdj El Ghoul": "Serdj El Ghoul - سرج الغول",
    Sétif: "Setif - سطيف",
    Tachouda: "Tachouda - تاشودة",
    Talaifacene: "Tala Ifacene - تالة إيفاسن",
    Taya: "Taya - الطاية",
    Tella: "Tella - النلعة",
    "Tizi N'Bechar": "Tizi Nbechar - تيزي نبشار",
  },
  Khenchela: {
    "Aïn Touila": "Ain Touila - عين الطويلة",
    Babar: "Babar - ببار",
    Baghai: "Baghai - بغاي",
    Bouhmama: "Bouhmama - بوحمامة",
    Chechar: "Cherchar - ششار",
    Chelia: "Chelia - شلية",
    Djellal: "Djellal - جلال",
    "El Hamma": "El Hamma - الحامة",
    "El Mahmal": "El Mahmal - المحمل",
    "El Oueldja": "El Oueldja - الولجة",
    Ensigha: "Ensigha - انسيغة",
    Kais: "Kais - قايس",
    Khenchela: "Khenchela - خنشلة",
    Khirane: "Khirane - خيران",
    "M'Sara": "Msara - مصارة",
    "M'Toussa": "Mtoussa - متوسة",
    "Ouled Rechache": "Ouled Rechache - أولاد رشاش",
    Remila: "Remila - الرميلة",
    Tamza: "Tamza - تلمزة",
    Taouzient: "Taouzianat - تاوزيانت",
    Yabous: "Yabous - يابوس",
  },
  Annaba: {
    "Aïn Berda": "Ain Berda - العين الباردة",
    Annaba: "Annaba - عنابة",
    Berrahal: "Berrahel - برحال",
    Chetaïbi: "Chetaibi - شطايبي",
    Cheurfa: "Cheurfa - الشرفاء",
    "El Bouni": "El Bouni - البوني",
    "El Hadjar": "El Hadjar - الحجار",
    Eulma: "Eulma - العلمة",
    "Oued El Aneb": "Oued El Aneb - وادي العنب",
    Seraïdi: "Seraidi - سرايدي",
    "Sidi Amar": "Sidi Amar - سيد عامر",
    Treat: "Treat - التريعات",
  },
  Constantine: {
    "Aïn Abid": "Ain Abid - عين عبيد",
    "Aïn Smara": "Ain Smara - عين السمارة",
    "Beni Hamiden": "Beni Hamidene - بني حميدان",
    Constantine: "Constantine - قسنطينة",
    "Didouche Mourad": "Didouche Mourad - ديدوش مراد",
    "El Khroub": "El Khroub - الخروب",
    "Hamma Bouziane": "Hamma Bouziane - حامة بوزيان",
    "Ibn Badis": "Ben Badis - أبن باديس الهرية",
    "Ibn Ziad": "Ibn Ziad - ابن زياد",
    "Messaoud Boudjriou": "Messaoud Boujeriou - بوجريو مسعود",
    "Ouled Rahmoune": "Ouled Rahmouni - أولاد رحمون",
    "Zighoud Youcef": "Zighoud Youcef - زيغود يوسف",
  },
  "Tindouf (wilaya restreinte)": {
    "Oum el Assel": "Oum el Assel - أم العسل",
    Tindouf: "Tindouf - تندوف",
  },
  Médéa: {
    "Aïn Boucif": "Ain Boucif - عين بوسيف",
    "Aïn Ouksir": "Ain Ouksir - عين القصيرة",
    Aissaouia: "Aissaouia - العيساوية",
    Aziz: "Aziz - عزيز",
    Baata: "Baata - بعطة",
    Benchicao: "Ben Chicao - بن شكاو",
    "Beni Slimane": "Beni Slimane - بني سليمان",
    Berrouaghia: "Berrouaghia - البرواقية",
    "Bir Ben Laabed": "Bir Ben Laabed - بئر بن عابد",
    Boghar: "Boghar - بوغار",
    "Bou Aiche": "Bouaiche - بوعيش",
    Bouaichoune: "Bouaichoune - بوعيشون",
    Bouchrahil: "Bouchrahil - بوشراحيل",
    Boughezoul: "Boughzoul - بوغزول",
    Bouskene: "Bouskene - بوسكن",
    Chahbounia: "Chabounia - الشهبونية",
    "Chellalet El Adhaoura": "Chelalet El Adhaoura - شلالة العذاورة",
    Cheniguel: "Cheniguel - شنيقل",
    Derrag: "Derrag - دراق",
    "Deux Bassins": "Deux Bassins - الحوضان",
    Djouab: "Djouab - جواب",
    "Draa Essamar": "Draa Essamar - ذراع السمار",
    "El Azizia": "El Azizia - العزيزية",
    "El Guelb El Kebir": "El Guelbelkebir - القلب الكبير",
    "El Hamdania": "El Hamdania - الحمدانية",
    "El Omaria": "El Omaria - العمرية",
    "El Ouinet": "El Ouinet - العوينات",
    Hannacha: "Hannacha - حناشة",
    "Kef Lakhdar": "Kef Lakhdar - الكاف الاخضر",
    "Khams Djouamaa": "Khams Djouamaa - خمس جوامع",
    "Ksar Boukhari": "Ksar El Boukhari - قصر البخاري",
    Médéa: "Medea - المدية",
    Meftaha: "Meftaha - مفتاح",
    Meghraoua: "Maghraoua - مغراوة",
    Mezerana: "Mezerana - مزغنة",
    Mihoub: "Mihoub - ميهوب",
    Moudjbar: "Medjebar - مجبر",
    Ouamri: "Ouamri - عوامري",
    "Oued Harbil": "Oued Harbil - وادي حربيل",
    "Ouled Antar": "Ouled Antar - أولاد عنتر",
    "Ouled Bouachra": "Ouled Bouachra - أولاد بوعشرة",
    "Ouled Brahim": "Ouled Brahim - أولاد إبراهيم",
    "Ouled Deide": "Ouled Deid - أولاد دايد",
    "Ouled Hellal": "Ouled Hellal - أولاد هلال",
    "Ouled Maaref": "Ouled Maaref - أولاد معروف",
    "Oum El Djalil": "Oum El Djellil - أم الجليل",
    Ouzera: "Ouzera - وزرة",
    Rebaia: "Rebaia - الربعية",
    Saneg: "Saneg - السائق",
    Sedraia: "Sedraya - سدراية",
    Seghouane: "Seghouane - سغوان",
    "Si Mahdjoub": "Si Mahdjoub - سي المحجوب",
    "Sidi Damed": "Sidi Demed - سيدي دامد",
    "Sidi Errabia": "Sidi Rabie - سيدي الربيع",
    "Sidi Naamanez": "Sidi Naamane - سيدي نعمان",
    "Sidi Zahar": "Sidi Zahar - سيدي زهار",
    "Sidi Ziane": "Sidi Ziane - سيدي زيان",
    Souagui: "Souagui - السواقي",
    Tablat: "Tablat - تابلاط",
    Tafraout: "Tafraout - تفراوت",
    Tamesguida: "Tamesguida - تمسقيدة",
    "Tizi Mahdi": "Tizi Mahdi - تيزي مهدي",
    "Tlatet Eddouar": "Tletat Ed Douair - ثلاث دوائر",
    Zoubiria: "Zoubiria - الزبيرية",
    Demiat: "Damiat - دميات",
  },
  "El Bayadh": {
    "Aïn El Orak": "Ain El Orak - عين العراك",
    Arbaouat: "Arbaouat - عرباوة",
    Boualem: "Boualem - بوعلام",
    Bougtoub: "Bougtoub - بوقطب",
    Boussemghoun: "Boussemghoun - بوسمغون",
    Brezina: "Brezina - بريزينة",
    Cheguig: "Cheguig - الشقيق",
    Chellala: "Chellala - شلالة",
    "El Abiodh Sidi Cheikh": "El Biodh Sidi Cheikh - الأبيض سيدي الشيخ",
    "El Bayadh": "El Bayadh - البيض",
    "El Bnoud": "El Bnoud - البنود",
    "El Kheiter": "El Kheither - الخيثر",
    "El Mehara": "El Mehara - المهارة",
    Ghassoul: "Ghassoul - غسول",
    "Kef El Ahmar": "Kef El Ahmar - الكاف الأحمر",
    Kraakda: "Krakda - كراكدة",
    Rogassa: "Rogassa - رقاصة",
    "Sidi Ameur": "Sidi Ameur - سيدي عامر",
    "Sidi Slimane": "Sidi Slimane - سيدي سليمان",
    "Sidi Tifour": "Sidi Tifour - سيدي تيفور",
    Stitten: "Stitten - ستيتن",
    Tousmouline: "Tousmouline - توسمولين",
  },
  Oran: {
    "Aïn El Bia": "Ain Biya - عين البية",
    "Aïn El Kerma": "Ain Kerma - عين الكرمة",
    "Aïn El Turk": "Ain Turk - عين الترك",
    Arzew: "Arzew - أرزيو",
    "Ben Freha": "Ben Freha - بن فريحة",
    Bethioua: "Bethioua - بطيوة",
    "Bir El Djir": "Bir El Djir - بئر الجير",
    "Bou Sfer": "Bousfer - بوصفر",
    Boufatis: "Boufatis - بوفتيس",
    Boutlelis: "Boutlelis - بوتليليس",
    "El Ançor": "El Ancar - العنصر",
    "El Braya": "El Braya - البراية",
    "El Kerma": "El Kerma - الكرمة",
    "Es Senia": "Es Senia - السانية",
    Gdyel: "Gdyel - قديل",
    "Hassi Ben Okba": "Hassi Ben Okba - حاسي بن عقبة",
    "Hassi Bounif": "Hassi Bounif - حاسي بونيف",
    "Hassi Mefsoukh": "Hassi Mefsoukh - حاسي مفسوخ",
    "Marsat El Hadjadj": "Marsat El Hadjadj - مرسى الحجاج",
    "Mers El Kébir": "Mers El Kebir - المرسى الكبير",
    Misserghin: "Messerghin - مسرغين",
    Oran: "Oran - وهران",
    "Oued Tlelat": "Oued Tlelat - وادي تليلات",
    "Sidi Benyebka": "Sidi Ben Yebka - سيدي بن يبقى",
    "Sidi Chami": "Sidi Chami - سيدي الشحمي",
    Tafraoui: "Tafraoui - طفراوي",
  },
  "Souk Ahras": {
    "Aïn Soltane": "Ain Soltane - عين السلطان",
    "Aïn Zana": "Ain Zana - عين الزانة",
    "Bir Bou Haouch": "Bir Bouhouche - بئر بوحوش",
    Drea: "Drea - الدريعة",
    Hanancha: "Hanencha - الجنانشة",
    Heddada: "Haddada - الحدادة",
    Khedara: "Khedara - لخضارة",
    Khemissa: "Khemissa - خميسة",
    "M'daourouch": "Mdaourouche - مداوروش",
    Mechroha: "Machroha - مشروحة",
    Merahna: "Merahna - المراهنة",
    "Oued Keberit": "Oued Kebrit - وادي الكبريت",
    Ouillen: "Quillen - ويلان",
    "Ouled Driss": "Ouled Driss - أولاد إدريس",
    "Ouled Moumene": "Ouled Moumen - أولاد مومن",
    "Oum El Adhaim": "Oum El Adhaim - أم العظايم",
    Ragouba: "Ragouba - الرقوبة",
    "Safel El Ouiden": "Safel El Ouiden - سافل الويدان",
    Sedrata: "Sedrata - سدراتة",
    "Sidi Fredj": "Sidi Fredj - سيدي فرج",
    "Souk Ahras": "Souk Ahras - سوق أهراس",
    Taoura: "Taoura - تاورة",
    Terraguelt: "Terraguelt - ترقالت",
    Tiffech: "Tiffech - تيفاش",
    Zaarouria: "Zaarouria - الزعرورية",
    Zouabi: "Zouabi - الزوابي",
  },
  Naâma: {
    "Aïn Ben Khelil": "Ain Ben Khelil - عين بن خليل",
    "Aïn Sefra": "Ain Safra - عين الصفراء",
    Assela: "Assela - عسلة",
    "Djeniene Bourezg": "Djeniane Bourzeg - جنين بورزق",
    "El Biod": "El Biod - البيوض",
    Kasdir: "Kasdir - قصدير",
    "Makman Ben Amer": "Makman Ben Amer - مكمن بن عمرو",
    Mecheria: "Mecheria - مشرية",
    Moghrar: "Moghrar - مغرار",
    Naâma: "Naama - النعامة",
    Sfissifa: "Sfissifa - سفيسيفة",
    Tiout: "Tiout - تيوت",
  },
  Boumerdès: {
    Afir: "Afir - أفير",
    Ammal: "Ammal - عمال",
    Baghlia: "Baghlia - بغلية",
    "Ben Choud": "Ben Choud - بني شود",
    "Beni Amrane": "Beni Amrane - بني عمران",
    "Bordj Menaiel": "Bordj Menaiel - برج منايل",
    Boudouaou: "Boudouaou - بودواو",
    "Boudouaou El Bahri": "Boudouaou El Bahri - بودواو البحري",
    Boumerdes: "Boumerdes - بومرداس",
    "Bouzegza Keddara": "Bouzegza Keddara - بوزقرة قدارة",
    "Chabet el Ameur": "Chabet El Ameur - شعبة العامر",
    Corso: "Corso - قورصو",
    Dellys: "Dellys - دلس",
    Djinet: "Djinet - جينات",
    "El Kharrouba": "El Kharrouba - الخروبة",
    Hammedi: "Hammedi - حمادي",
    Issers: "Isser - يسر",
    "Khemis El Khechna": "Khemis El Khechna - خميس الخشنة",
    Larbatache: "Larbatache - الاربعطاش",
    Leghata: "Leghata - القاطة",
    Naciria: "Naciria - الناصرية",
    "Ouled Aissa": "Ouled Aissa - أولاد عيسى",
    "Ouled Hedadj": "Ouled Hedadj - أولاد هداج",
    "Ouled Moussa": "Ouled Moussa - أولاد موسى",
    "Si Mustapha": "Si Mustapha - سي مصطفى",
    "Sidi Daoud": "Sidi Daoud - سيدي داود",
    "Souk El Had": "Souk El Haad - سوق الأحد",
    Taourga: "Taourga - تورقة",
    Thenia: "Thenia - الثنية",
    Tidjelabine: "Tidjelabine - تجلبين",
    Timezrit: "Timezrit - تمزريت",
    Zemmouri: "Zemmouri - زموري",
  },
  Mascara: {
    "Aïn Fares": "Ain Fares - عين فارس",
    "Aïn Fekan": "Ain Fekan - عين فكان",
    "Aïn Ferah": "Ain Ferah - عين فراح",
    "Aïn Fras": "Ain Frass - عين الفرس",
    Alaïmia: "Alaimia - العلايمية",
    Aouf: "Aouf - عوف",
    Beniane: "Benian - بنيان",
    "Bou Hanifia": "Bouhanifia - بوحنيفية",
    "Bou Henni": "Bou Henni - بوهني",
    Chorfa: "Chorfa - الشرفاء",
    "El Bordj": "El Bordj - البرج",
    "El Gaada": "El Gaada - القعدة",
    "El Ghomri": "El Ghomri - الغمري",
    "El Guettana": "El Gueitena - القطنة",
    "El Keurt": "El Keurt - القرط",
    "El Menaouer": "El Menaouer - المنور",
    Ferraguig: "Ferraguig - فراقيق",
    Froha: "Froha - فروحة",
    Gharrous: "Gharrous - غروس",
    Ghriss: "Ghriss - غريس",
    Guerdjoum: "Guerdjoum - قرجوم",
    Hachem: "El Hachem - الحشم",
    Hacine: "Hacine - حسين",
    Khalouia: "Khalouia - خلوية",
    Makdha: "Makhda - ماقضة",
    Mamounia: "El Mamounia - المأمونية",
    Maoussa: "Maoussa - ماوسة",
    Mascara: "Mascara - معسكر",
    Matemore: "Matemore - المطمور",
    "Mocta Douz": "Mocta Douz - مقطع الدوز",
    Mohammadia: "Mohammadia - المحمدية",
    Nesmoth: "Nesmot - نسمط",
    Oggaz: "Oggaz - عكاز",
    "Oued El Abtal": "Oued El Abtal - وادي الأبطال",
    "Oued Taria": "Oued Taria - وادي تاغية",
    "Ras El Aïn Amirouche": "Ras El Ain Amirouche - رأس عين عميروش",
    Sedjerara: "Sedjerara - سجرارة",
    Sehailia: "Sehailia - السهايلية",
    "Sidi Abdeldjebar": "Sidi Abdeldjebar - سيدي عبد الجبار",
    "Sidi Abdelmoumen": "Sidi Abdelmoumene - سيدي عبد المومن",
    "Sidi Boussaid": "Sidi Boussaid - سيدي بوسعيد",
    "Sidi Kada": "Sidi Kada - سيدي قادة",
    Sig: "Sig - سيق",
    Tighennif: "Tighennif - تيغنيف",
    Tizi: "Tizi - تيزي",
    Zahana: "Zahana - زهانة",
    Zelmata: "Zelamta - زلامطة",
  },
  "Aïn Témouchent": {
    Aghlal: "Aghlal - أغلال",
    "Aïn El Arbaa": "Ain El Arbaa - عين الأربعاء",
    "Aïn Kihal": "Ain Kihal - عين الكحيل",
    "Aïn Témouchent": "Ain Temouchent - عين تيموشنت",
    "Aïn Tolba": "Ain Tolba - عين الطلبة",
    Aoubellil: "Aoubellil - عقب الليل",
    "Beni Saf": "Beni Saf - بني صاف",
    Bouzedjar: "Bouzedjar - بوزجار",
    "Chaabat El Leham": "Chaabat El Ham - شعبة اللحم",
    Chentouf: "Chentouf - شنتوف",
    "El Amria": "El Amria - العامرية",
    "El Emir Abdelkader": "Emir Abdelkader - الأمير عبد القادر",
    "El Malah": "El Malah - المالح",
    "El Messaid": "El Messaid - المساعيد",
    "Hammam Bouhadjar": "Hammam Bouhadjar - حملم بوحجر",
    Hassasna: "Hassasna - الحساسنة",
    "Hassi El Ghella": "Hassi El Ghella - حاسي الغلة",
    "Oued Berkeche": "Oued Berkeche - وادي برقش",
    "Oued Sabah": "Oued Sebbah - وادي الصباح",
    "Ouled Boudjemaa": "Ouled Boudjemaa - أولاد بوجمعة",
    "Ouled Kihal": "Ouled Kihal - أولاد كحيل",
    "Oulhaça El Gheraba": "Oulhaca El Gheraba - ولهاصة الغرابة",
    "Sidi Ben Adda": "Sidi Ben Adda - سيدي بن عدة",
    "Sidi Boumedienne": "Sidi Boumediene - سيدي بومدين",
    "Sidi Ouriache": "Sidi Ouriache - سيدي أورياش",
    "Sidi Safi": "Sidi Safi - سيدي الصافي",
    Tamzoura: "Tamzoura - تامزورة",
    Terga: "Terga - تارقة",
  },
  Mila: {
    "Ahmed Rachedi": "Ahmed Rachedi - أحمد راشدي",
    "Aïn Beida Harriche": "Ain Beida Harriche - عين البيضاء حريش",
    "Aïn Mellouk": "Ain Mellouk - عين ملوك",
    "Aïn Tine": "Ain Tine - عين التين",
    "Amira Arrès": "Amira Arres - عميرة أراس",
    "Benyahia Abderrahmane": "Benyahia Abderrahmane - أبن يحيى عبد الرحمن",
    Bouhatem: "Bouhatem - بوحاتم",
    "Chelghoum Laid": "Chelghoum Laid - شلغوم العيد",
    Chigara: "Chigara - السيقارة",
    "Derradji Bousselah": "Derradji Bousselah - دراجي بوصالح",
    "El Mechira": "El Mechira - المشيرة",
    "Elayadi Barbes": "Elayadi Barbes - العيادي برباس",
    Ferdjioua: "Ferdjioua - فرجيوة",
    "Grarem Gouga": "Grarem Gouga - قرارم قوقة",
    Hamala: "Hamala - حمالة",
    Mila: "Mila - ميلة",
    "Minar Zarza": "Minar Zarza - مينار زرزة",
    "Oued Athmania": "Oued Athmenia - وادي العثمانية",
    "Oued Endja": "Oued Endja - وادي النجاء",
    "Oued Seguen": "Oued Seguen - وادي سقان",
    "Ouled Khalouf": "Ouled Khalouf - أولاد خلوف",
    Rouached: "Rouached - الرواشد",
    "Sidi Khelifa": "Sidi Khelifa - سيدي خليفة",
    "Sidi Merouane": "Sidi Merouane - سيدي مروان",
    Tadjenanet: "Tadjenanet - تاجنانت",
    "Tassadane Haddada": "Tassadane Haddada - تسادان حدادة",
    Teleghma: "Teleghma - تلاغمة",
    "Terrai Bainen": "Terrai Bainem - ترعي بايبان",
    "Tessala Lemtaï": "Tessala - تسالة المطاعي",
    Tiberguent: "Tiberguent - تيبرقنت",
    "Yahia Beni Guecha": "Yahia Beniguecha - يحيى بني قشة",
    Zeghaia: "Zeghaia - الزغاية",
  },
  Relizane: {
    "Aïn Rahma": "Ain Rahma - عين الرحمة",
    "Aïn Tarek": "Ain Tarek - عين طارق",
    "Ammi Moussa": "Ammi Moussa - عمي موسى",
    "Belassel Bouzegza": "Belaassel Bouzagza - بلعسل بوزقزة",
    Bendaoud: "Bendaoud - بن داود",
    "Beni Dergoun": "Beni Dergoun - بني درقون",
    "Beni Zentis": "Beni Zentis - بني زنطيس",
    "Dar Ben Abdellah": "Dar Ben Abdelah - دار بن عبد الله",
    Djidioua: "Djidiouia - جديوية",
    "El Guettar": "El-guettar - القطار",
    "El Hamadna": "El Hmadna - الحمادنة",
    "El Hassi": "El Hassi - الحاسي",
    "El Matmar": "El-matmar - المطمر",
    "El Ouldja": "El Ouldja - الولجة",
    "Had Echkalla": "Had Echkalla - حد الشكالة",
    Hamri: "Hamri - الحمري",
    Kalaa: "Kalaa - القلعة",
    Lahlef: "Lahlef - الأحلاف",
    Mazouna: "Mazouna - مازونة",
    Mediouna: "Mediouna - مديونة",
    Mendes: "Mendes - منداس",
    "Merdja Sidi Abed": "Merdja Sidi Abed - مرجة سيدي عابد",
    Ouarizane: "Ouarizane - ورزان",
    "Oued El Djemaa": "Oued El Djemaa - وادي الجمعة",
    "Oued Essalem": "Oued Essalem - وادي السلام",
    "Oued Rhiou": "Oued Rhiou - وادي رهيو",
    "Ouled Aiche": "Ouled Aiche - أولاد عيش",
    "Ouled Sidi Mihoub": "Ouled Sidi Mihoub - أولاد سيدي ميهوب",
    Ramka: "Ramka - رمقة",
    Relizane: "Relizane - غليزان",
    "Sidi Khettab": "Sidi Khettab - سيدي خطاب",
    "Sidi Lazreg": "Sidi Lazreg - سيدي لزرق",
    "Sidi M'Hamed Ben Ali": "Sidi Mhamed Benali - سيدي أحمد بن علي",
    "Sidi M'Hamed Benaouda": "Sidi Mhamed Benaouda - سيدي امحمد بن عودة",
    "Sidi Saada": "Sidi Saada - سيدي سعادة",
    "Souk El Had": "Souk El Had - سوق الأحد",
    Yellel: "Yellel - يلل",
    Zemmora: "Zemmoura - زمورة",
  },
};
