const data = {
  Laghouat: [
    {
      value: "Aflou",
      label: "Aflou - أفلو",
    },
    {
      value: "Aïn Madhi",
      label: "Ain Madhi - عين ماضي",
    },
    {
      value: "Aïn Sidi Ali",
      label: "Ain Sidi Ali - عين سهيه علي",
    },
    {
      value: "Beidha",
      label: "Beidha - بيضاء",
    },
    {
      value: "Bennasser Benchohra",
      label: "Benacer Benchohra - بن ناصر بن شهرة",
    },
    {
      value: "Brida",
      label: "Brida - بريدة",
    },
    {
      value: "El Assafia",
      label: "El Assafia - العسفية",
    },
    {
      value: "El Ghicha",
      label: "El Ghicha - الغيشة",
    },
    {
      value: "El Houaita",
      label: "El Haouaita - الحويطة",
    },
    {
      value: "Gueltat Sidi Saad",
      label: "Gueltat Sidi Saad - قتلة سيدي سعيد",
    },
    {
      value: "Hadj Mechri",
      label: "Hadj Mechri - الحاج مشري",
    },
    {
      value: "Hassi Delaa",
      label: "Hassi Delaa - حاسي الدلاعة",
    },
    {
      value: "Hassi R'Mel",
      label: "Hassi R'mel - حاسي الرمل",
    },
    {
      value: "Kheneg",
      label: "Kheneg - الخنق",
    },
    {
      value: "Ksar El Hirane",
      label: "Ksar El Hirane - قصر الحيران",
    },
    {
      value: "Laghouat",
      label: "Laghouat - الأغواط",
    },
    {
      value: "Oued M'Zi",
      label: "Oued M'zi - وادي مزي",
    },
    {
      value: "Oued Morra",
      label: "Oued Morra - وادي مرة",
    },
    {
      value: "Sebgag",
      label: "Sebgag - سبقاق",
    },
    {
      value: "Sidi Bouzid",
      label: "Sidi Bouzid - سيدي بوزيد",
    },
    {
      value: "Sidi Makhlouf",
      label: "Sidi Makhlouf - سيدي مخلوف",
    },
    {
      value: "Tadjemout",
      label: "Tadjemout - تاجموت",
    },
    {
      value: "Tadjrouna",
      label: "Tadjrouna - تاجرونة",
    },
    {
      value: "Taouiala",
      label: "Taouiala - تاويالة",
    },
  ],
  Chlef: [
    { value: "Abou El Hassan", label: "Abou El Hassan - أبو الحسين" },
    { value: "Aïn Merane", label: "Ain Merane - عين مران" },
    { value: "Bénairia", label: "Benairia - بنايرية" },
    { value: "Beni Bouateb", label: "Beni Bouattab - بني بوعتاب" },
    { value: "Beni Haoua", label: "Beni Haoua - بني حواء" },
    { value: "Beni Rached", label: "Beni Rached - بني راشد" },
    { value: "Boukadir", label: "Boukadir - بوقادير" },
    { value: "Bouzeghaia", label: "Bouzeghaia - بوزغاية" },
    { value: "Breira", label: "Breira - بريرة" },
    { value: "Chettia", label: "Chettia - الشطية" },
    { value: "Chlef", label: "Chlef - الشلف" },
    { value: "Dahra", label: "Dahra - الظهر" },
    { value: "El Hadjadj", label: "El Hadjadj - الحجاج" },
    { value: "El Karimia", label: "El Karimia - الكريمية" },
    { value: "El Marsa", label: "El Marsa - المرسى" },
    { value: "Harchoun", label: "Harchoun - حرشون" },
    { value: "Harenfa", label: "Herenfa - الهرنفة" },
    { value: "Labiod Medjadja", label: "Labiod Medjadja - الأبيض مجاجة" },
    { value: "Moussadek", label: "Moussadek - مصدق" },
    { value: "Oued Fodda", label: "Oued Fodda - وادي الفضة" },
    { value: "Oued Goussine", label: "Oued Goussine - وادي قوسين" },
    { value: "Oued Sly", label: "Oued Sly - وادي سلي" },
    { value: "Ouled Abbes", label: "Ouled Abbes - أولاد عباس" },
    {
      value: "Ouled Ben Abdelkader",
      label: "Ouled Ben Abdelkader - أولاد بن عبد القادر",
    },
    { value: "Ouled Fares", label: "Ouled Fares - أولاد فارس" },
    { value: "Oum Drou", label: "Oum Drou - أم الدروع" },
    { value: "Sendjas", label: "Sendjas - السنجاس" },
    {
      value: "Sidi Abderrahmane",
      label: "Sidi Abderrahmane - سيدي عبد الرحمن",
    },
    { value: "Sidi Akkacha", label: "Sidi Akkacha - سيدي عكاشة" },
    { value: "Sobha", label: "Sobha - صبحة" },
    { value: "Tadjena", label: "Tadjena - تاجنة" },
    { value: "Talassa", label: "Talassa - تلعصة" },
    { value: "Taougrite", label: "Taougrite - تاقريت" },
    { value: "Ténès", label: "Tenes - تنس" },
    { value: "Zeboudja", label: "Zeboudja - الزبوجة" },
  ],
  Béjaïa: [
    { value: "Adekar", label: "Adekar - أدكار" },
    { value: "Ait Djellil", label: "Beni Dejllil - بني جليل" },
    { value: "Aït Ksila", label: "Beni Ksila - بني كسيلة" },
    { value: "Aït Maouche", label: "Beni maouche - بني معوش" },
    { value: "Aït Mellikeche", label: "Beni-mallikeche - بني مليكش" },
    { value: "Aït R'zine", label: "Ait R'zine - أيت رزين" },
    { value: "Aït Smail", label: "Ait-smail - أيت إسماعيل" },
    { value: "Akbou", label: "Akbou - أقبو" },
    { value: "Akfadou", label: "Akfadou - أكفادو" },
    { value: "Amalou", label: "Amalou - أمالو" },
    { value: "Amizour", label: "Amizour - أميزور" },
    { value: "Aokas", label: "Aokas - أوقاس" },
    { value: "Barbacha", label: "Barbacha - برباشة" },
    { value: "Béjaïa", label: "Bejaia - بجاية" },
    { value: "Boudjellil", label: "Boudjellil - بو جليل" },
    { value: "Bouhamza", label: "Bouhamza - بوحمزة" },
    { value: "Boukhelifa", label: "Boukhelifa - بوخليفة" },
    { value: "Chellata", label: "Chellata - شلاطة" },
    { value: "Chemini", label: "Chemini - شميني" },
    { value: "Darguina", label: "Darghina - درقينة" },
    { value: "Draâ El Kaïd", label: "Dra El Caid - ذراع القايد" },
    { value: "El Kseur", label: "El Kseur - القصر" },
    { value: "Fenaïa Ilmaten", label: "Fenaia Il Maten - فلاين الماثن" },
    { value: "Ferraoun", label: "Feraoun - فرعون" },
    { value: "Ighil Ali", label: "Ighil-ali - إغيل علي" },
    { value: "Ighram", label: "Ighram - إغرم" },
    { value: "Kendira", label: "Kendira - كنديرة" },
    { value: "Kherrata", label: "Kherrata - خراطة" },
    { value: "Leflaye", label: "Leflaye - لفلاي" },
    { value: "M'cisna", label: "M'cisna - مسيسنة" },
    { value: "Melbou", label: "Melbou - مالبو" },
    { value: "Oued Ghir", label: "Oued Ghir - وادي غير" },
    { value: "Ouzellaguen", label: "Ouzellaguene - أوزلاقن" },
    { value: "Seddouk", label: "Seddouk - صدوق" },
    { value: "Semaoun", label: "Smaoun - سمعون" },
    { value: "Sidi Aïch", label: "Sidi-aich - سيدي عيش" },
    { value: "Sidi Ayad", label: "Sidi Ayad - سيدي عياد" },
    { value: "Souk El Ténine", label: "Souk El Tenine - سوق لإثنين" },
    { value: "Souk Oufella", label: "Souk Oufella - السوق أوفلا" },
    { value: "Tala Hamza", label: "Tala Hamza - تالة حمزة" },
    { value: "Tamokra", label: "Tamokra - تامقرة" },
    { value: "Tamridjet", label: "Tamridjet - تامريجت" },
    { value: "Taourirt Ighil", label: "Taourit Ighil - تاوريرت إغيل" },
    { value: "Taskriout", label: "Taskriout - تاسكريوت" },
    { value: "Tazmalt", label: "Tazmalt - تزمالت" },
    { value: "Tibane", label: "Tibane - طيبان" },
    { value: "Tichy", label: "Tichy - تيشي" },
    { value: "Tifra", label: "Tifra - تيفرة" },
    { value: "Timezrit", label: "Timezrit - تيمزريت" },
    { value: "Tinabdher", label: "Tinebdar - تينبدار" },
    { value: "Tizi N'Berber", label: "Tizi-n'berber - تيزي نبربر" },
    { value: "Toudja", label: "Toudja - توجة" },
  ],
  Bouira: [
    { value: "Aghbalou", label: "Aghbalou - أغبالو" },
    { value: "Ahl El Ksar", label: "Ahl El Ksar - أهل القصر" },
    { value: "Aïn Bessem", label: "Ain-bessem - عين بسام" },
    { value: "Aïn El Hadjar", label: "Ain El Hadjar - عين الحجر" },
    { value: "Aïn El Turc", label: "Ain Turk - عين الترك" },
    { value: "Aïn Laloui", label: "Ain Laloui - عين العلوي" },
    { value: "Aït Laziz", label: "Ait Laaziz - أيت لعزيز" },
    { value: "Aomar", label: "Aomar - أعمر" },
    { value: "Ath Mansour", label: "Ath Mansour Taourirt - تاوريرت" },
    { value: "Bechloul", label: "Bechloul - بشلول" },
    { value: "Bir Ghbalou", label: "Bir Ghbalou - بئر غبالو" },
    { value: "Bordj Okhriss", label: "Bordj Okhriss - برج أوخريص" },
    { value: "Bouderbala", label: "Bouderbala - بودربالة" },
    { value: "Bouira", label: "Bouira - البويرة" },
    { value: "Boukram", label: "Boukram - بوكرم" },
    { value: "Chorfa", label: "Chorfa - الشرفاء" },
    { value: "Dechmia", label: "Dechmia - الدشمية" },
    { value: "Dirrah", label: "Dirah - ديرة" },
    { value: "Djebahia", label: "Djebahia - جباحية" },
    { value: "El Adjiba", label: "El Adjiba - العجيبة" },
    { value: "El Asnam", label: "El Asnam - الأسنام" },
    { value: "El Hachimia", label: "El Hachimia - الهاشمية" },
    { value: "El Hakimia", label: "El-hakimia - الحاكمية" },
    { value: "El Khabouzia", label: "El Khabouzia - الخبوزية" },
    { value: "El Mokrani", label: "El-mokrani - المقراني" },
    { value: "Guerrouma", label: "Guerrouma - قرومة" },
    { value: "Hadjera Zerga", label: "Hadjera Zerga - الحجرة الزرقاء" },
    { value: "Haizer", label: "Haizer - الحيزر" },
    { value: "Hanif", label: "Hanif - حنيف" },
    { value: "Kadiria", label: "Kadiria - القادرية" },
    { value: "Lakhdaria", label: "Lakhdaria - الأخضرية" },
    { value: "M'Chedallah", label: "Mchedallah - مشد الله" },
    { value: "Maala", label: "Maala - معلة" },
    { value: "Maamora", label: "Maamora - المعمورة" },
    { value: "Mezdour", label: "Mezdour - مزدور" },
    { value: "Oued El Berdi", label: "Oued El Berdi - وادي البردي" },
    { value: "Ouled Rached", label: "Ouled Rached - أولاد راشد" },
    { value: "Raouraoua", label: "Raouraoua - روراوة" },
    { value: "Ridane", label: "Ridane - ريدان" },
    { value: "Saharidj", label: "Saharidj - الصهايج" },
    { value: "Souk El Khemis", label: "Souk El Khemis - سوق الخميس" },
    { value: "Sour El Ghouzlane", label: "Sour El Ghozlane - سور الغزلان" },
    { value: "Taghzout", label: "Taghzout - تاغزوت" },
    { value: "Taguedit", label: "Taguedite - تاقديت" },
    { value: "Zbarbar", label: "Zbarbar - زبربر" },
  ],
  Tlemcen: [
    { value: "Aïn Fetah", label: "Ain Fettah - عين فتاح" },
    { value: "Aïn Fezza", label: "Ain Fezza - عين فزة" },
    { value: "Aïn Ghoraba", label: "Ain Ghoraba - عين الغرابة" },
    { value: "Aïn Kebira", label: "Ain Kebira - العين الكبيرة" },
    { value: "Aïn Nehala", label: "Ain Nehala - عين نحالة" },
    { value: "Aïn Tallout", label: "Ain Tallout - عين تالوت" },
    { value: "Aïn Youcef", label: "Ain Youcef - عين يوسف" },
    { value: "Amieur", label: "Amieur - عمير" },
    { value: "Azails", label: "Azails - العزايل" },
    { value: "Bab El Assa", label: "Bab El Assa - باب العسة" },
    { value: "Beni Bahdel", label: "Beni Bahdel - بني بهدل" },
    { value: "Beni Boussaid", label: "Beni Boussaid - بني بوسعيد" },
    { value: "Beni Khellad", label: "Beni Khaled - بني راشد" },
    { value: "Beni Mester", label: "Beni Mester - بني مستر" },
    { value: "Beni Ouarsous", label: "Beni Ouarsous - بني وارسوس" },
    { value: "Beni Semiel", label: "Beni Smiel - بني صميل" },
    { value: "Beni Snous", label: "Beni Snous - بني سنوس" },
    { value: "Bensekrane", label: "Bensekrane - إبن سكران" },
    { value: "Bouhlou", label: "Bouhlou - بوحلو" },
    { value: "Chetouane", label: "Chetouane - شتوان" },
    { value: "Dar Yaghmouracene", label: "Dar Yaghmouracene - دار يغمراسن" },
    { value: "Djebala", label: "Djebala - جبالة" },
    { value: "El Aricha", label: "El Aricha - العريشة" },
    { value: "El Bouihi", label: "Bouihi - البويهي" },
    { value: "El Fehoul", label: "El Fehoul - الفحول" },
    { value: "El Gor", label: "El Gor - القور" },
    { value: "Fellaoucene", label: "Fellaoucene - فلاوسن" },
    { value: "Ghazaouet", label: "Ghazaouet - الغزوات" },
    { value: "Hammam Boughrara", label: "Hammam Boughrara - حمام بوغرارة" },
    { value: "Hennaya", label: "Hennaya - الحناية" },
    { value: "Honaïne", label: "Honaine - حنين" },
    { value: "Maghnia", label: "Maghnia - مغنية" },
    { value: "Mansourah", label: "Mansourah - منصورة" },
    { value: "Marsa Ben M'Hidi", label: "Marsa Ben M'hidi - مرسى بن مهيدي" },
    { value: "MSirda Fouaga", label: "Msirda Fouaga - مسيردة الفواقة" },
    { value: "Nedroma", label: "Nedroma - ندرومة" },
    { value: "Oued Lakhdar", label: "oued lakhdar - واد لخضر" },
    { value: "Ouled Mimoun", label: "Ouled Mimoun - أولاد ميمون" },
    { value: "Ouled Riyah", label: "Ouled Riyah - أولاد رياح" },
    { value: "Remchi", label: "Remchi - الرمشي" },
    { value: "Sabra", label: "Sabra - صبرة" },
    { value: "Sebaa Chioukh", label: "Sebbaa Chioukh - السبعة شيوخ" },
    { value: "Sebdou", label: "Sebdou - سبدو" },
    { value: "Sidi Abdelli", label: "Sidi Abdelli - سيدي عبد اللي" },
    { value: "Sidi Djillali", label: "Sidi Djilali - سيدي الجيلالي" },
    { value: "Sidi Medjahed", label: "Sidi Medjahed - سيدي مجاهد" },
    { value: "Souahlia", label: "Souahlia - السواحلية" },
    { value: "Souani", label: "Souani - السواني" },
    { value: "Souk Tlata", label: "Souk Tleta - سوق الثلاثاء" },
    { value: "Terny Beni Hdiel", label: "Terny Beni Hediel - تيرني بني هديل" },
    { value: "Tienet", label: "Tianet - تيانت" },
    { value: "Tlemcen", label: "Tlemcen - تلمسان" },
    { value: "Zenata", label: "Zenata - زناتة" },
  ],
  Djelfa: [
    { value: "Aïn Chouhada", label: "Ain Chouhada - عين الشهداء" },
    { value: "Aïn El Ibel", label: "Ain El Ibel - عين الإبل" },
    { value: "Aïn Feka", label: "Ain Fekka - عين فكة" },
    { value: "Aïn Maabed", label: "Ain Maabed - عين معبد" },
    { value: "Aïn Oussara", label: "Ain Oussera - عين وسارة" },
    { value: "Amourah", label: "Amourah - عمورة" },
    { value: "Benhar", label: "Benhar - بنهار" },
    { value: "Beni Yagoub", label: "Benyagoub - بني يعقوب" },
    { value: "Birine", label: "Birine - بيرين" },
    { value: "Bouira Lahdab", label: "Bouira Lahdab - بويرة الأحدب" },
    { value: "Charef", label: "Charef - الشارف" },
    { value: "Dar Chioukh", label: "Dar Chioukh - دار الشيوخ" },
    { value: "Deldoul", label: "Deldoul - دلدول" },
    { value: "Djelfa", label: "Djelfa - الجلفة" },
    { value: "Douis", label: "Douis - دويس" },
    { value: "El Guedid", label: "El Guedid - القديد" },
    { value: "El Idrissia", label: "El Idrissia - الادريسية" },
    { value: "El Khemis", label: "El Khemis - الخميس" },
    { value: "Faidh El Botma", label: "Faidh El Botma - فيض البطمة" },
    { value: "Guernini", label: "Guernini - قرنيني" },
    { value: "Guettara", label: "Guettara - القطارة" },
    { value: "Had Sahary", label: "Had Sahary - حد الصحاري" },
    { value: "Hassi Bahbah", label: "Hassi Bahbah - حاسي بحبح" },
    { value: "Hassi El Euch", label: "Hassi El Euch - حاسي العش" },
    { value: "Hassi Fedoul", label: "Hassi Fedoul - حاسي فدول" },
    { value: "M'Liliha", label: "Mliliha - مليليحة" },
    { value: "Messaad", label: "Messaad - مسعد" },
    { value: "Moudjebara", label: "Moudjebara - مجبرة" },
    { value: "Oum Laadham", label: "Oum Laadham - أم العظام" },
    { value: "Sed Rahal", label: "Sed Rahal - سد الرحال" },
    { value: "Selmana", label: "Selmana - سلمانة" },
    { value: "Sidi Baizid", label: "Sidi Baizid - سيدي بايزيد" },
    { value: "Sidi Ladjel", label: "Sidi Ladjel - سيدي لعجل" },
    { value: "Tadmit", label: "Tadmit - تاعظميت" },
    { value: "Zaafrane", label: "Zaafrane - زعفران" },
    { value: "Zaccar", label: "Zaccar - زكار" },
  ],

  Tébessa: [
    { value: "Aïn Zerga", label: "Ain Zerga - عين الزرقاء" },
    { value: "Bedjene", label: "Bedjene - بجن" },
    { value: "Bekkaria", label: "Bekkaria - بكارية" },
    { value: "Bir Dheb", label: "Bir Dheheb - بئر الذهب" },
    { value: "Bir el Ater", label: "Bir El Ater - بئر العاتر" },
    { value: "Bir Mokkadem", label: "Bir Mokkadem - بئر المقدم" },
    { value: "Boukhadra", label: "Boukhadra - بوخضرة" },
    { value: "Boulhaf Dir", label: "Boulhaf Dyr - بولحاف الدين" },
    { value: "Cheria", label: "Cheria - الشريعة" },
    { value: "El Aouinet", label: "El Aouinet - العوينات" },
    { value: "El Houidjbet", label: "El Houidjbet - الحويجبات" },
    { value: "El Kouif", label: "El Kouif - الكويف" },
    { value: "El Ma Labiodh", label: "El Malabiod - الماء الابيض" },
    { value: "El Meridj", label: "El Meridj - المريج" },
    { value: "El Mezeraa", label: "El Mezeraa - المزرعة" },
    { value: "El Ogla", label: "El Ogla - العقلة" },
    { value: "Ferkane", label: "Ferkane - فركان" },
    { value: "Guorriguer", label: "Guorriguer - قوريقر" },
    { value: "Hammamet", label: "Hammamet - الحمامات" },
    { value: "Morsott", label: "Morssot - مرسط" },
    { value: "Negrine", label: "Negrine - نقرين" },
    { value: "Ogla Melha", label: "El Ogla El Malha - العقلة المالحة" },
    { value: "Ouenza", label: "Ouenza - الونزة" },
    { value: "Oum Ali", label: "Oum Ali - أم علي" },
    { value: "Safsaf El Ouesra", label: "Saf Saf El Ouesra - صفصاف الوسرة" },
    { value: "Stah Guentis", label: "Stah Guentis - سطح قنطيس" },
    { value: "Tébessa", label: "Tebessa - تبسة" },
    { value: "Tlidjene", label: "Telidjen - ثليجان" },
  ],
  Béchar: [
    { value: "Abadla", label: "Abadla - العبادل" },
    { value: "Béchar", label: "Bechar - بشار" },
    { value: "Béni Abbès", label: "Beni Abbes - بني عباس" },
    { value: "Beni Ikhlef", label: "Beni Ikhlef - بني يخلف" },
    { value: "Beni Ounif", label: "Beni Ounif - بني ونيف" },
    { value: "Boukais", label: "Boukais - بوقايس" },
    { value: "El Ouata", label: "El Ouata - الوطاء" },
    { value: "Erg Ferradj", label: "Erg Ferradj - عرق فراج" },
    { value: "Igli", label: "Igli - إيقلي" },
    { value: "Kenadsa", label: "Kenadsa - قنادسة" },
    { value: "Kerzaz", label: "Kerzaz - كرزاز" },
    { value: "Ksabi", label: "Ksabi - قصابي" },
    { value: "Lahmar", label: "Lahmar - الأحمر" },
    {
      value: "Mechraa Houari Boumedienne",
      label: "Mechraa H.boumediene - مشروع هواري بومدين",
    },
    { value: "Meridja", label: "Meridja - مريجة" },
    { value: "Mougheul", label: "Mogheul - موغل" },
    { value: "Ouled Khoudir", label: "Ouled Khoudir - أولاد خضير" },
    { value: "Tabelbala", label: "Tabelbala - تبلبالة" },
    { value: "Taghit", label: "Taghit - تاغيت" },
    { value: "Tamtert", label: "Tamtert - تامترت" },
    { value: "Timoudi", label: "Timoudi - تيمودي" },
  ],
  Blida: [
    { value: "Aïn Romana", label: "Ain Romana - عين الرمانة" },
    { value: "Beni Mered", label: "Beni Mered - بني مراد" },
    { value: "Beni Tamou", label: "Beni-tamou - بني تامو" },
    { value: "Benkhelil", label: "Benkhelil - بن خليل" },
    { value: "Blida", label: "Blida - البليدة" },
    { value: "Bouarfa", label: "Bouarfa - بوعرفة" },
    { value: "Boufarik", label: "Boufarik - بوفاريك" },
    { value: "Bougara", label: "Bougara - بوقرة" },
    { value: "Bouinan", label: "Bouinan - بوعينان" },
    { value: "Chebli", label: "Chebli - الشبلي" },
    { value: "Chiffa", label: "Chiffa - الشفة" },
    { value: "Chréa", label: "Chrea - الشريعة" },
    { value: "Djebabra", label: "Djebabra - جبابرة" },
    { value: "El Affroun", label: "El-affroun - العفرون" },
    { value: "Guerouaou", label: "Guerrouaou - قرواو" },
    { value: "Hammam Melouane", label: "Hammam Melouane - حمام ملوان" },
    { value: "Larbaa", label: "Larbaa - الأربعاء" },
    { value: "Meftah", label: "Meftah - مفتاح" },
    { value: "Mouzaia", label: "Mouzaia - موزاية" },
    { value: "Oued Alleug", label: "Oued El Alleug - وادي العلايق" },
    { value: "Oued Djer", label: "Oued Djer - وادي جر" },
    { value: "Ouled Slama", label: "Ouled Slama - اولاد سلامة" },
    { value: "Ouled Yaïch", label: "Ouled Yaich - أولاد يعيش" },
    { value: "Souhane", label: "Souhane - سوحان" },
    { value: "Soumaa", label: "Souma - الصومعة" },
  ],
  Jijel: [
    { value: "Bordj Tahar", label: "Bordj Tahar - برج الطاهر" },
    {
      value: "Boucif Ouled Askeur",
      label: "Boussif Ouled Askeur - بوسيف أولاد عسكري",
    },
    {
      value: "Boudriaa Ben Yadjis",
      label: "Boudria Beniyadjis - بوذريعة بني ياجيس",
    },
    { value: "Bouraoui Belhadef", label: "Bouraoui Belhadef - بوراوي بلهادف" },
    { value: "Chahna", label: "Chahna - الشحنة" },
    { value: "Chekfa", label: "Chekfa - الشقفة" },
    {
      value: "Djemaa Beni Habibi",
      label: "Djemaa Beni Habibi - الجمعة بني حبيبي",
    },
    { value: "Djimla", label: "Djimla - جميلة" },
    { value: "El Ancer", label: "El Ancer - العنصر" },
    { value: "El Aouana", label: "El Aouana - العوانة" },
    { value: "El Kennar Nouchfi", label: "El Kennar Nouchfi - القنار نوشفي" },
    { value: "El Milia", label: "El Milia - الميلية" },
    { value: "Emir Abdelkader", label: "Emir Abdelkader - الامير عبد القادر" },
    { value: "Eraguene", label: "Erraguene - أراقن" },
    { value: "Ghebala", label: "Ghebala - غبالة" },
    { value: "Jijel", label: "Jijel - جيجل" },
    { value: "Kaous", label: "Kaous - قاوس" },
    { value: "Kheïri Oued Adjoul", label: "Khiri Oued Adjoul - خير وادي عجول" },
    { value: "Ouadjana", label: "Oudjana - وجانة" },
    { value: "Ouled Rabah", label: "Ouled Rabah - أولاد رابح" },
    {
      value: "Ouled Yahia Khedrouche",
      label: "Ouled Yahia Khadrouch - أولاد يحيى خدروش",
    },
    { value: "Selma Benziada", label: "Selma Benziada - سلمى بن زيادة" },
    { value: "Settara", label: "Settara - السطارة" },
    { value: "Sidi Abdelaziz", label: "Sidi Abdelaziz - سيدي عبد العزيز" },
    { value: "Sidi Maarouf", label: "Sidi Marouf - سيدي معروف" },
    { value: "Taher", label: "Taher - الطاهير" },
    { value: "Texenna", label: "Texena - تاكسنة" },
    { value: "Ziama Mansouriah", label: "Ziama Mansouria - زيامة منصورية" },
  ],
  "Sidi Bel Abbès": [
    { value: "Aïn Adden", label: "Ain Adden - عين عدان" },
    { value: "Aïn El Berd", label: "Ain El Berd - عين البرد" },
    { value: "Aïn Kada", label: "Ain Kada - عين قادة" },
    { value: "Aïn Thrid", label: "Ain Thrid - عين الثريد" },
    { value: "Aïn Tindamine", label: "Ain Tindamine - عين تندمين" },
    { value: "Amarnas", label: "Amarnas - امرناس" },
    {
      value: "Badredine El Mokrani",
      label: "Badredine El Mokrani - بدر الدين المقراني",
    },
    { value: "Belarbi", label: "Belarbi - بلعربي" },
    { value: "Ben Badis", label: "Ben Badis - بن باديس" },
    { value: "Benachiba Chelia", label: "Benachiba Chelia - بن عشيبة شلية" },
    { value: "Bir El Hammam", label: "Bir El Hammam - بئر الحمام" },
    { value: "Boudjebaa El Bordj", label: "Boudjebaa El Bordj - بوجبع البرج" },
    { value: "Boukhanafis", label: "Boukhanafis - بوخنيفيس" },
    { value: "Chettouane Belaila", label: "Chetouane Belaila - شتوان بليلة" },
    { value: "Dhaya", label: "Dhaya - الضاية" },
    { value: "El Haçaiba", label: "El Hacaiba - الحصيبة" },
    { value: "Hassi Dahou", label: "Hassi Dahou - حاسي دحو" },
    { value: "Hassi Zehana", label: "Hassi Zahana - حاسي زهانة" },
    { value: "Lamtar", label: "Lamtar - لمطار" },
    { value: "M'Cid", label: "Mcid - مسيد" },
    { value: "Makedra", label: "Makedra - مقدرة" },
    { value: "Marhoum", label: "Marhoum - مرحوم" },
    { value: "Merine", label: "Merine - مرين" },
    { value: "Mezaourou", label: "Mezaourou - مزاورو" },
    {
      value: "Mostefa Ben Brahim",
      label: "Mostefa Ben Brahim - مصطفى بن ابراهيم",
    },
    { value: "Moulay Slissen", label: "Moulay Slissen - مولاي سليسن" },
    { value: "Oued Sebaa", label: "Oued Sebaa - وادي السبع" },
    { value: "Oued Sefioun", label: "Oued Sefioun - وادي سفيون" },
    { value: "Oued Taourira", label: "Oued Taourira - وادي تاوريرة" },
    { value: "Ras El Ma", label: "Ras El Ma - راس الماء" },
    { value: "Redjem Demouche", label: "Redjem Demouche - رجم دموش" },
    { value: "Sehala Thaoura", label: "Sehala Thaoura - سحالة ثاورة" },
    { value: "Sfisef", label: "Sfissef - الزفيزف" },
    { value: "Sidi Ali Benyoub", label: "Sidi Ali Benyoub - سيدي علي بن يوب" },
    {
      value: "Sidi Ali Boussidi",
      label: "Sidi Ali Boussidi - سيدي علي بوسيدي",
    },
    { value: "Sidi Bel Abbes", label: "Sidi Bel Abbes - سيدي بلعباس" },
    { value: "Sidi Brahim", label: "Sidi Brahim - سيدي ابراهيم" },
    { value: "Sidi Chaib", label: "Sidi Chaib - سيدي شعيب" },
    {
      value: "Sidi Daho des Zairs",
      label: "Sidi Dahou Zairs - سيدي دحو الزاير",
    },
    { value: "Sidi Hamadouche", label: "Sidi Hamadouche - سيدي حمادوش" },
    { value: "Sidi Khaled", label: "Sidi Khaled - سيدي خالد" },
    { value: "Sidi Lahcene", label: "Sidi Lahcene - سيدي لحسن" },
    { value: "Sidi Yacoub", label: "Sidi Yacoub - سيدي يعقوب" },
    { value: "Tabia", label: "Tabia - طابية" },
    { value: "Tafissour", label: "Tafissour - تافيسور" },
    { value: "Taoudmout", label: "Taoudmout - تاودموت" },
    { value: "Teghalimet", label: "Teghalimet - تغليمت" },
    { value: "Telagh", label: "Telagh - تلاغ" },
    { value: "Tenira", label: "Tenira - تنيرة" },
    { value: "Tessala", label: "Tessala - تسالة" },
    { value: "Tilmouni", label: "Tilmouni - تيلموني" },
    { value: "Zerouala", label: "Zerouala - زروالة" },
  ],
  Tiaret: [
    { value: "Aïn Bouchekif", label: "Ain Bouchekif - عين بوشقيق" },
    { value: "Aïn Deheb", label: "Ain Deheb - عين الذهب" },
    { value: "Aïn Dzarit", label: "Ain Zarit - عين زاريت" },
    { value: "Aïn El Hadid", label: "Ain El Hadid - عين الحديد" },
    { value: "Aïn Kermes", label: "Ain Kermes - عين كرمس" },
    { value: "Bougara", label: "Bougara - بوقرة" },
    { value: "Chehaima", label: "Chehaima - شحيمة" },
    { value: "Dahmouni", label: "Dahmouni - دحموني" },
    { value: "Djebilet Rosfa", label: "Djebilet Rosfa - جبيلة الرصفاء" },
    { value: "Djillali Ben Amar", label: "Djillali Ben Amar - جيلالي بن عمار" },
    { value: "Faidja", label: "Faidja - الفايجة" },
    { value: "Frenda", label: "Frenda - فرندة" },
    { value: "Guertoufa", label: "Guertoufa - قرطوفة" },
    { value: "Hamadia", label: "Hamadia - الحمادية" },
    { value: "Ksar Chellala", label: "Ksar Chellala - قصر الشلالة" },
    { value: "Madna", label: "Madna - مادنة" },
    { value: "Mahdia", label: "Mahdia - مهدية" },
    { value: "Mechraa Safa", label: "Mechraa Safa - مشرع الصفا" },
    { value: "Medrissa", label: "Medrissa - مديرسة" },
    { value: "Medroussa", label: "Medroussa - مدروسة" },
    { value: "Meghila", label: "Meghila - مغيلة" },
    { value: "Mellakou", label: "Mellakou - كلاكو" },
    { value: "Nadorah", label: "Nadorah - الناظورة" },
    { value: "Naima", label: "Naima - النعيمة" },
    { value: "Oued Lilli", label: "Oued Lilli - وادي ليلي" },
    { value: "Rahouia", label: "Rahouia - رحوية" },
    { value: "Rechaiga", label: "Rechaiga - الرشايقة" },
    { value: "Sebaine", label: "Sebaine - سبعين" },
    { value: "Sebt", label: "Sebt - السبت" },
    { value: "Serghine", label: "Serghine - سرغين" },
    { value: "Si Abdelghani", label: "Si Abdelghani - سي عبد الغني" },
    { value: "Sidi Abderahmane", label: "Sidi Abderrahmane - سيدي عبد الرحمن" },
    { value: "Sidi Ali Mellal", label: "Sidi Ali Mellal - سيدي علي ملال" },
    { value: "Sidi Bakhti", label: "Sidi Bakhti - سيدي بختي" },
    { value: "Sidi Hosni", label: "Sidi Hosni - سيدي الحسني" },
    { value: "Sougueur", label: "Sougueur - السوقر" },
    { value: "Tagdemt", label: "Tagdemt - تاقدمت" },
    { value: "Takhemaret", label: "Takhemaret - تخمرت" },
    { value: "Tiaret", label: "Tiaret - تيارت" },
    { value: "Tidda", label: "Tidda - تيدة" },
    { value: "Tousnina", label: "Tousnina - توسنينة" },
    {
      value: "Zmalet El Emir Abdelkader",
      label: "Zmalet El Emir Abdelkade - زاملة الأمير عبد القادر",
    },
  ],
  Guelma: [
    { value: "Aïn Ben Beida", label: "Ain Ben Beida - عين بن بيضاء" },
    { value: "Aïn Larbi", label: "Ain Larbi - عين العربي" },
    { value: "Aïn Makhlouf", label: "Ain Makhlouf - عين مخلوف" },
    { value: "Aïn Reggada", label: "Ain Reggada - عين رقادة" },
    { value: "Aïn Sandel", label: "Ain Sandel - عين صندل" },
    { value: "Belkheir", label: "Belkheir - بلخير" },
    { value: "Ben Djerrah", label: "Ben Djarah - بن جراح" },
    { value: "Beni Mezline", label: "Beni Mezline - بني مزلين" },
    { value: "Bordj Sabath", label: "Bordj Sabat - برج صباط" },
    { value: "Bouati Mahmoud", label: "Bouati Mahmoud - بوعاطي محمود" },
    { value: "Bouchegouf", label: "Bouchegouf - بوشقوف" },
    { value: "Bouhachana", label: "Bou Hachana - بوحشانة" },
    { value: "Bouhamdane", label: "Bou Hamdane - بوحمدان" },
    { value: "Boumahra Ahmed", label: "Bouhamra Ahmed - بومهرة أحمد" },
    { value: "Dahouara", label: "Dahouara - الداواهرة" },
    {
      value: "Djeballah Khemissi",
      label: "Djeballah Khemissi - جبالة الخميسي",
    },
    { value: "El Fedjoudj", label: "El Fedjoudj - الفجوج" },
    { value: "Guellat Bou Sbaa", label: "Guelaat Bou Sbaa - قلعة بوصبع" },
    { value: "Guelma", label: "Guelma - قالمة" },
    { value: "Hammam Debagh", label: "Hamam Debagh - حمام دباغ" },
    { value: "Hammam N'Bail", label: "Hammam N'bail - حمام النبايل" },
    { value: "Héliopolis", label: "Heliopolis - هيليوبوليس" },
    { value: "Houari Boumédiène", label: "Ain Hessania - عين الحساينية" },
    { value: "Khezarra", label: "Khezara - خزارة" },
    { value: "Medjez Amar", label: "Medjez Amar - مجاز عمار" },
    { value: "Medjez Sfa", label: "Medjez Sfa - مجاز الصفاء" },
    { value: "Nechmaya", label: "Nechmaya - نشماية" },
    { value: "Oued Cheham", label: "Oued Cheham - وادي الشحم" },
    { value: "Oued Fragha", label: "Oued Fragha - وادي فراغا" },
    { value: "Oued Zenati", label: "Oued Zenati - وادي الزناتي" },
    { value: "Ras El Agba", label: "Ras El Agba - رأس العقبة" },
    { value: "Roknia", label: "Roknia - الركنية" },
    { value: "Sellaoua Announa", label: "Sellaoua Announa - سلاوة عنونة" },
    { value: "Tamlouka", label: "Tamlouka - تاملوكة" },
  ],
  Mostaganem: [
    {
      value: "Abdelmalek Ramdane",
      label: "Benabdelmalek Ramdane - بن عبد المالك رمضان",
    },
    { value: "Achaacha", label: "Achaacha - عشعاشة" },
    { value: "Aïn Boudinar", label: "Ain-boudinar - عين بودينار" },
    { value: "Aïn Nouissy", label: "Ain Nouissy - عين نويسي" },
    { value: "Aïn Sidi Cherif", label: "Ain-sidi Cherif - عين سيدي الشريف" },
    { value: "Aïn Tedles", label: "Ain-tedles - عين تادلس" },
    { value: "Blad Touahria", label: "Touahria - الطواهرية" },
    { value: "Bouguirat", label: "Bouguirat - بوقيراط" },
    { value: "El Hassaine", label: "Hassiane - الحسيان" },
    { value: "Fornaka", label: "Fornaka - فرناقة" },
    { value: "Hadjadj", label: "Hadjadj - حجاج" },
    { value: "Hassi Mameche", label: "Hassi Mameche - حاسي معمش" },
    { value: "Khadra", label: "Khadra - خضراء" },
    { value: "Kheireddine", label: "Kheir Eddine - خير الدين" },
    { value: "Mansourah", label: "Mansourah - منصورة" },
    { value: "Mazagran", label: "Mazagran - مزغران" },
    { value: "Mesra", label: "Mesra - ماسرة" },
    { value: "Mostaganem", label: "Mostaganem - مستغانم" },
    { value: "Nekmaria", label: "Nekmaria - نكمارية" },
    { value: "Oued El Kheir", label: "Oued El Kheir - وادي الخير" },
    { value: "Ouled Boughalem", label: "Ouled Boughalem - أولاد بوغالم" },
    { value: "Ouled Maallah", label: "Ouled Maalah - أولاد مع الله" },
    { value: "Safsaf", label: "Safsaf - صفصاف" },
    { value: "Sayada", label: "Sayada - صيادة" },
    { value: "Sidi Ali", label: "Sidi Ali - سيدي علي" },
    { value: "Sidi Belattar", label: "Sidi Belaattar - سيدي بلعطار" },
    { value: "Sidi Lakhdar", label: "Sidi-lakhdar - سيدي لخضر" },
    { value: "Sirat", label: "Sirat - سيرات" },
    { value: "Souaflia", label: "Souaflia - السوافلية" },
    { value: "Sour", label: "Sour - سور" },
    { value: "Stidia", label: "Stidia - ستيدية" },
    { value: "Tazgait", label: "Tazgait - تزقايت" },
  ],
  Skikda: [
    { value: "Aïn Bouziane", label: "Ain Bouziane - عين بوزيان" },
    { value: "Aïn Charchar", label: "Ain Charchar - عين الشرشار" },
    { value: "Aïn Kechra", label: "Ain Kechera - عين قشرة" },
    { value: "Aïn Zouit", label: "Ain Zouit - عين زويت" },
    { value: "Azzaba", label: "Azzaba - عزابة" },
    { value: "Bekkouche Lakhdar", label: "Bekkouche Lakhdar - بكوش الأخضر" },
    { value: "Ben Azzouz", label: "Ben Azzouz - بن عزوز" },
    { value: "Beni Bechir", label: "Beni Bechir - بني بشير" },
    { value: "Beni Oulbane", label: "Beni Oulbane - بني ولبان" },
    { value: "Beni Zid", label: "Beni Zid - بني زيد" },
    { value: "Bin El Ouiden", label: "Bin El Ouiden - بين الويدان" },
    { value: "Bouchtata", label: "Bouchetata - بوشطاطة" },
    { value: "Cheraia", label: "Cheraia - الشرائع" },
    { value: "Collo", label: "Collo - القل" },
    {
      value: "Djendel Saadi Mohamed",
      label: "Djendel Saadi Mohamed - جندل سعيدي محمد",
    },
    { value: "El Ghedir", label: "El Ghedir - الغدير" },
    { value: "El Hadaiek", label: "El Hadaiek - الحدائق" },
    { value: "El Harrouch", label: "El Arrouch - الحروش" },
    { value: "El Marsa", label: "El Marsa - المرسى" },
    { value: "Emdjez Edchich", label: "Emjez Edchich - مجاز الدشيش" },
    { value: "Es Sebt", label: "Es Sebt - السبت" },
    { value: "Filfila", label: "Filfila - فلفلة" },
    { value: "Hamadi Krouma", label: "Hamadi Krouma - حمادي كرومة" },
    { value: "Kanoua", label: "Kanoua - قنواع" },
    { value: "Kerkera", label: "Kerkera - الكركرة" },
    { value: "Kheneg Mayoum", label: "Khenag Mayoum - خنق مايون" },
    { value: "Oued Zehour", label: "Oued Zhour - وادي الزهور" },
    {
      value: "Ouldja Boulballout",
      label: "Ouldja Boulbalout - الولجة بولبلوط",
    },
    { value: "Ouled Attia", label: "Ouled Attia - أولاد عطية" },
    { value: "Ouled Hbaba", label: "Ouled Habbeba - أولاد حبابة" },
    { value: "Oum Toub", label: "Oum Toub - أم الطوب" },
    { value: "Ramdane Djamel", label: "Ramdane Djamel - ومضان جمال" },
    { value: "Salah Bouchaour", label: "Salah Bouchaour - صالح بو الشعور" },
    { value: "Sidi Mezghiche", label: "Sidi Mezghiche - سيدي مزغيش" },
    { value: "Skikda", label: "Skikda - سكيكدة" },
    { value: "Tamalous", label: "Tamalous - تمالوس" },
    { value: "Zerdaza", label: "Zerdezas - زردازة" },
    { value: "Zitouna", label: "Zitouna - الزيتونة" },
  ],
  Batna: [
    { value: "Abdelkader Azil", label: "Azil Abedelkader - إزيل عبد القادر" },
    { value: "Aïn Djasser", label: "Ain Djasser - عين جاسر" },
    { value: "Aïn Touta", label: "Ain Touta - عين التوتة" },
    { value: "Aïn Yagout", label: "Ain Yagout - عين ياقوت" },
    { value: "Arris", label: "Arris - أريس" },
    { value: "Barika", label: "Barika - بريكة" },
    { value: "Batna", label: "Batna - باتنة" },
    {
      value: "Ben Foudhala El Hakania",
      label: "Beni Foudhala El Hakania - بني فوظالة الحكانية",
    },
    { value: "Bitam", label: "Bitam - بيطام" },
    { value: "Boulhilat", label: "Boulhilat - بوالحيلات" },
    { value: "Boumagueur", label: "Boumagueur - بومقر" },
    { value: "Boumia (Batna)", label: "Boumia - بومية" },
    { value: "Bouzina", label: "Bouzina - بوزينة" },
    { value: "Chemora", label: "Chemora - شمرة" },
    { value: "Chir", label: "Chir - شير" },
    { value: "Djerma", label: "Djerma - جرمة" },
    { value: "Djezar", label: "Djezzar - الجزار" },
    { value: "El Hassi", label: "El Hassi - الحاسي" },
    { value: "El Madher", label: "El Madher - المعذر" },
    { value: "Fesdis", label: "Fesdis - فسديس" },
    { value: "Foum Toub", label: "Foum Toub - فم الطوب" },
    { value: "Ghassira", label: "Ghassira - غسيرة" },
    { value: "Gosbat", label: "Gosbat - القصبات" },
    { value: "Guigba", label: "Guigba - قيقبة" },
    { value: "Hidoussa", label: "Hidoussa - حيدوسة" },
    { value: "Ichmoul", label: "Ichmoul - أشمول" },
    { value: "Inoughissen", label: "Inoughissen - إينوغيسن" },
    { value: "Kimmel", label: "Kimmel - كيمل" },
    { value: "Ksar Bellezma", label: "Ksar Bellezma - قصر بلزمة" },
    { value: "Larbaâ", label: "Larbaa - لرباع" },
    { value: "Lazrou", label: "Lazrou - لازرو" },
    { value: "Lemsane", label: "Lemsane - لمسان" },
    { value: "M'doukel", label: "Mdoukal - مدوكال" },
    { value: "Maafa", label: "Maafa - معافة" },
    { value: "Menaa", label: "Menaa - منعة" },
    { value: "Merouana", label: "Merouana - مروانة" },
    { value: "N'Gaous", label: "Ngaous - نقاوس" },
    { value: "Oued Chaaba", label: "Oued Chaaba - وادي الشعبة" },
    { value: "Oued El Ma", label: "Oued El Ma - وادي الماء" },
    { value: "Oued Taga", label: "Oued Taga - وادي الطاقة" },
    { value: "Ouled Ammar", label: "Ouled Ammar - أولاد عمار" },
    { value: "Ouled Aouf", label: "Ouled Aouf - أولاد عوف" },
    { value: "Ouled Fadel", label: "Ouled Fadel - أولاد فاضل" },
    { value: "Ouled Sellam", label: "Ouled Sellem - أولاد سالم" },
    {
      value: "Ouled Si Slimane",
      label: "Ouled Si Slimane - أولاد سيدي سليمان",
    },
    { value: "Ouyoun El Assafir", label: "Ouyoun El Assafir - عيون العصافير" },
    { value: "Rahbat", label: "Rahbat - الرحبات" },
    { value: "Ras El Aioun", label: "Ras El Aioun - رأس العيون" },
    { value: "Sefiane", label: "Sefiane - سفيان" },
    { value: "Seggana", label: "Seggana - سقانة" },
    { value: "Seriana", label: "Seriana - سريانة" },
    { value: "T'Kout", label: "Tkout - تكوت" },
    { value: "Talkhamt", label: "Talkhamt - تالغمت" },
    { value: "Taxlent", label: "Taxlent - تاكسلانة" },
    { value: "Tazoult", label: "Tazoult - تازولت" },
    { value: "Teniet El Abed", label: "Teniet El Abed - ثنية العابد" },
    { value: "Tighanimine", label: "Tighanimine - تغانمين" },
    { value: "Tigherghar", label: "Tigharghar - تغرغار" },
    { value: "Tilatou", label: "Tilatou - تيلاطو" },
    { value: "Timgad", label: "Timgad - تيمقاد" },
    { value: "Zanat El Beida", label: "Zanet El Beida - زانة البيضاء" },
  ],
  "M'Sila": [
    { value: "Aïn El Hadjel", label: "Ain El Hadjel - عين الحجل" },
    { value: "Aïn El Melh", label: "Ain El Melh - عين الملح" },
    { value: "Aïn Errich", label: "Ain Rich - عين الريش" },
    { value: "Aïn Fares", label: "Ain Fares - عين فارس" },
    { value: "Aïn Khadra", label: "Ain Khadra - عين خضراء" },
    { value: "Belaiba", label: "Belaiba - بلعايبة" },
    { value: "Ben Srour", label: "Ben Srour - ابن سرور" },
    { value: "Beni Ilmane", label: "Beni Ilmane - بني يلمان" },
    { value: "Benzouh", label: "Benzouh - بن زوح" },
    { value: "Berhoum", label: "Berhoum - برهوم" },
    { value: "Bir Foda", label: "Bir Foda - بئر الفضة" },
    { value: "Bou Saâda", label: "Bou Saada - بوسعادة" },
    { value: "Bouti Sayah", label: "Bouti Sayeh - بوطي السياح" },
    { value: "Chellal", label: "Chellal - شلال" },
    { value: "Dehahna", label: "Dehahna - دهاهنة" },
    { value: "Djebel Messaad", label: "Djebel Messaad - جبل مسعد" },
    { value: "El Hamel", label: "El Hamel - الهامل" },
    { value: "El Houamed", label: "El Houamed - الحوامد" },
    { value: "Hammam Dhalaa", label: "Hammam Dalaa - حمام الضلعة" },
    {
      value: "Khettouti Sed El Djir",
      label: "Khettouti Sed El Jir - ختوتي سد الجير",
    },
    { value: "Khoubana", label: "Khoubana - خبانة" },
    { value: "M'Cif", label: "Mcif - مصيف" },
    { value: "M'Sila", label: "M'sila - المسيلة" },
    { value: "M'Tarfa", label: "Mtarfa - المطارفة" },
    { value: "Maadid", label: "Maadid - المعاضيد" },
    { value: "Maarif", label: "Maarif - معاريف" },
    { value: "Magra", label: "Magra - مقرة" },
    { value: "Medjedel", label: "Medjedel - مجدل" },
    { value: "Mohammed Boudiaf", label: "Mohamed Boudiaf - محمد بوضياف" },
    { value: "Ouanougha", label: "Ouanougha - ونوغة" },
    {
      value: "Ouled Addi Guebala",
      label: "Ouled Addi Guebala - أولاد عدي قبالة",
    },
    { value: "Ouled Atia", label: "Menaa Ouled Attia - منعة -أولاد عطية" },
    { value: "Ouled Derradj", label: "Ouled Derradj - أولاد دراج" },
    { value: "Ouled Madhi", label: "Ouled Madhi - أولاد ماضي" },
    { value: "Ouled Mansour", label: "Ouled Mansour - أولاد منصور" },
    {
      value: "Ouled Sidi Brahim",
      label: "Ouled Sidi Brahim - أولاد سيدي ابراهيم",
    },
    { value: "Ouled Slimane", label: "Ouled Slimane - أولاد سليمان" },
    { value: "Oultem", label: "Oulteme - ولتام" },
    { value: "Sidi Aïssa", label: "Sidi Aissa - سيدي عيسى" },
    { value: "Sidi Ameur", label: "Sidi Ameur - سيدي عامر" },
    { value: "Sidi Hadjeres", label: "Sidi Hadjeres - سيدي هجرس" },
    { value: "Sidi M'Hamed", label: "Sidi Mhamed - سيدي أحمد" },
    { value: "Slim", label: "Slim - سليم" },
    { value: "Souamaa", label: "Souamaa - الصوامع" },
    { value: "Tamsa", label: "Tamsa - تامسة" },
    { value: "Tarmount", label: "Tarmount - تارمونت" },
    { value: "Zarzour", label: "Zarzour - زرزور" },
  ],
  "Tizi Ouzou": [
    { value: "Abi Youcef", label: "Abi Youcef - أبي يوسف" },
    { value: "Aghribs", label: "Aghribs - أغريب" },
    { value: "Agouni Gueghrane", label: "Agouni Gueghrane - أقني قغران" },
    { value: "Ain El Hammam", label: "Ain El Hammam - عين الحمام" },
    { value: "Aïn Zaouia", label: "Ain Zaouia - عين الزاوية" },
    { value: "Aït Aggouacha", label: "Ait Aggouacha - أيت قواشة" },
    { value: "Aït Aïssa Mimoun", label: "Ait Aissa Mimoun - أيت عيسى ميمون" },
    { value: "Aït Bouadou", label: "Ait Bouaddou - أيت بوعدو" },
    { value: "Aït Boumahdi", label: "Ait Boumehdi - أيت بومهدي" },
    { value: "Aït Chafâa", label: "Ait Chafaa - أيت شفعة" },
    { value: "Aït Khellili", label: "Ait Khellili - أيت خليلي" },
    { value: "Aït Mahmoud", label: "Ait-mahmoud - أيت محمود" },
    { value: "Aït Oumalou", label: "Ait Oumalou - أيت أومالو" },
    { value: "Aït Toudert", label: "Ait Toudert - أيت تودرت" },
    { value: "Aït Yahia", label: "Ait-yahia - أيت يحي" },
    { value: "Aït Yahia Moussa", label: "Ait Yahia Moussa - أيت يحيى" },
    { value: "Aït Yenni", label: "Ait Yenni - أيت يني" },
    { value: "Akbil", label: "Akbil - اقبيل" },
    { value: "Akerrou", label: "Akerrou - أقرو" },
    { value: "Assi Youcef", label: "Assi Youcef - أسي يوسف" },
    { value: "Ath Zikki", label: "Ait Zikki - أيت زيكي" },
    { value: "Azazga", label: "Azazga - عزازقة" },
    { value: "Azeffoun", label: "Azeffoun - أزفون" },
    { value: "Beni Aïssi", label: "Beni Aissi - بني عيسي" },
    { value: "Beni Douala", label: "Beni-douala - بني دوالة" },
    { value: "Beni Zmenzer", label: "Beni Zmenzer - بني زمنزر" },
    { value: "Boghni", label: "Boghni - بوغني" },
    { value: "Boudjima", label: "Boudjima - بوجيمة" },
    { value: "Bounouh", label: "Bounouh - بونوح" },
    { value: "Bouzguen", label: "Bouzeguene - بوزغن" },
    { value: "Draâ Ben Khedda", label: "Draa Ben Khedda - ذراع بن خدة" },
    { value: "Draâ El Mizan", label: "Draa El Mizan - ذراع الميزان" },
    { value: "Freha", label: "Freha - فريحة" },
    { value: "Frikat", label: "Frikat - فريقات" },
    { value: "Iboudraren", label: "Iboudrarene - أبودرارن" },
    { value: "Idjeur", label: "Idjeur - إجر" },
    { value: "Iferhounène", label: "Iferhounene - ايفرحونن" },
    { value: "Ifigha", label: "Ifigha - إيفيغاء" },
    { value: "Iflissen", label: "Iflissen - أفليسن" },
    { value: "Illilten", label: "Illilten - اليلتين" },
    { value: "Illoula Oumalou", label: "Illoula Oumalou - ايلولة امالو" },
    { value: "Imsouhel", label: "Imsouhal - أمسوحال" },
    { value: "Irdjen", label: "Irdjen - ارجن" },
    {
      value: "Larbaâ Nath Irathen",
      label: "Larba Nath Irathen - الاربعاء نايث ايراثن",
    },
    { value: "M'Kira", label: "Mkira - مكيرة" },
    { value: "Mâatkas", label: "Maatkas - المعاتقة" },
    { value: "Makouda", label: "Makouda - ماكودة" },
    { value: "Mechtras", label: "Mechtras - مشطراس" },
    { value: "Mekla", label: "Mekla - مقلة" },
    { value: "Mizrana", label: "Mizrana - مزرانة" },
    { value: "Ouacif", label: "Ouacif - واسيف" },
    { value: "Ouadhia", label: "Ouadhia - واضية" },
    { value: "Ouaguenoun", label: "Ouaguenoune - واقنون" },
    { value: "Sidi Namane", label: "Sidi Naamane - سيدي نعمان" },
    { value: "Souamaâ", label: "Souamaa - الصوامع" },
    { value: "Souk El Thenine", label: "Souk El Thenine - سوق الاثنين" },
    { value: "Tadmaït", label: "Tadmait - تادمايت" },
    { value: "Tigzirt", label: "Tigzirt - تقيزريت" },
    { value: "Timizart", label: "Timizart - تيميزارت" },
    { value: "Tirmitine", label: "Tirmitine - تيرمتين" },
    { value: "Tizi Gheniff", label: "Tizi Ghenif - تيزي غنيف" },
    { value: "Tizi N'Tleta", label: "Tizi Ntleta - تيزي نثلاثة" },
    { value: "Tizi Ouzou", label: "Tizi ouzou - تيزي وزو" },
    { value: "Tizi Rached", label: "Tizi Rached - تيزي راشد" },
    { value: "Yakouren", label: "Yakourene - يعكورن" },
    { value: "Yatafen", label: "Yatafene - ياطفان" },
    { value: "Zekri", label: "Zekri - زكري" },
  ],
  "El Tarf": [
    { value: "Aïn El Assel", label: "Ain El Assel - عين العسل" },
    { value: "Aïn Kerma", label: "Ain Kerma - عين الكرمة" },
    { value: "Asfour", label: "Asfour - عصفور" },
    { value: "Ben Mehidi", label: "Ben Mhidi - ابن مهيدي" },
    { value: "Berrihane", label: "Berrihane - بريحان" },
    { value: "Besbes", label: "Besbes - البسباس" },
    { value: "Bougous", label: "Bougous - بوقوس" },
    { value: "Bouhadjar", label: "Bouhadjar - بوحجار" },
    { value: "Bouteldja", label: "Bouteldja - بوثلجة" },
    { value: "Chebaita Mokhtar", label: "Chebaita Mokhtar - شبايطة مختار" },
    { value: "Chefia", label: "Chefia - الشافية" },
    { value: "Chihani", label: "Chihani - شهاني" },
    { value: "Dréan", label: "Drean - الذرغان" },
    { value: "Echatt", label: "Echatt - الشط" },
    { value: "El Aioun", label: "El Aioun - العيون" },
    { value: "El Kala", label: "El Kala - القالة" },
    { value: "El Tarf", label: "El Tarf - الطارف" },
    { value: "Hammam Beni Salah", label: "Hammam Beni Salah - حمام بن صالح" },
    { value: "Lac des Oiseaux", label: "Lac Des Oiseaux - بحيرة الطيور" },
    { value: "Oued Zitoun", label: "Oued Zitoun - وادي الزيتون" },
    { value: "Raml Souk", label: "Raml Souk - رمل السوق" },
    { value: "Souarekh", label: "Souarekh - السواريخ" },
    { value: "Zerizer", label: "Zerizer - زريزر" },
    { value: "Zitouna", label: "Zitouna - الزيتونة" },
  ],
  "Oum El Bouaghi": [
    { value: "Aïn Babouche", label: "Ain Babouche - عين بابوش" },
    { value: "Aïn Beïda", label: "Ain Beida - عين البيضاء" },
    { value: "Aïn Diss", label: "Ain Diss - عين الديس" },
    { value: "Aïn Fakroun", label: "Ain Fekroune - عين الفكرون" },
    { value: "Aïn Kercha", label: "Ain Kercha - عين كرشة" },
    { value: "Aïn M'lila", label: "Ain M'lila - عين مليلة" },
    { value: "Aïn Zitoun", label: "Ain Zitoun - عين الزيتون" },
    { value: "Behir Chergui", label: "Behir Chergui - بحير الشرقي" },
    { value: "Berriche", label: "Berriche - بريش" },
    { value: "Bir Chouhada", label: "Bir Chouhada - بئر الشهداء" },
    { value: "Dhalaa", label: "Dhala - الضلعة" },
    { value: "El Amiria", label: "El Amiria - العامرية" },
    { value: "El Belala", label: "El Belala - البلالة" },
    { value: "El Djazia", label: "El Djazia - الجازية" },
    {
      value: "El Fedjoudj Boughrara Saoudi",
      label: "El Fedjoudj Boughrara Saoudi - الفجوج بوغرارة سعودي",
    },
    { value: "El Harmilia", label: "El Harmilia - الحرملية" },
    { value: "Fkirina", label: "Fkirina - فكيرينة" },
    { value: "Hanchir Toumghani", label: "Hanchir Toumghani - هنشير تومغاني" },
    { value: "Ksar Sbahi", label: "Ksar Sbahi - قصر الصباحي" },
    { value: "Meskiana", label: "Meskiana - مسكيانة" },
    { value: "Oued Nini", label: "Oued Nini - وادي نيني" },
    { value: "Ouled Gacem", label: "Ouled Gacem - أولاد قاسم" },
    { value: "Ouled Hamla", label: "Ouled Hamla - أولاد حملة" },
    { value: "Ouled Zouaï", label: "Ouled Zouai - أولاد زاوي" },
    { value: "Oum el Bouaghi", label: "Oum El Bouaghi - أم البواقي" },
    { value: "Rahia", label: "Rahia - الراحية" },
    { value: "Sigus", label: "Sigus - سيقوس" },
    { value: "Souk Naamane", label: "Souk Naamane - سوق نعمان" },
    { value: "Zorg", label: "Zorg - الزرق" },
  ],
  Tissemsilt: [
    { value: "Ammari", label: "Ammari - عماري" },
    { value: "Beni Chaib", label: "Beni Chaib - بني شعيب" },
    { value: "Beni Lahcene", label: "Beni Lahcene - بني الحسن" },
    { value: "Bordj Bou Naama", label: "Bordj Bounaama - برج بونعامة" },
    {
      value: "Bordj El Emir Abdelkader",
      label: "Bordj El Emir Abdelkader - برج الأمير عبد القادر",
    },
    { value: "Boucaid", label: "Bou Caid - بوقايد" },
    { value: "Khemisti", label: "Khemisti - خميستي" },
    { value: "Larbaa", label: "Larbaa - الأربعاء" },
    { value: "Lardjem", label: "Lardjem - الأرجم" },
    { value: "Layoune", label: "Layoune - العيون" },
    { value: "Lazharia", label: "Lazharia - الأزهرية" },
    { value: "Maacem", label: "Maacem - المعاصم" },
    { value: "Melaab", label: "Melaab - ملعب" },
    { value: "Ouled Bessem", label: "Ouled Bessem - أولاد بسام" },
    { value: "Sidi Abed", label: "Sidi Abed - سيدي عابد" },
    { value: "Sidi Boutouchent", label: "Sidi Boutouchent - سيدي بوتوشنت" },
    { value: "Sidi Lantri", label: "Sidi Lantri - سيدي العنتري" },
    { value: "Sidi Slimane", label: "Sidi Slimane - سيدي سليمان" },
    { value: "Tamalaht", label: "Tamellalet - تاملاحت" },
    { value: "Theniet El Had", label: "Theniet El Had - ثنية الاحد" },
    { value: "Tissemsilt", label: "Tissemsilt - تيسمسيلت" },
    { value: "Youssoufia", label: "Youssoufia - اليوسفية" },
  ],
  Ouargla: [
    { value: "Aïn Beida", label: "Ain Beida - عين البيضاء" },
    { value: "Benaceur", label: "Benaceur - بن ناصر" },
    { value: "Blidet Amor", label: "Blidet Amor - بلدية عامر" },
    { value: "El Allia", label: "El Alia - العالية" },
    { value: "El Borma", label: "El Borma - البرمة" },
    { value: "El Hadjira", label: "El-hadjira - الحجيرة" },
    {
      value: "Hassi Ben Abdellah",
      label: "Hassi Ben Abdellah - حاسي بن عبد الله",
    },
    { value: "Hassi Messaoud", label: "Hassi Messaoud - حاسي مسعود" },
    { value: "M'Naguer", label: "M'naguer - المنقر" },
    { value: "Megarine", label: "Megarine - المقارين" },
    { value: "N'Goussa", label: "Ngoussa - نقوسة" },
    { value: "Nezla", label: "Nezla - النزلة" },
    { value: "Ouargla", label: "Ouargla - ورقلة" },
    { value: "Rouissat", label: "Rouissat - الرويسات" },
    { value: "Sidi Khouiled", label: "Sidi Khouiled - سيدي خويلد" },
    { value: "Sidi Slimane", label: "Sidi Slimane - سيدي سليمان" },
    { value: "Taibet", label: "Taibet - الطيبات" },
    { value: "Tamacine", label: "Temacine - تماسين" },
    { value: "Tebesbest", label: "Tebesbest - تبسبست" },
    { value: "Touggourt", label: "Touggourt - توقرت" },
    { value: "Zaouia El Abidia", label: "Zaouia El Abidia - الزاوية العابدية" },
  ],
  "El Oued": [
    { value: "Bayadha", label: "Bayadha - البياضة" },
    { value: "Beni Guecha", label: "Ben Guecha - بني قشة" },
    { value: "Debila", label: "Debila - الدبيلة" },
    { value: "Djamaa", label: "Djamaa - جامعة" },
    { value: "Douar El Ma", label: "Douar El Maa - دوار الماء" },
    { value: "El M'Ghair", label: "El-m'ghair - المغير" },
    { value: "El Ogla", label: "El Ogla - العقلة" },
    { value: "El Oued", label: "El Oued - الوادي" },
    { value: "Guemar", label: "Guemar - قمار" },
    { value: "Hamraia", label: "Hamraia - الحمراية" },
    {
      value: "Hassani Abdelkrim",
      label: "Hassani Abdelkrim - حساني عبد الكريم",
    },
    { value: "Hassi Khalifa", label: "Hassi Khalifa - حاسي خليفة" },
    { value: "Kouinine", label: "Kouinine - كوينين" },
    { value: "M'Rara", label: "M'rara - مرارة" },
    { value: "Magrane", label: "Magrane - المقرن" },
    { value: "Mih Ouansa", label: "Mih Ouansa - ميه وانسة" },
    { value: "Nakhla", label: "Nakhla - النخلة" },
    { value: "Oued El Alenda", label: "Oued El Alenda - وادي العلندة" },
    { value: "Oum Touyour", label: "Oum Touyour - أم الطيور" },
    { value: "Ourmas", label: "Ourmes - ورماس" },
    { value: "Reguiba", label: "Reguiba - الرقيبة" },
    { value: "Robbah", label: "Robbah - الرباح" },
    { value: "Sidi Amrane", label: "Sidi Amrane - سيدي عمران" },
    { value: "Sidi Aoun", label: "Sidi Aoun - سيدي عون" },
    { value: "Sidi Khellil", label: "Sidi Khelil - سيدي خليل" },
    { value: "Still", label: "Still - سطيل" },
    { value: "Taghzout", label: "Taghzout - تاغزوت" },
    { value: "Taleb Larbi", label: "Taleb Larbi - طالب العربي" },
    { value: "Tendla", label: "Tenedla - تندلة" },
    { value: "Trifaoui", label: "Trifaoui - الطريفاوي" },
  ],
  Tipaza: [
    { value: "Aghbal", label: "Aghbal - أغبال" },
    { value: "Ahmar El Aïn", label: "Ahmer El Ain - أحمر العين" },
    { value: "Aïn Tagourait", label: "Ain Tagourait - عين تاقورايت" },
    { value: "Attatba", label: "Attatba - الحطاطبة" },
    { value: "Beni Milleuk", label: "Beni Mileuk - بني ميلك" },
    { value: "Bou Ismaïl", label: "Bou Ismail - بواسماعيل" },
    { value: "Bouharoun", label: "Bou Haroun - بوهارون" },
    { value: "Bourkika", label: "Bourkika - بورقيقة" },
    { value: "Chaiba", label: "Chaiba - الشعيبة" },
    { value: "Cherchell", label: "Cherchell - شرشال" },
    { value: "Damous", label: "Damous - الداموس" },
    { value: "Douaouda", label: "Douaouda - دواودة" },
    { value: "Fouka", label: "Fouka - فوكة" },
    { value: "Gouraya", label: "Gouraya - قوراية" },
    { value: "Hadjeret Ennous", label: "Hadjret Ennous - حجرة النص" },
    { value: "Hadjout", label: "Hadjout - حجوط" },
    { value: "Khemisti", label: "Khemisti - خميستي" },
    { value: "Koléa", label: "Kolea - القليعة" },
    { value: "Larhat", label: "Larhat - الأرهاط" },
    { value: "Menaceur", label: "Menaceur - مناصر" },
    { value: "Merad", label: "Merad - مراد" },
    { value: "Messelmoun", label: "Messelmoun - مسلمون" },
    { value: "Nador", label: "Nador - الناظور" },
    { value: "Sidi Amar", label: "Sidi-amar - سيدي عامر" },
    { value: "Sidi Ghiles", label: "Sidi Ghiles - سيدي غيلاس" },
    { value: "Sidi Rached", label: "Sidi Rached - سيدي راشد" },
    { value: "Sidi Semiane", label: "Sidi Semiane - سيدي سميان" },
    { value: "Tipaza", label: "Tipaza - تيبازة" },
  ],
  Adrar: [
    { value: "Adrar", label: "Adrar - أدرار" },
    { value: "Akabli", label: "Akabli - اقبلي" },
    { value: "Aougrout", label: "Aougrout - أوقروت" },
    { value: "Aoulef", label: "Aoulef - أولف" },
    {
      value: "Bordj Badji Mokhtar",
      label: "Bordj Badji Mokhtar - برج باجي مختار",
    },
    { value: "Bouda", label: "Bouda - بودة" },
    { value: "Charouine", label: "Charouine - شروين" },
    { value: "Deldoul", label: "Deldoul - دلدول" },
    { value: "Fenoughil", label: "Fenoughil - فنوغيل" },
    { value: "In Zghmir", label: "In Zghmir - انزجمير" },
    { value: "Ksar Kaddour", label: "Ksar Kaddour - قصر قدور" },
    { value: "Metarfa", label: "Metarfa - المطارفة" },
    {
      value: "Ouled Ahmed Tammi",
      label: "Ouled Ahmed Timmi - أولاد أحمد تيمي",
    },
    { value: "Ouled Aïssa", label: "Ouled Aissa - أولاد عيسى" },
    { value: "Ouled Saïd", label: "Ouled Said - أولاد سعيد" },
    { value: "Reggane", label: "Reggane - رقان" },
    { value: "Sali", label: "Sali - سالي" },
    { value: "Sebaa", label: "Sebaa - سبع" },
    { value: "Talmine", label: "Talmine - طلمين" },
    { value: "Tamantit", label: "Tamantit - تمنطيط" },
    { value: "Tamekten", label: "Timekten - تيمقطن" },
    { value: "Tamest", label: "Tamest - تامست" },
    { value: "Timiaouine", label: "Timiaouine - تيمياوين" },
    { value: "Timimoun", label: "Timimoun - تيميمون" },
    { value: "Tinerkouk", label: "Tinerkouk - تينركوك" },
    { value: "Tit", label: "Tit - تيط" },
    { value: "Tsabit", label: "Tsabit - تسابيت" },
    { value: "Zaouiet Kounta", label: "Zaouiet Kounta - زاوية كنتة" },
  ],
  Illizi: [
    { value: "Bordj El Haouas", label: "Bordj El Haouasse - برج الحواس" },
    { value: "Bordj Omar Driss", label: "Bordj Omar Driss - برج عمر إدريس" },
    { value: "Debdeb", label: "Debdeb - دبداب" },
    { value: "Djanet", label: "Djanet - جانت" },
    { value: "Illizi", label: "Illizi - إيليزي" },
    { value: "In Amenas", label: "In Amenas - إن أميناس" },
  ],
  Biskra: [
    { value: "Aïn Naga", label: "Ain Naga - عين الناقة" },
    { value: "Aïn Zaatout", label: "Ain Zaatout - عين زعطوط" },
    { value: "Besbes", label: "Besbes - بسباس" },
    { value: "Biskra", label: "Biskra - بسكرة" },
    { value: "Bordj Ben Azzouz", label: "Bordj Ben Azzouz - برج بن عزوز" },
    { value: "Bouchagroune", label: "Bouchagroun - بوشقرون" },
    { value: "Branis", label: "Branis - البرانس" },
    { value: "Chetma", label: "Chetma - شتمة" },
    { value: "Djemorah", label: "Djemorah - جمورة" },
    { value: "Doucen", label: "Doucen - الدوسن" },
    { value: "Ech Chaïba", label: "Chaiba - الشعيبة" },
    { value: "El Feidh", label: "El Feidh - الفيض" },
    { value: "El Ghrous", label: "El Ghrous - الغروس" },
    { value: "El Hadjeb", label: "El Hadjab - الحاجب" },
    { value: "El Haouch", label: "El Haouch - الحوش" },
    { value: "El Kantara", label: "El Kantara - القنطرة" },
    { value: "El Mizaraa", label: "Meziraa - المزيرعة" },
    { value: "El Outaya", label: "El Outaya - الوطاية" },
    { value: "Foughala", label: "Foughala - فوغالة" },
    {
      value: "Khenguet Sidi Nadji",
      label: "Khenguet Sidi Nadji - خنقة سيدي ناجي",
    },
    { value: "Lichana", label: "Lichana - لشانة" },
    { value: "Lioua", label: "Lioua - لواء" },
    { value: "M'Chouneche", label: "M'chouneche - مشونش" },
    { value: "M'Lili", label: "Mlili - مليلي" },
    { value: "Mekhadma", label: "Mekhadma - مخادمة" },
    { value: "Ouled Djellal", label: "Ouled Djellal - أولاد جلال" },
    { value: "Oumache", label: "Oumache - أوماش" },
    { value: "Ourlal", label: "Ourlal - أورلال" },
    { value: "Ras El Miaad", label: "Ras El Miad - رأس الميعاد" },
    { value: "Sidi Khaled", label: "Sidi Khaled - سيدي خالد" },
    { value: "Sidi Okba", label: "Sidi Okba - سيدي عقبة" },
    { value: "Tolga", label: "Tolga - طولقة" },
    { value: "Zeribet El Oued", label: "Zeribet El Oued - زريبة الوادي" },
  ],
  "Aïn Defla": [
    { value: "Aïn Benian", label: "Ain Benian - عين البنيان" },
    { value: "Aïn Bouyahia", label: "Ain Bouyahia - عين بويحيى" },
    { value: "Aïn Defla", label: "Ain Defla - عين الدفلة" },
    { value: "Aïn Lechiekh", label: "Ain Lechiakh - عين الاشياخ" },
    { value: "Aïn Soltane", label: "Ain-soltane - عين السلطان" },
    { value: "Aïn Torki", label: "Ain Torki - عين الترك" },
    { value: "Arib", label: "Arib - عريب" },
    { value: "Bathia", label: "Bathia - بطحية" },
    { value: "Belaas", label: "Belaas - بالعاص" },
    { value: "Ben Allal", label: "Ben Allal - إبن علال" },
    { value: "Bir Ould Khelifa", label: "Bir Ould Khelifa - بئر ولد خليفة" },
    { value: "Birbouche", label: "Barbouche - بربوش" },
    {
      value: "Bordj Emir Khaled",
      label: "Bordj-emir-khaled - برج الأمير خالد",
    },
    { value: "Boumedfaa", label: "Boumedfaa - بومدفع" },
    { value: "Bourached", label: "Bourached - بوراشد" },
    { value: "Djelida", label: "Djelida - جليدة" },
    {
      value: "Djemaa Ouled Cheikh",
      label: "Djemaa Ouled Cheikh - جمعة أولاد الشيخ",
    },
    { value: "Djendel", label: "Djendel - جندل" },
    { value: "El Abadia", label: "El Abadia - العبادية" },
    { value: "El Amra", label: "El Amra - العامرة" },
    { value: "El Attaf", label: "El Attaf - العطاف" },
    { value: "El Hassania", label: "Hassania - الحسانية" },
    { value: "El Maine", label: "El Maine - الماين" },
    { value: "Hammam Righa", label: "Hammam Righa - حمام ريغة" },
    { value: "Hoceinia", label: "Hoceinia - الحسينية" },
    { value: "Khemis Miliana", label: "Khemis Miliana - خميس مليانة" },
    { value: "Mekhatria", label: "Mekhatria - المخاطرية" },
    { value: "Miliana", label: "Miliana - مليانة" },
    { value: "Oued Chorfa", label: "Oued Chorfa - وادي الشرفاء" },
    { value: "Oued Djemaa", label: "Oued Djemaa - وادي جمعة" },
    { value: "Rouina", label: "Rouina - روينة" },
    { value: "Sidi Lakhdar", label: "Sidi Lakhdar - سيدي الأخضر" },
    { value: "Tacheta Zougagha", label: "Tacheta Zegagha - تاشتة زقاغة" },
    { value: "Tarik Ibn Ziad", label: "Tarik-ibn-ziad - طارق بن زياد" },
    { value: "Tiberkanine", label: "Tiberkanine - تبركانين" },
    { value: "Zeddine", label: "Zeddine - زدين" },
  ],
  Saïda: [
    { value: "Aïn El Hadjar", label: "Ain El Hadjar - عين الحجر" },
    { value: "Aïn Sekhouna", label: "Ain Sekhouna - عين السخونة" },
    { value: "Aïn Soltane", label: "Ain Soltane - عين السلطان" },
    { value: "Doui Thabet", label: "Doui Thabet - دوي ثابت" },
    { value: "El Hassasna", label: "El Hassasna - الحساسنة" },
    { value: "Hounet", label: "Hounet - حنات" },
    { value: "Maamora", label: "Maamora - المعمورة" },
    { value: "Moulay Larbi", label: "Moulay Larbi - مولاي العربي" },
    { value: "Ouled Brahim", label: "Ouled Brahim - أولاد إبراهيم" },
    { value: "Ouled Khaled", label: "Ouled Khaled - أولاد خالد" },
    { value: "Saïda", label: "Saida - سعيدة" },
    { value: "Sidi Ahmed", label: "Sidi Ahmed - سيدي احمد" },
    { value: "Sidi Amar", label: "Sidi Amar - سيدي عمار" },
    { value: "Sidi Boubekeur", label: "Sidi Boubekeur - سيدي بوبكر" },
    { value: "Tircine", label: "Tircine - تيرسين" },
    { value: "Youb", label: "Youb - يوب" },
  ],
  "Bordj Bou Arreridj": [
    { value: "Aïn Taghrout", label: "Ain Taghrout - عين تاغروت" },
    { value: "Aïn Tesra", label: "Ain Tesra - عين تسرة" },
    { value: "Belimour", label: "Belimour - بليمور" },
    { value: "Ben Daoud", label: "Ben Daoud - بن داود" },
    { value: "Bir Kasdali", label: "Bir Kasdali - بئر قصد علي" },
    { value: "Bordj Bou Arreridj", label: "Bordj Bou Arreridj - برج بوعريرج" },
    { value: "Bordj Ghédir", label: "Bordj Ghdir - برج غدير" },
    { value: "Bordj Zemoura", label: "Bordj Zemora - برج زمورة" },
    { value: "Colla", label: "Colla - القلة" },
    { value: "Djaafra", label: "Djaafra - الجعافرة" },
    { value: "El Ach", label: "El Ach - العش" },
    { value: "El Achir", label: "El Achir - الياشير" },
    { value: "El Anseur", label: "El Anseur - العنصر" },
    { value: "El Hamadia", label: "El Hamadia - الحمادية" },
    { value: "El M'hir", label: "El Mhir - المهير" },
    { value: "El Main", label: "El Main - الماين" },
    { value: "Ghilassa", label: "Ghilassa - غيلاسة" },
    { value: "Haraza", label: "Haraza - حرازة" },
    { value: "Hasnaoua", label: "Hasnaoua - حسناوة" },
    { value: "Khelil", label: "Khelil - خليل" },
    { value: "Ksour", label: "Ksour - القصور" },
    { value: "Mansoura", label: "Mansoura - المنصورة" },
    { value: "Medjana", label: "Medjana - مجانة" },
    { value: "Ouled Brahem", label: "Ouled Brahem - أولاد أبراهيم" },
    { value: "Ouled Dahmane", label: "Ouled Dahmane - أولاد دحمان" },
    {
      value: "Ouled Sidi Brahim",
      label: "Ouled Sidi Brahim - أولاد سيدي ابراهيم",
    },
    { value: "Rabta", label: "Rabta - الرابطة" },
    { value: "Ras El Oued", label: "Ras El Oued - رأس الوادي" },
    { value: "Sidi Embarek", label: "Sidi Embarek - سيدي مبارك" },
    { value: "Taglait", label: "Taglait - تقلعيت" },
    { value: "Tassameurt", label: "Tesmart - تسمرت" },
    { value: "Tefreg", label: "Tafreg - تفرق" },
    { value: "Teniet En Nasr", label: "Teniet En Nasr - ثنية النصر" },
    { value: "Tixter", label: "Tixter - تيكستير" },
  ],
  Ghardaïa: [
    { value: "Berriane", label: "Berriane - بريان" },
    { value: "Bounoura", label: "Bounoura - بونورة" },
    { value: "Dhayet Bendhahoua", label: "Dhayet Bendhahoua - ضاية بن ضحوة" },
    { value: "El Atteuf", label: "El Atteuf - العطف" },
    { value: "El Guerrara", label: "El Guerrara - القرارة" },
    { value: "El Menia", label: "El Meniaa - المنيعة" },
    { value: "Ghardaïa", label: "Ghardaia - غرداية" },
    { value: "Hassi Fehal", label: "Hassi Fehal - حاسي الفحل" },
    { value: "Hassi Gara", label: "Hassi Gara - حاسي القارة" },
    { value: "Mansoura", label: "Mansoura - المنصورة" },
    { value: "Metlili", label: "Metlili - منليلي" },
    { value: "Sebseb", label: "Sebseb - سبسب" },
    { value: "Zelfana", label: "Zelfana - رلفانة" },
  ],
  Alger: [
    { value: "Aïn Benian", label: "Ain Benian - عين بنيان" },
    { value: "Aïn Taya", label: "Ain Taya - عين طاية" },
    { value: "Alger Centre", label: "Alger Centre - الجزائر" },
    { value: "Bab El Oued", label: "Bab El Oued - باب الوادي" },
    { value: "Bab Ezzouar", label: "Bab Ezzouar - باب الزوار" },
    { value: "Baba Hassen", label: "Baba Hesen - بابا حسن" },
    { value: "Bachdjerrah", label: "Bachedjerah - باش جراح" },
    { value: "Baraki", label: "Baraki - براقي" },
    { value: "Belouizdad", label: "Mohamed Belouzdad - محمد بلوزداد" },
    { value: "Ben Aknoun", label: "Ben Aknoun - ابن عكنون" },
    { value: "Beni Messous", label: "Beni Messous - بني مسوس" },
    { value: "Bir Mourad Raïs", label: "Bir Mourad Rais - بئر مراد رايس" },
    { value: "Birkhadem", label: "Birkhadem - بئر خادم" },
    { value: "Birtouta", label: "Bir Touta - بئر توتة" },
    { value: "Bologhine", label: "Bologhine Ibnou Ziri - بولوغين بن زيري" },
    { value: "Bordj El Bahri", label: "Bordj El Bahri - برج البحري" },
    { value: "Bordj El Kiffan", label: "Bordj El Kiffan - برج الكيفان" },
    { value: "Bourouba", label: "Bourouba - بوروبة" },
    { value: "Bouzareah", label: "Bouzareah - بوزريعة" },
    { value: "Casbah", label: "Casbah - القصبة" },
    { value: "Cheraga", label: "Cheraga - الشراقة" },
    { value: "Dar El Beïda", label: "Dar El Beida - الدار البيضاء" },
    { value: "Dely Ibrahim", label: "Dely Ibrahim - دالي ابراهيم" },
    { value: "Djasr Kasentina", label: "Djasr Kasentina - جسر قسنطينة" },
    { value: "Douera", label: "Douira - الدويرة" },
    { value: "Draria", label: "Draria - الدرارية" },
    { value: "El Achour", label: "El Achour - العاشور" },
    { value: "El Biar", label: "El Biar - الابيار" },
    { value: "El Hammamet", label: "El Hammamet - الحمامات" },
    { value: "El Harrach", label: "El Harrach - الحراش" },
    { value: "El Madania", label: "El Madania - المدنية" },
    { value: "El Magharia", label: "El Magharia - المغارية" },
    { value: "El Marsa", label: "El Merssa - المرسى" },
    { value: "El Mouradia", label: "El Mouradia - المرادية" },
    { value: "H'raoua", label: "Herraoua - هراوة" },
    { value: "Hussein Dey", label: "Hussein Dey - حسين داي" },
    { value: "Hydra", label: "Hydra - حيدرة" },
    { value: "Khraicia", label: "Kheraisia - الخرايسية" },
    { value: "Kouba", label: "Kouba - القبة" },
    { value: "Les Eucalyptus", label: "Les Eucalyptus - الكاليتوس" },
    { value: "Mahelma", label: "Maalma - المعالمة" },
    { value: "Mohammadia", label: "Mohammadia - المحمدية" },
    { value: "Oued Koriche", label: "Oued Koriche - وادي قريش" },
    { value: "Oued Smar", label: "Oued Smar - وادي السمار" },
    { value: "Ouled Chebel", label: "Ouled Chebel - اولاد شبل" },
    { value: "Ouled Fayet", label: "Ouled Fayet - اولاد فايت" },
    { value: "Rahmania", label: "Rahmania - الرحمانية" },
    { value: "Raïs Hamidou", label: "Rais Hamidou - الرايس حميدو" },
    { value: "Reghaïa", label: "Reghaia - رغاية" },
    { value: "Rouïba", label: "Rouiba - الرويبة" },
    { value: "Saoula", label: "Sehaoula - السحاولة" },
    { value: "Sidi M'Hamed", label: "Sidi Mhamed - سيدي امحمد" },
    { value: "Sidi Moussa", label: "Sidi Moussa - سيدي موسى" },
    { value: "Souidania", label: "Souidania - سويدانية" },
    { value: "Staoueli", label: "Setaouali - سطاوالي" },
    { value: "Tessala El Merdja", label: "Tessala El Merdja - تسالة المرجة" },
    { value: "Zeralda", label: "Zeralda - زرالدة" },
  ],
  Tamanrasset: [
    { value: "Abalessa", label: "Abalessa - آبلسّا" },
    { value: "Foggaret Ezzaouia", label: "Foggaret Azzaouia - فقارة الزوا" },
    { value: "Idles", label: "Idles - أدلس" },
    { value: "In Amguel", label: "Ain Amguel - عين امقل" },
    { value: "In Ghar", label: "In Ghar - إنغر" },
    { value: "In Guezzam", label: "In Guezzam - عين قزام" },
    { value: "In Salah", label: "In Salah - عين صالح" },
    { value: "Tamanrasset", label: "Tamanrasset - تامنغست" },
    { value: "Tazrouk", label: "Tazrouk - تازروك" },
    { value: "Tin Zaouatine", label: "Tin Zouatine - تينزواتين" },
  ],
  Sétif: [
    { value: "Aïn Abessa", label: "Ain Abessa - عين عباسة" },
    { value: "Aïn Arnat", label: "Ain Arnat - عين أرنات" },
    { value: "Aïn Azel", label: "Ain Azel - عين أزال" },
    { value: "Aïn El Kebira", label: "Ain El Kebira - العين الكبيرة" },
    { value: "Aïn Lahdjar", label: "Ain Lahdjar - عين الحجر" },
    { value: "Aïn Legradj", label: "Ain Legradj - عين لقراج" },
    { value: "Aïn Oulmene", label: "Ain Oulmane - عين ولمان" },
    { value: "Aïn Roua", label: "Ain Roua - عين الروى" },
    { value: "Aïn Sebt", label: "Ain Sebt - عين السبت" },
    { value: "Aït Naoual Mezada", label: "Ait Naoual Mezada - أيت نوال مزادة" },
    { value: "Aït Tizi", label: "Ait Tizi - ايت تيزي" },
    { value: "Aït Wertilan", label: "Aït Wertilan - ايت ورتيلان" },
    { value: "Amoucha", label: "Amoucha - عموشة" },
    { value: "Babor", label: "Babor - بابور" },
    { value: "Bazer Sakhra", label: "Bazer Sakra - بازر الصخرة" },
    { value: "Beidha Bordj", label: "Beidha Bordj - بيضاء برج" },
    { value: "Belaa", label: "Bellaa - بلعة" },
    { value: "Beni Aziz", label: "Beni-aziz - بني عزيز" },
    { value: "Beni Chebana", label: "Beni Chebana - بني شبانة" },
    { value: "Beni Fouda", label: "Beni Fouda - بني فودة" },
    { value: "Beni Hocine", label: "Beni Oussine - بني وسين" },
    { value: "Beni Mouhli", label: "Beni Mouhli - بني موحلي" },
    { value: "Bir El Arch", label: "Bir El Arch - بئر العرش" },
    { value: "Bir Haddada", label: "Bir Haddada - بئر حدادة" },
    { value: "Bouandas", label: "Bouandas - بوعنداس" },
    { value: "Bougaa", label: "Bougaa - بوقاعة" },
    { value: "Bousselam", label: "Bousselam - بوسلام" },
    { value: "Boutaleb", label: "Boutaleb - بوطالب" },
    { value: "Dehamcha", label: "Dehamcha - الدهامشة" },
    { value: "Djemila", label: "Djemila - جميلة" },
    { value: "Draa Kebila", label: "Draa Kebila - ذراع القبيلة" },
    { value: "El Eulma", label: "El Eulma - العلمة" },
    { value: "El Ouldja", label: "El Ouldja - الولجة" },
    { value: "El Ouricia", label: "El Ouricia - الوريسية" },
    { value: "Guellal", label: "Guellal - قلال بوطالب" },
    { value: "Guelta Zerka", label: "Guelta Zerka - القتلة الزرقاء" },
    { value: "Guenzet", label: "Guenzet - قنزات" },
    { value: "Guidjel", label: "Guidjel - قجال" },
    { value: "Hamma", label: "Hamma - الحامة" },
    { value: "Hammam Guergour", label: "Hammam Guergour - حمام قرقور" },
    { value: "Hammam Soukhna", label: "Hamam Soukhna - حمام السخنة" },
    { value: "Harbil", label: "Harbil - حربيل" },
    { value: "Ksar El Abtal", label: "Ksar El Abtal - قصر الابطال" },
    { value: "Maaouia", label: "Maaouia - معاوية" },
    { value: "Maoklane", label: "Maouaklane - ماوكلان" },
    { value: "Mezloug", label: "Mezloug - مزلوق" },
    { value: "Oued El Barad", label: "Oued El Barad - وادي البارد" },
    { value: "Ouled Addouane", label: "Ouled Addouane - أولاد عدوان" },
    { value: "Ouled Sabor", label: "Ouled Sabor - أولاد صابر" },
    { value: "Ouled Si Ahmed", label: "Ouled Si Ahmed - أولاد سي أحمد" },
    { value: "Ouled Tebben", label: "Ouled Tebben - أولاد تبان" },
    { value: "Rasfa", label: "Rosfa - الرصفة" },
    { value: "Salah Bey", label: "Salah Bey - صالح باي" },
    { value: "Serdj El Ghoul", label: "Serdj El Ghoul - سرج الغول" },
    { value: "Sétif", label: "Setif - سطيف" },
    { value: "Tachouda", label: "Tachouda - تاشودة" },
    { value: "Talaifacene", label: "Tala Ifacene - تالة إيفاسن" },
    { value: "Taya", label: "Taya - الطاية" },
    { value: "Tella", label: "Tella - النلعة" },
    { value: "Tizi N'Bechar", label: "Tizi Nbechar - تيزي نبشار" },
  ],
  Khenchela: [
    { value: "Aïn Touila", label: "Ain Touila - عين الطويلة" },
    { value: "Babar", label: "Babar - ببار" },
    { value: "Baghai", label: "Baghai - بغاي" },
    { value: "Bouhmama", label: "Bouhmama - بوحمامة" },
    { value: "Chechar", label: "Cherchar - ششار" },
    { value: "Chelia", label: "Chelia - شلية" },
    { value: "Djellal", label: "Djellal - جلال" },
    { value: "El Hamma", label: "El Hamma - الحامة" },
    { value: "El Mahmal", label: "El Mahmal - المحمل" },
    { value: "El Oueldja", label: "El Oueldja - الولجة" },
    { value: "Ensigha", label: "Ensigha - انسيغة" },
    { value: "Kais", label: "Kais - قايس" },
    { value: "Khenchela", label: "Khenchela - خنشلة" },
    { value: "Khirane", label: "Khirane - خيران" },
    { value: "M'Sara", label: "Msara - مصارة" },
    { value: "M'Toussa", label: "Mtoussa - متوسة" },
    { value: "Ouled Rechache", label: "Ouled Rechache - أولاد رشاش" },
    { value: "Remila", label: "Remila - الرميلة" },
    { value: "Tamza", label: "Tamza - تلمزة" },
    { value: "Taouzient", label: "Taouzianat - تاوزيانت" },
    { value: "Yabous", label: "Yabous - يابوس" },
  ],
  Annaba: [
    { value: "Aïn Berda", label: "Ain Berda - العين الباردة" },
    { value: "Annaba", label: "Annaba - عنابة" },
    { value: "Berrahal", label: "Berrahel - برحال" },
    { value: "Chetaïbi", label: "Chetaibi - شطايبي" },
    { value: "Cheurfa", label: "Cheurfa - الشرفاء" },
    { value: "El Bouni", label: "El Bouni - البوني" },
    { value: "El Hadjar", label: "El Hadjar - الحجار" },
    { value: "Eulma", label: "Eulma - العلمة" },
    { value: "Oued El Aneb", label: "Oued El Aneb - وادي العنب" },
    { value: "Seraïdi", label: "Seraidi - سرايدي" },
    { value: "Sidi Amar", label: "Sidi Amar - سيد عامر" },
    { value: "Treat", label: "Treat - التريعات" },
  ],
  Constantine: [
    { value: "Aïn Abid", label: "Ain Abid - عين عبيد" },
    { value: "Aïn Smara", label: "Ain Smara - عين السمارة" },
    { value: "Beni Hamiden", label: "Beni Hamidene - بني حميدان" },
    { value: "Constantine", label: "Constantine - قسنطينة" },
    { value: "Didouche Mourad", label: "Didouche Mourad - ديدوش مراد" },
    { value: "El Khroub", label: "El Khroub - الخروب" },
    { value: "Hamma Bouziane", label: "Hamma Bouziane - حامة بوزيان" },
    { value: "Ibn Badis", label: "Ben Badis - أبن باديس الهرية" },
    { value: "Ibn Ziad", label: "Ibn Ziad - ابن زياد" },
    { value: "Messaoud Boudjriou", label: "Messaoud Boujeriou - بوجريو مسعود" },
    { value: "Ouled Rahmoune", label: "Ouled Rahmouni - أولاد رحمون" },
    { value: "Zighoud Youcef", label: "Zighoud Youcef - زيغود يوسف" },
  ],
  Tindouf: [
    { value: "Oum el Assel", label: "Oum el Assel - أم العسل" },
    { value: "Tindouf", label: "Tindouf - تندوف" },
  ],
  Médéa: [
    { value: "Aïn Boucif", label: "Ain Boucif - عين بوسيف" },
    { value: "Aïn Ouksir", label: "Ain Ouksir - عين القصيرة" },
    { value: "Aissaouia", label: "Aissaouia - العيساوية" },
    { value: "Aziz", label: "Aziz - عزيز" },
    { value: "Baata", label: "Baata - بعطة" },
    { value: "Benchicao", label: "Ben Chicao - بن شكاو" },
    { value: "Beni Slimane", label: "Beni Slimane - بني سليمان" },
    { value: "Berrouaghia", label: "Berrouaghia - البرواقية" },
    { value: "Bir Ben Laabed", label: "Bir Ben Laabed - بئر بن عابد" },
    { value: "Boghar", label: "Boghar - بوغار" },
    { value: "Bou Aiche", label: "Bouaiche - بوعيش" },
    { value: "Bouaichoune", label: "Bouaichoune - بوعيشون" },
    { value: "Bouchrahil", label: "Bouchrahil - بوشراحيل" },
    { value: "Boughezoul", label: "Boughzoul - بوغزول" },
    { value: "Bouskene", label: "Bouskene - بوسكن" },
    { value: "Chahbounia", label: "Chabounia - الشهبونية" },
    {
      value: "Chellalet El Adhaoura",
      label: "Chelalet El Adhaoura - شلالة العذاورة",
    },
    { value: "Cheniguel", label: "Cheniguel - شنيقل" },
    { value: "Derrag", label: "Derrag - دراق" },
    { value: "Deux Bassins", label: "Deux Bassins - الحوضان" },
    { value: "Djouab", label: "Djouab - جواب" },
    { value: "Draa Essamar", label: "Draa Essamar - ذراع السمار" },
    { value: "El Azizia", label: "El Azizia - العزيزية" },
    { value: "El Guelb El Kebir", label: "El Guelbelkebir - القلب الكبير" },
    { value: "El Hamdania", label: "El Hamdania - الحمدانية" },
    { value: "El Omaria", label: "El Omaria - العمرية" },
    { value: "El Ouinet", label: "El Ouinet - العوينات" },
    { value: "Hannacha", label: "Hannacha - حناشة" },
    { value: "Kef Lakhdar", label: "Kef Lakhdar - الكاف الاخضر" },
    { value: "Khams Djouamaa", label: "Khams Djouamaa - خمس جوامع" },
    { value: "Ksar Boukhari", label: "Ksar El Boukhari - قصر البخاري" },
    { value: "Médéa", label: "Medea - المدية" },
    { value: "Meftaha", label: "Meftaha - مفتاح" },
    { value: "Meghraoua", label: "Maghraoua - مغراوة" },
    { value: "Mezerana", label: "Mezerana - مزغنة" },
    { value: "Mihoub", label: "Mihoub - ميهوب" },
    { value: "Moudjbar", label: "Medjebar - مجبر" },
    { value: "Ouamri", label: "Ouamri - عوامري" },
    { value: "Oued Harbil", label: "Oued Harbil - وادي حربيل" },
    { value: "Ouled Antar", label: "Ouled Antar - أولاد عنتر" },
    { value: "Ouled Bouachra", label: "Ouled Bouachra - أولاد بوعشرة" },
    { value: "Ouled Brahim", label: "Ouled Brahim - أولاد إبراهيم" },
    { value: "Ouled Deide", label: "Ouled Deid - أولاد دايد" },
    { value: "Ouled Hellal", label: "Ouled Hellal - أولاد هلال" },
    { value: "Ouled Maaref", label: "Ouled Maaref - أولاد معروف" },
    { value: "Oum El Djalil", label: "Oum El Djellil - أم الجليل" },
    { value: "Ouzera", label: "Ouzera - وزرة" },
    { value: "Rebaia", label: "Rebaia - الربعية" },
    { value: "Saneg", label: "Saneg - السائق" },
    { value: "Sedraia", label: "Sedraya - سدراية" },
    { value: "Seghouane", label: "Seghouane - سغوان" },
    { value: "Si Mahdjoub", label: "Si Mahdjoub - سي المحجوب" },
    { value: "Sidi Damed", label: "Sidi Demed - سيدي دامد" },
    { value: "Sidi Errabia", label: "Sidi Rabie - سيدي الربيع" },
    { value: "Sidi Naamanez", label: "Sidi Naamane - سيدي نعمان" },
    { value: "Sidi Zahar", label: "Sidi Zahar - سيدي زهار" },
    { value: "Sidi Ziane", label: "Sidi Ziane - سيدي زيان" },
    { value: "Souagui", label: "Souagui - السواقي" },
    { value: "Tablat", label: "Tablat - تابلاط" },
    { value: "Tafraout", label: "Tafraout - تفراوت" },
    { value: "Tamesguida", label: "Tamesguida - تمسقيدة" },
    { value: "Tizi Mahdi", label: "Tizi Mahdi - تيزي مهدي" },
    { value: "Tlatet Eddouar", label: "Tletat Ed Douair - ثلاث دوائر" },
    { value: "Zoubiria", label: "Zoubiria - الزبيرية" },
    { value: "Demiat", label: "Damiat - دميات" },
  ],
  "El Bayadh": [
    { value: "Aïn El Orak", label: "Ain El Orak - عين العراك" },
    { value: "Arbaouat", label: "Arbaouat - عرباوة" },
    { value: "Boualem", label: "Boualem - بوعلام" },
    { value: "Bougtoub", label: "Bougtoub - بوقطب" },
    { value: "Boussemghoun", label: "Boussemghoun - بوسمغون" },
    { value: "Brezina", label: "Brezina - بريزينة" },
    { value: "Cheguig", label: "Cheguig - الشقيق" },
    { value: "Chellala", label: "Chellala - شلالة" },
    {
      value: "El Abiodh Sidi Cheikh",
      label: "El Biodh Sidi Cheikh - الأبيض سيدي الشيخ",
    },
    { value: "El Bayadh", label: "El Bayadh - البيض" },
    { value: "El Bnoud", label: "El Bnoud - البنود" },
    { value: "El Kheiter", label: "El Kheither - الخيثر" },
    { value: "El Mehara", label: "El Mehara - المهارة" },
    { value: "Ghassoul", label: "Ghassoul - غسول" },
    { value: "Kef El Ahmar", label: "Kef El Ahmar - الكاف الأحمر" },
    { value: "Kraakda", label: "Krakda - كراكدة" },
    { value: "Rogassa", label: "Rogassa - رقاصة" },
    { value: "Sidi Ameur", label: "Sidi Ameur - سيدي عامر" },
    { value: "Sidi Slimane", label: "Sidi Slimane - سيدي سليمان" },
    { value: "Sidi Tifour", label: "Sidi Tifour - سيدي تيفور" },
    { value: "Stitten", label: "Stitten - ستيتن" },
    { value: "Tousmouline", label: "Tousmouline - توسمولين" },
  ],
  Oran: [
    { value: "Aïn El Bia", label: "Ain Biya - عين البية" },
    { value: "Aïn El Kerma", label: "Ain Kerma - عين الكرمة" },
    { value: "Aïn El Turk", label: "Ain Turk - عين الترك" },
    { value: "Arzew", label: "Arzew - أرزيو" },
    { value: "Ben Freha", label: "Ben Freha - بن فريحة" },
    { value: "Bethioua", label: "Bethioua - بطيوة" },
    { value: "Bir El Djir", label: "Bir El Djir - بئر الجير" },
    { value: "Bou Sfer", label: "Bousfer - بوصفر" },
    { value: "Boufatis", label: "Boufatis - بوفتيس" },
    { value: "Boutlelis", label: "Boutlelis - بوتليليس" },
    { value: "El Ançor", label: "El Ancar - العنصر" },
    { value: "El Braya", label: "El Braya - البراية" },
    { value: "El Kerma", label: "El Kerma - الكرمة" },
    { value: "Es Senia", label: "Es Senia - السانية" },
    { value: "Gdyel", label: "Gdyel - قديل" },
    { value: "Hassi Ben Okba", label: "Hassi Ben Okba - حاسي بن عقبة" },
    { value: "Hassi Bounif", label: "Hassi Bounif - حاسي بونيف" },
    { value: "Hassi Mefsoukh", label: "Hassi Mefsoukh - حاسي مفسوخ" },
    { value: "Marsat El Hadjadj", label: "Marsat El Hadjadj - مرسى الحجاج" },
    { value: "Mers El Kébir", label: "Mers El Kebir - المرسى الكبير" },
    { value: "Misserghin", label: "Messerghin - مسرغين" },
    { value: "Oran", label: "Oran - وهران" },
    { value: "Oued Tlelat", label: "Oued Tlelat - وادي تليلات" },
    { value: "Sidi Benyebka", label: "Sidi Ben Yebka - سيدي بن يبقى" },
    { value: "Sidi Chami", label: "Sidi Chami - سيدي الشحمي" },
    { value: "Tafraoui", label: "Tafraoui - طفراوي" },
  ],
  "Souk Ahras": [
    { value: "Aïn Soltane", label: "Ain Soltane - عين السلطان" },
    { value: "Aïn Zana", label: "Ain Zana - عين الزانة" },
    { value: "Bir Bou Haouch", label: "Bir Bouhouche - بئر بوحوش" },
    { value: "Drea", label: "Drea - الدريعة" },
    { value: "Hanancha", label: "Hanencha - الجنانشة" },
    { value: "Heddada", label: "Haddada - الحدادة" },
    { value: "Khedara", label: "Khedara - لخضارة" },
    { value: "Khemissa", label: "Khemissa - خميسة" },
    { value: "M'daourouch", label: "Mdaourouche - مداوروش" },
    { value: "Mechroha", label: "Machroha - مشروحة" },
    { value: "Merahna", label: "Merahna - المراهنة" },
    { value: "Oued Keberit", label: "Oued Kebrit - وادي الكبريت" },
    { value: "Ouillen", label: "Quillen - ويلان" },
    { value: "Ouled Driss", label: "Ouled Driss - أولاد إدريس" },
    { value: "Ouled Moumene", label: "Ouled Moumen - أولاد مومن" },
    { value: "Oum El Adhaim", label: "Oum El Adhaim - أم العظايم" },
    { value: "Ragouba", label: "Ragouba - الرقوبة" },
    { value: "Safel El Ouiden", label: "Safel El Ouiden - سافل الويدان" },
    { value: "Sedrata", label: "Sedrata - سدراتة" },
    { value: "Sidi Fredj", label: "Sidi Fredj - سيدي فرج" },
    { value: "Souk Ahras", label: "Souk Ahras - سوق أهراس" },
    { value: "Taoura", label: "Taoura - تاورة" },
    { value: "Terraguelt", label: "Terraguelt - ترقالت" },
    { value: "Tiffech", label: "Tiffech - تيفاش" },
    { value: "Zaarouria", label: "Zaarouria - الزعرورية" },
    { value: "Zouabi", label: "Zouabi - الزوابي" },
  ],
  Naâma: [
    { value: "Aïn Ben Khelil", label: "Ain Ben Khelil - عين بن خليل" },
    { value: "Aïn Sefra", label: "Ain Safra - عين الصفراء" },
    { value: "Assela", label: "Assela - عسلة" },
    { value: "Djeniene Bourezg", label: "Djeniane Bourzeg - جنين بورزق" },
    { value: "El Biod", label: "El Biod - البيوض" },
    { value: "Kasdir", label: "Kasdir - قصدير" },
    { value: "Makman Ben Amer", label: "Makman Ben Amer - مكمن بن عمرو" },
    { value: "Mecheria", label: "Mecheria - مشرية" },
    { value: "Moghrar", label: "Moghrar - مغرار" },
    { value: "Naâma", label: "Naama - النعامة" },
    { value: "Sfissifa", label: "Sfissifa - سفيسيفة" },
    { value: "Tiout", label: "Tiout - تيوت" },
  ],
  Boumerdès: [
    { value: "Afir", label: "Afir - أفير" },
    { value: "Ammal", label: "Ammal - عمال" },
    { value: "Baghlia", label: "Baghlia - بغلية" },
    { value: "Ben Choud", label: "Ben Choud - بني شود" },
    { value: "Beni Amrane", label: "Beni Amrane - بني عمران" },
    { value: "Bordj Menaiel", label: "Bordj Menaiel - برج منايل" },
    { value: "Boudouaou", label: "Boudouaou - بودواو" },
    {
      value: "Boudouaou El Bahri",
      label: "Boudouaou El Bahri - بودواو البحري",
    },
    { value: "Boumerdes", label: "Boumerdes - بومرداس" },
    { value: "Bouzegza Keddara", label: "Bouzegza Keddara - بوزقرة قدارة" },
    { value: "Chabet el Ameur", label: "Chabet El Ameur - شعبة العامر" },
    { value: "Corso", label: "Corso - قورصو" },
    { value: "Dellys", label: "Dellys - دلس" },
    { value: "Djinet", label: "Djinet - جينات" },
    { value: "El Kharrouba", label: "El Kharrouba - الخروبة" },
    { value: "Hammedi", label: "Hammedi - حمادي" },
    { value: "Issers", label: "Isser - يسر" },
    { value: "Khemis El Khechna", label: "Khemis El Khechna - خميس الخشنة" },
    { value: "Larbatache", label: "Larbatache - الاربعطاش" },
    { value: "Leghata", label: "Leghata - القاطة" },
    { value: "Naciria", label: "Naciria - الناصرية" },
    { value: "Ouled Aissa", label: "Ouled Aissa - أولاد عيسى" },
    { value: "Ouled Hedadj", label: "Ouled Hedadj - أولاد هداج" },
    { value: "Ouled Moussa", label: "Ouled Moussa - أولاد موسى" },
    { value: "Si Mustapha", label: "Si Mustapha - سي مصطفى" },
    { value: "Sidi Daoud", label: "Sidi Daoud - سيدي داود" },
    { value: "Souk El Had", label: "Souk El Haad - سوق الأحد" },
    { value: "Taourga", label: "Taourga - تورقة" },
    { value: "Thenia", label: "Thenia - الثنية" },
    { value: "Tidjelabine", label: "Tidjelabine - تجلبين" },
    { value: "Timezrit", label: "Timezrit - تمزريت" },
    { value: "Zemmouri", label: "Zemmouri - زموري" },
  ],
  Mascara: [
    { value: "Aïn Fares", label: "Ain Fares - عين فارس" },
    { value: "Aïn Fekan", label: "Ain Fekan - عين فكان" },
    { value: "Aïn Ferah", label: "Ain Ferah - عين فراح" },
    { value: "Aïn Fras", label: "Ain Frass - عين الفرس" },
    { value: "Alaïmia", label: "Alaimia - العلايمية" },
    { value: "Aouf", label: "Aouf - عوف" },
    { value: "Beniane", label: "Benian - بنيان" },
    { value: "Bou Hanifia", label: "Bouhanifia - بوحنيفية" },
    { value: "Bou Henni", label: "Bou Henni - بوهني" },
    { value: "Chorfa", label: "Chorfa - الشرفاء" },
    { value: "El Bordj", label: "El Bordj - البرج" },
    { value: "El Gaada", label: "El Gaada - القعدة" },
    { value: "El Ghomri", label: "El Ghomri - الغمري" },
    { value: "El Guettana", label: "El Gueitena - القطنة" },
    { value: "El Keurt", label: "El Keurt - القرط" },
    { value: "El Menaouer", label: "El Menaouer - المنور" },
    { value: "Ferraguig", label: "Ferraguig - فراقيق" },
    { value: "Froha", label: "Froha - فروحة" },
    { value: "Gharrous", label: "Gharrous - غروس" },
    { value: "Ghriss", label: "Ghriss - غريس" },
    { value: "Guerdjoum", label: "Guerdjoum - قرجوم" },
    { value: "Hachem", label: "El Hachem - الحشم" },
    { value: "Hacine", label: "Hacine - حسين" },
    { value: "Khalouia", label: "Khalouia - خلوية" },
    { value: "Makdha", label: "Makhda - ماقضة" },
    { value: "Mamounia", label: "El Mamounia - المأمونية" },
    { value: "Maoussa", label: "Maoussa - ماوسة" },
    { value: "Mascara", label: "Mascara - معسكر" },
    { value: "Matemore", label: "Matemore - المطمور" },
    { value: "Mocta Douz", label: "Mocta Douz - مقطع الدوز" },
    { value: "Mohammadia", label: "Mohammadia - المحمدية" },
    { value: "Nesmoth", label: "Nesmot - نسمط" },
    { value: "Oggaz", label: "Oggaz - عكاز" },
    { value: "Oued El Abtal", label: "Oued El Abtal - وادي الأبطال" },
    { value: "Oued Taria", label: "Oued Taria - وادي تاغية" },
    {
      value: "Ras El Aïn Amirouche",
      label: "Ras El Ain Amirouche - رأس عين عميروش",
    },
    { value: "Sedjerara", label: "Sedjerara - سجرارة" },
    { value: "Sehailia", label: "Sehailia - السهايلية" },
    { value: "Sidi Abdeldjebar", label: "Sidi Abdeldjebar - سيدي عبد الجبار" },
    { value: "Sidi Abdelmoumen", label: "Sidi Abdelmoumene - سيدي عبد المومن" },
    { value: "Sidi Boussaid", label: "Sidi Boussaid - سيدي بوسعيد" },
    { value: "Sidi Kada", label: "Sidi Kada - سيدي قادة" },
    { value: "Sig", label: "Sig - سيق" },
    { value: "Tighennif", label: "Tighennif - تيغنيف" },
    { value: "Tizi", label: "Tizi - تيزي" },
    { value: "Zahana", label: "Zahana - زهانة" },
    { value: "Zelmata", label: "Zelamta - زلامطة" },
  ],
  "Aïn Témouchent": [
    { value: "Aghlal", label: "Aghlal - أغلال" },
    { value: "Aïn El Arbaa", label: "Ain El Arbaa - عين الأربعاء" },
    { value: "Aïn Kihal", label: "Ain Kihal - عين الكحيل" },
    { value: "Aïn Témouchent", label: "Ain Temouchent - عين تيموشنت" },
    { value: "Aïn Tolba", label: "Ain Tolba - عين الطلبة" },
    { value: "Aoubellil", label: "Aoubellil - عقب الليل" },
    { value: "Beni Saf", label: "Beni Saf - بني صاف" },
    { value: "Bouzedjar", label: "Bouzedjar - بوزجار" },
    { value: "Chaabat El Leham", label: "Chaabat El Ham - شعبة اللحم" },
    { value: "Chentouf", label: "Chentouf - شنتوف" },
    { value: "El Amria", label: "El Amria - العامرية" },
    {
      value: "El Emir Abdelkader",
      label: "Emir Abdelkader - الأمير عبد القادر",
    },
    { value: "El Malah", label: "El Malah - المالح" },
    { value: "El Messaid", label: "El Messaid - المساعيد" },
    { value: "Hammam Bouhadjar", label: "Hammam Bouhadjar - حملم بوحجر" },
    { value: "Hassasna", label: "Hassasna - الحساسنة" },
    { value: "Hassi El Ghella", label: "Hassi El Ghella - حاسي الغلة" },
    { value: "Oued Berkeche", label: "Oued Berkeche - وادي برقش" },
    { value: "Oued Sabah", label: "Oued Sebbah - وادي الصباح" },
    { value: "Ouled Boudjemaa", label: "Ouled Boudjemaa - أولاد بوجمعة" },
    { value: "Ouled Kihal", label: "Ouled Kihal - أولاد كحيل" },
    {
      value: "Oulhaça El Gheraba",
      label: "Oulhaca El Gheraba - ولهاصة الغرابة",
    },
    { value: "Sidi Ben Adda", label: "Sidi Ben Adda - سيدي بن عدة" },
    { value: "Sidi Boumedienne", label: "Sidi Boumediene - سيدي بومدين" },
    { value: "Sidi Ouriache", label: "Sidi Ouriache - سيدي أورياش" },
    { value: "Sidi Safi", label: "Sidi Safi - سيدي الصافي" },
    { value: "Tamzoura", label: "Tamzoura - تامزورة" },
    { value: "Terga", label: "Terga - تارقة" },
  ],
  Mila: [
    { value: "Ahmed Rachedi", label: "Ahmed Rachedi - أحمد راشدي" },
    {
      value: "Aïn Beida Harriche",
      label: "Ain Beida Harriche - عين البيضاء حريش",
    },
    { value: "Aïn Mellouk", label: "Ain Mellouk - عين ملوك" },
    { value: "Aïn Tine", label: "Ain Tine - عين التين" },
    { value: "Amira Arrès", label: "Amira Arres - عميرة أراس" },
    {
      value: "Benyahia Abderrahmane",
      label: "Benyahia Abderrahmane - أبن يحيى عبد الرحمن",
    },
    { value: "Bouhatem", label: "Bouhatem - بوحاتم" },
    { value: "Chelghoum Laid", label: "Chelghoum Laid - شلغوم العيد" },
    { value: "Chigara", label: "Chigara - السيقارة" },
    { value: "Derradji Bousselah", label: "Derradji Bousselah - دراجي بوصالح" },
    { value: "El Mechira", label: "El Mechira - المشيرة" },
    { value: "Elayadi Barbes", label: "Elayadi Barbes - العيادي برباس" },
    { value: "Ferdjioua", label: "Ferdjioua - فرجيوة" },
    { value: "Grarem Gouga", label: "Grarem Gouga - قرارم قوقة" },
    { value: "Hamala", label: "Hamala - حمالة" },
    { value: "Mila", label: "Mila - ميلة" },
    { value: "Minar Zarza", label: "Minar Zarza - مينار زرزة" },
    { value: "Oued Athmania", label: "Oued Athmenia - وادي العثمانية" },
    { value: "Oued Endja", label: "Oued Endja - وادي النجاء" },
    { value: "Oued Seguen", label: "Oued Seguen - وادي سقان" },
    { value: "Ouled Khalouf", label: "Ouled Khalouf - أولاد خلوف" },
    { value: "Rouached", label: "Rouached - الرواشد" },
    { value: "Sidi Khelifa", label: "Sidi Khelifa - سيدي خليفة" },
    { value: "Sidi Merouane", label: "Sidi Merouane - سيدي مروان" },
    { value: "Tadjenanet", label: "Tadjenanet - تاجنانت" },
    { value: "Tassadane Haddada", label: "Tassadane Haddada - تسادان حدادة" },
    { value: "Teleghma", label: "Teleghma - تلاغمة" },
    { value: "Terrai Bainen", label: "Terrai Bainem - ترعي بايبان" },
    { value: "Tessala Lemtaï", label: "Tessala - تسالة المطاعي" },
    { value: "Tiberguent", label: "Tiberguent - تيبرقنت" },
    { value: "Yahia Beni Guecha", label: "Yahia Beniguecha - يحيى بني قشة" },
    { value: "Zeghaia", label: "Zeghaia - الزغاية" },
  ],
  Relizane: [
    { value: "Aïn Rahma", label: "Ain Rahma - عين الرحمة" },
    { value: "Aïn Tarek", label: "Ain Tarek - عين طارق" },
    { value: "Ammi Moussa", label: "Ammi Moussa - عمي موسى" },
    { value: "Belassel Bouzegza", label: "Belaassel Bouzagza - بلعسل بوزقزة" },
    { value: "Bendaoud", label: "Bendaoud - بن داود" },
    { value: "Beni Dergoun", label: "Beni Dergoun - بني درقون" },
    { value: "Beni Zentis", label: "Beni Zentis - بني زنطيس" },
    { value: "Dar Ben Abdellah", label: "Dar Ben Abdelah - دار بن عبد الله" },
    { value: "Djidioua", label: "Djidiouia - جديوية" },
    { value: "El Guettar", label: "El-guettar - القطار" },
    { value: "El Hamadna", label: "El Hmadna - الحمادنة" },
    { value: "El Hassi", label: "El Hassi - الحاسي" },
    { value: "El Matmar", label: "El-matmar - المطمر" },
    { value: "El Ouldja", label: "El Ouldja - الولجة" },
    { value: "Had Echkalla", label: "Had Echkalla - حد الشكالة" },
    { value: "Hamri", label: "Hamri - الحمري" },
    { value: "Kalaa", label: "Kalaa - القلعة" },
    { value: "Lahlef", label: "Lahlef - الأحلاف" },
    { value: "Mazouna", label: "Mazouna - مازونة" },
    { value: "Mediouna", label: "Mediouna - مديونة" },
    { value: "Mendes", label: "Mendes - منداس" },
    { value: "Merdja Sidi Abed", label: "Merdja Sidi Abed - مرجة سيدي عابد" },
    { value: "Ouarizane", label: "Ouarizane - ورزان" },
    { value: "Oued El Djemaa", label: "Oued El Djemaa - وادي الجمعة" },
    { value: "Oued Essalem", label: "Oued Essalem - وادي السلام" },
    { value: "Oued Rhiou", label: "Oued Rhiou - وادي رهيو" },
    { value: "Ouled Aiche", label: "Ouled Aiche - أولاد عيش" },
    {
      value: "Ouled Sidi Mihoub",
      label: "Ouled Sidi Mihoub - أولاد سيدي ميهوب",
    },
    { value: "Ramka", label: "Ramka - رمقة" },
    { value: "Relizane", label: "Relizane - غليزان" },
    { value: "Sidi Khettab", label: "Sidi Khettab - سيدي خطاب" },
    { value: "Sidi Lazreg", label: "Sidi Lazreg - سيدي لزرق" },
    {
      value: "Sidi M'Hamed Ben Ali",
      label: "Sidi Mhamed Benali - سيدي أحمد بن علي",
    },
    {
      value: "Sidi M'Hamed Benaouda",
      label: "Sidi Mhamed Benaouda - سيدي امحمد بن عودة",
    },
    { value: "Sidi Saada", label: "Sidi Saada - سيدي سعادة" },
    { value: "Souk El Had", label: "Souk El Had - سوق الأحد" },
    { value: "Yellel", label: "Yellel - يلل" },
    { value: "Zemmora", label: "Zemmoura - زمورة" },
  ],
};

module.exports = { data };
